
/*                                                                                            */
/* core-sequences.sql                                                                         */
/*                                                                                            */
/* This file was generated automatically by dumpSchema.pl on Wed Feb 12 12:22:27 EST 2003     */
/*                                                                                            */

SET ECHO ON
SPOOL core-sequences.log

CREATE SEQUENCE Coretest.ALGORITHMIMPLEMENTATION_SQ START WITH 1;
CREATE SEQUENCE Coretest.ALGORITHMINVOCATION_SQ START WITH 1;
CREATE SEQUENCE Coretest.ALGORITHMPARAMKEYTYPE_SQ START WITH 1;
CREATE SEQUENCE Coretest.ALGORITHMPARAMKEY_SQ START WITH 1;
CREATE SEQUENCE Coretest.ALGORITHMPARAM_SQ START WITH 1;
CREATE SEQUENCE Coretest.ALGORITHM_SQ START WITH 1;
CREATE SEQUENCE Coretest.CATEGORY_SQ START WITH 1;
CREATE SEQUENCE Coretest.DATABASEDOCUMENTATION_SQ START WITH 1;
CREATE SEQUENCE Coretest.DATABASEINFO_SQ START WITH 1;
CREATE SEQUENCE Coretest.GENERALDOCUMENTATION_SQ START WITH 1;
CREATE SEQUENCE Coretest.GROUPINFO_SQ START WITH 1;
CREATE SEQUENCE Coretest.MACHINE_SQ START WITH 1;
CREATE SEQUENCE Coretest.PROJECTINFO_SQ START WITH 1;
CREATE SEQUENCE Coretest.TABLECATEGORY_SQ START WITH 1;
CREATE SEQUENCE Coretest.TABLEINFO_SQ START WITH 1;
CREATE SEQUENCE Coretest.USERDATABASE_SQ START WITH 1;
CREATE SEQUENCE Coretest.USERGROUP_SQ START WITH 1;
CREATE SEQUENCE Coretest.USERINFO_SQ START WITH 1;
CREATE SEQUENCE Coretest.USERPROJECT_SQ START WITH 1;
CREATE SEQUENCE Coretest.WORKFLOWBLACKBOARD_SQ START WITH 1;
CREATE SEQUENCE Coretest.WORKFLOWEDGESQL_SQ START WITH 1;
CREATE SEQUENCE Coretest.WORKFLOWEDGE_SQ START WITH 1;
CREATE SEQUENCE Coretest.WORKFLOWINIT_SQ START WITH 1;
CREATE SEQUENCE Coretest.WORKFLOWNODEIMP_SQ START WITH 1;
CREATE SEQUENCE Coretest.WORKFLOWSTATUS_SQ START WITH 1;
CREATE SEQUENCE Coretest.WORKFLOW_SQ START WITH 1;

/* 26 sequences(s) */

SPOOL OFF
SET ECHO OFF
DISCONNECT
EXIT
