
/*                                                                                            */
/* dotsver-pkey-constraints.sql                                                               */
/*                                                                                            */
/* This file was generated automatically by dumpSchema.pl on Wed Feb 12 12:28:25 EST 2003     */
/*                                                                                            */

SET ECHO ON
SPOOL dotsver-pkey-constraints.log

/* PRIMARY KEY CONSTRAINTS */

alter table DoTStestVer.AACOMMENTVER add constraint PK_AACOMMENTVER primary key (AA_COMMENT_ID,MODIFICATION_DATE);
alter table DoTStestVer.AAENTRYVER add constraint PK_AAENTRYVER primary key (AA_ENTRY_ID,MODIFICATION_DATE);
alter table DoTStestVer.AAFAMILYEXPERIMENTVER add constraint PK_AAFAMILYEXPERIMENTVER primary key (AA_FAMILY_EXPERIMENT_ID,MODIFICATION_DATE);
alter table DoTStestVer.AAGENESYNONYMVER add constraint PK_AAGENESYNONYMVER primary key (AA_GENE_SYNONYM_ID,MODIFICATION_DATE);
alter table DoTStestVer.AAGENEVER add constraint PK_AAGENEVER primary key (AA_GENE_ID,MODIFICATION_DATE);
alter table DoTStestVer.AALOCATIONVER add constraint PK_AALOCATIONVER primary key (AA_LOCATION_ID,MODIFICATION_DATE);
alter table DoTStestVer.AAMOTIFGOTERMRULEVER add constraint PK_AAMOTIFGOTERMRULEVER primary key (AA_MOTIF_GO_TERM_RULE_ID,MODIFICATION_DATE);
alter table DoTStestVer.AASEQGROUPEXPERIMENTIMPVER add constraint PK_AASEQGROUPEXPERIMENTIMPVER primary key (AA_SEQ_GROUP_EXPERIMENT_ID,MODIFICATION_DATE);
alter table DoTStestVer.AASEQUENCEDBREFVER add constraint PK_AASEQUENCEDBREFVER primary key (AA_SEQUENCE_DB_REF_ID,MODIFICATION_DATE);
alter table DoTStestVer.AASEQUENCEFAMILYVER add constraint PK_AASEQUENCEFAMILYVER primary key (AA_SEQUENCE_FAMILY_ID,MODIFICATION_DATE);
alter table DoTStestVer.AASEQUENCEGROUPFAMILYVER add constraint PK_AASEQUENCEGROUPFAMILYVER primary key (AA_SEQUENCE_GROUP_FAMILY_ID,MODIFICATION_DATE);
alter table DoTStestVer.AASEQUENCEGROUPIMPVER add constraint PK_AASEQUENCEGROUPIMPVER primary key (AA_SEQUENCE_GROUP_ID,MODIFICATION_DATE);
alter table DoTStestVer.AASEQUENCEIMPVER add constraint PK_AASEQUENCEIMPVER primary key (AA_SEQUENCE_ID,MODIFICATION_DATE);
alter table DoTStestVer.AASEQUENCEKEYWORDVER add constraint PK_AASEQUENCEKEYWORDVER primary key (AA_SEQUENCE_KEYWORD_ID,MODIFICATION_DATE);
alter table DoTStestVer.AASEQUENCEORGANELLEVER add constraint PK_AASEQUENCEORGANELLEVER primary key (AA_SEQUENCE_ORGANELLE_ID,MODIFICATION_DATE);
alter table DoTStestVer.AASEQUENCEREFVER add constraint PK_AASEQUENCEREFVER primary key (AA_SEQUENCE_REF_ID,MODIFICATION_DATE);
alter table DoTStestVer.AASEQUENCESEQUENCEGROUPVER add constraint PK_AASEQUENCESEQUENCEGROUPVER primary key (AA_SEQUENCE_SEQUENCE_GROUP_ID,MODIFICATION_DATE);
alter table DoTStestVer.AASEQUENCETAXONVER add constraint PK_AASEQUENCETAXONVER primary key (AA_SEQUENCE_TAXON_ID,MODIFICATION_DATE);
alter table DoTStestVer.ANATOMYLIBRARYVER add constraint PK_ANATOMYLIBRARYVER primary key (ANATOMY_LIBRARY_ID,MODIFICATION_DATE);
alter table DoTStestVer.ANATOMYLOEVER add constraint PK_ANATOMYLOEVER primary key (ANATOMY_LOE_ID);
alter table DoTStestVer.ASSEMBLYANATOMYPERCENTVER add constraint PK_ASSEMBLYANATOMYPERCENTVER primary key (ASSEMBLY_ANATOMY_PERCENT_ID,MODIFICATION_DATE);
alter table DoTStestVer.ASSEMBLYSEQUENCESNPVER add constraint PK_ASSEMBLYSEQUENCESNPVER primary key (ASSEMBLY_SEQUENCE_SNP_ID,MODIFICATION_DATE);
alter table DoTStestVer.ASSEMBLYSEQUENCEVER add constraint PK_ASSEMBLYSEQUENCEVER primary key (ASSEMBLY_SEQUENCE_ID,MODIFICATION_DATE);
alter table DoTStestVer.ASSEMBLYSNPVER add constraint PK_ASSEMBLYSNPVER primary key (ASSEMBLY_SNP_ID,MODIFICATION_DATE);
alter table DoTStestVer.ATTRIBUTIONVER add constraint PK_ATTRIBUTIONVER primary key (ATTRIBUTION_ID,MODIFICATION_DATE);
alter table DoTStestVer.BESTSIMILARITYPAIRVER add constraint PK_BESTSIMILARITYPAIRVER primary key (BEST_SIMILARITY_PAIR_ID,MODIFICATION_DATE);
alter table DoTStestVer.CLONEINSETVER add constraint PK_CLONEINSETVER primary key (CLONE_IN_SET_ID,MODIFICATION_DATE);
alter table DoTStestVer.CLONESETVER add constraint PK_CLONESETVER primary key (CLONE_SET_ID,MODIFICATION_DATE);
alter table DoTStestVer.CLONEVER add constraint PK_CLONEVER primary key (CLONE_ID,MODIFICATION_DATE);
alter table DoTStestVer.COMMENTNAMEVER add constraint PK_COMMENTNAMEVER primary key (COMMENT_NAME_ID,MODIFICATION_DATE);
alter table DoTStestVer.COMMENTSVER add constraint PK_COMMENTSVER primary key (COMMENTS_ID,MODIFICATION_DATE);
alter table DoTStestVer.COMPLEXANATOMYVER add constraint PK_COMPLEXANATOMYVER primary key (COMPLEX_ANATOMY_ID,MODIFICATION_DATE);
alter table DoTStestVer.COMPLEXCOMPONENTVER add constraint PK_COMPLEXCOMPONENTVER primary key (COMPLEX_COMPONENT_ID,MODIFICATION_DATE);
alter table DoTStestVer.COMPLEXTYPEVER add constraint PK_COMPLEXTYPEVER primary key (COMPLEX_TYPE_ID,MODIFICATION_DATE);
alter table DoTStestVer.COMPLEXVER add constraint PK_COMPLEXVER primary key (COMPLEX_ID,MODIFICATION_DATE);
alter table DoTStestVer.CONSISTENTALIGNMENTVER add constraint PK_CONSISTENTALIGNMENTVER primary key (CONSISTENT_ALIGNMENT_ID,MODIFICATION_DATE);
alter table DoTStestVer.DBREFNAFEATUREVER add constraint PK_DBREFNAFEATUREVER primary key (DB_REF_NA_FEATURE_ID,MODIFICATION_DATE);
alter table DoTStestVer.DBREFPFAMENTRYVER add constraint PK_DBREFPFAMENTRYVER primary key (DB_REF_PFAM_ENTRY_ID,MODIFICATION_DATE);
alter table DoTStestVer.EFFECTORACTIONTYPEVER add constraint PK_EFFECTORACTIONTYPEVER primary key (EFFECTOR_ACTION_TYPE_ID,MODIFICATION_DATE);
alter table DoTStestVer.ENDSEQUENCEPAIRMAPVER add constraint PK_ENDSEQUENCEPAIRMAPVER primary key (END_SEQUENCE_PAIR_MAP_ID,MODIFICATION_DATE);
alter table DoTStestVer.EPCRVER add constraint PK_EPCRVER primary key (EPCR_ID,MODIFICATION_DATE);
alter table DoTStestVer.ESTVER add constraint PK_ESTVER primary key (EST_ID,MODIFICATION_DATE);
alter table DoTStestVer.EVIDENCEVER add constraint PK_EVIDENCEVER primary key (EVIDENCE_ID,MODIFICATION_DATE);
alter table DoTStestVer.EXONLOCATIONVER add constraint PK_EXONLOCATIONVER primary key (EXON_LOCATION_ID,MODIFICATION_DATE);
alter table DoTStestVer.FAMILYGENEVER add constraint PK_FAMILYGENEVER primary key (FAMILY_GENE_ID,MODIFICATION_DATE);
alter table DoTStestVer.FAMILYPROTEINVER add constraint PK_FAMILYPROTEINVER primary key (FAMILY_PROTEIN_ID,MODIFICATION_DATE);
alter table DoTStestVer.FAMILYVER add constraint PK_FAMILYVER primary key (FAMILY_ID,MODIFICATION_DATE);
alter table DoTStestVer.FEATURENAMEVER add constraint PK_FEATURENAMEVER primary key (FEATURE_NAME_ID,MODIFICATION_DATE);
alter table DoTStestVer.FINGERPRINTCLONECONTIGVER add constraint PK_FINGERPRINTCLONECONTIGVER primary key (FINGERPRINT_CLONE_CONTIG_ID,MODIFICATION_DATE);
alter table DoTStestVer.FINGERPRINTCLONEMARKERVER add constraint PK_FINGERPRINTCLONEMARKERVER primary key (FINGERPRINT_CLONE_MARKER_ID,MODIFICATION_DATE);
alter table DoTStestVer.FINGERPRINTCLONEVER add constraint PK_FINGERPRINTCLONEVER primary key (FINGERPRINT_CLONE_ID,MODIFICATION_DATE);
alter table DoTStestVer.FINGERPRINTCONTIGVER add constraint PK_FINGERPRINTCONTIGVER primary key (FINGERPRINT_CONTIG_ID,MODIFICATION_DATE);
alter table DoTStestVer.FINGERPRINTMAPVER add constraint PK_FINGERPRINTMAPVER primary key (FINGERPRINT_MAP_ID,MODIFICATION_DATE);
alter table DoTStestVer.GENEALIASVER add constraint PK_GENEALIASVER primary key (GENE_ALIAS_ID,MODIFICATION_DATE);
alter table DoTStestVer.GENECATEGORYVER add constraint PK_GENECATEGORYVER primary key (GENE_CATEGORY_ID,MODIFICATION_DATE);
alter table DoTStestVer.GENECHROMOSOMALLOCATIONVER add constraint PK_GENECHROMOSOMALLOCATIONVER primary key (GENE_CHROMOSOMAL_LOCATION_ID,MODIFICATION_DATE);
alter table DoTStestVer.GENEFAMILYRELATIONVER add constraint PK_GENEFAMILYRELATIONVER primary key (GENE_FAMILY_RELATION_ID,MODIFICATION_DATE);
alter table DoTStestVer.GENEFAMILYVER add constraint PK_GENEFAMILYVER primary key (GENE_FAMILY_ID,MODIFICATION_DATE);
alter table DoTStestVer.GENEFEATURESAGETAGLINKVER add constraint PK_GENEFEATURESAGETAGLINKVER primary key (GENE_FEATURE_SAGE_TAG_LINK_ID,MODIFICATION_DATE);
alter table DoTStestVer.GENEFEATURESEQOVERLAPVER add constraint PK_GENEFEATURESEQOVERLAPVER primary key (GENE_FEATURE_SEQ_OVERLAP_ID,MODIFICATION_DATE);
alter table DoTStestVer.GENEINSTANCECATEGORYVER add constraint PK_GENEINSTANCECATEGORYVER primary key (GENE_INSTANCE_CATEGORY_ID);
alter table DoTStestVer.GENEINSTANCEVER add constraint PK_GENEINSTANCEVER primary key (GENE_INSTANCE_ID);
alter table DoTStestVer.GENESUPERFAMILYVER add constraint PK_GENESUPERFAMILYVER primary key (GENE_SUPER_FAMILY_ID,MODIFICATION_DATE);
alter table DoTStestVer.GENESYNONYMVER add constraint PK_GENESYNONYMVER primary key (GENE_SYNONYM_ID,MODIFICATION_DATE);
alter table DoTStestVer.GENETRAPASSEMBLYVER add constraint PK_GENETRAPASSEMBLYVER primary key (GENE_TRAP_ASSEMBLY_ID,MODIFICATION_DATE);
alter table DoTStestVer.INDEXWORDLINKVER add constraint PK_INDEXWORDLINKVER primary key (INDEX_WORD_LINK_ID,MODIFICATION_DATE);
alter table DoTStestVer.INDEXWORDSIMLINKVER add constraint PK_INDEXWORDSIMLINKVER primary key (INDEX_WORD_SIM_LINK_ID,MODIFICATION_DATE);
alter table DoTStestVer.INDEXWORDVER add constraint PK_INDEXWORDVER primary key (INDEX_WORD_ID,MODIFICATION_DATE);
alter table DoTStestVer.INTERACTIONINTERACTIONLOEVER add constraint PK_INTERACTINTERACTIONLOEVER primary key (INTERACTION_INTERACTION_LOE_ID,MODIFICATION_DATE);
alter table DoTStestVer.INTERACTIONLOEVER add constraint PK_INTERACTIONLOEVER primary key (INTERACTION_LOE_ID,MODIFICATION_DATE);
alter table DoTStestVer.INTERACTIONTYPEVER add constraint PK_INTERACTIONTYPEVER primary key (INTERACTION_TYPE_ID,MODIFICATION_DATE);
alter table DoTStestVer.INTERACTIONVER add constraint PK_INTERACTIONVER primary key (INTERACTION_ID,MODIFICATION_DATE);
alter table DoTStestVer.ISEXPRESSEDVER add constraint PK_ISEXPRESSEDVER primary key (IS_EXPRESSED_ID,MODIFICATION_DATE);
alter table DoTStestVer.KEYWORDVER add constraint PK_KEYWORDVER primary key (KEYWORD_ID,MODIFICATION_DATE);
alter table DoTStestVer.LIBRARYVER add constraint PK_LIBRARYVER primary key (LIBRARY_ID,MODIFICATION_DATE);
alter table DoTStestVer.MERGESPLITVER add constraint PK_MERGESPLITVER primary key (MERGE_SPLIT_ID,MODIFICATION_DATE);
alter table DoTStestVer.MOTIFVER add constraint PK_MOTIFVER primary key (MOTIF_ID,MODIFICATION_DATE);
alter table DoTStestVer.NACOMMENTVER add constraint PK_NACOMMENTVER primary key (NA_COMMENT_ID,MODIFICATION_DATE);
alter table DoTStestVer.NAENTRYVER add constraint PK_NAENTRYVER primary key (NA_ENTRY_ID,MODIFICATION_DATE);
alter table DoTStestVer.NAFEATRELATIONSHIPTYPEVER add constraint PK_NAFEATRELATIONSHIPTYPEVER primary key (NA_FEAT_RELATIONSHIP_TYPE_ID,MODIFICATION_DATE);
alter table DoTStestVer.NAFEATURECOMMENTVER add constraint PK_NAFEATURECOMMENTVER primary key (NA_FEATURE_COMMENT_ID,MODIFICATION_DATE);
alter table DoTStestVer.NAFEATURENAGENEVER add constraint PK_NAFEATURENAGENEVER primary key (NA_FEATURE_NA_GENE_ID,MODIFICATION_DATE);
alter table DoTStestVer.NAFEATURENAPROTEINVER add constraint PK_NAFEATURENAPROTEINVER primary key (NA_FEATURE_NA_PROTEIN_ID,MODIFICATION_DATE);
alter table DoTStestVer.NAFEATURENAPTVER add constraint PK_NAFEATURENAPTVER primary key (NA_FEATURE_NA_PT_ID,MODIFICATION_DATE);
alter table DoTStestVer.NAFEATURERELATIONSHIPVER add constraint PK_NAFEATURERELATIONSHIPVER primary key (NA_FEATURE_RELATIONSHIP_ID,MODIFICATION_DATE);
alter table DoTStestVer.NAGENEVER add constraint PK_NAGENEVER primary key (NA_GENE_ID,MODIFICATION_DATE);
alter table DoTStestVer.NALOCATIONVER add constraint PK_NALOCATIONVER primary key (NA_LOCATION_ID,MODIFICATION_DATE);
alter table DoTStestVer.NAPRIMARYTRANSCRIPTVER add constraint PK_NAPRIMARYTRANSCRIPTVER primary key (NA_PRIMARY_TRANSCRIPT_ID,MODIFICATION_DATE);
alter table DoTStestVer.NAPROTEINVER add constraint PK_NAPROTEINVER primary key (NA_PROTEIN_ID,MODIFICATION_DATE);
alter table DoTStestVer.NASEQCYTOLOCATIONVER add constraint PK_NASEQCYTOLOCATIONVER primary key (NA_SEQ_CYTO_LOCATION_ID,MODIFICATION_DATE);
alter table DoTStestVer.NASEQUENCEIMPVER add constraint PK_NASEQUENCEIMPVER primary key (NA_SEQUENCE_ID,MODIFICATION_DATE);
alter table DoTStestVer.NASEQUENCEKEYWORDVER add constraint PK_NASEQUENCEKEYWORDVER primary key (NA_SEQUENCE_KEYWORD_ID,MODIFICATION_DATE);
alter table DoTStestVer.NASEQUENCEORGANELLEVER add constraint PK_NASEQUENCEORGANELLEVER primary key (NA_SEQUENCE_ORGANELLE_ID,MODIFICATION_DATE);
alter table DoTStestVer.NASEQUENCEREFVER add constraint PK_NASEQUENCEREFVER primary key (NA_SEQUENCE_REF_ID,MODIFICATION_DATE);
alter table DoTStestVer.NRDBENTRYVER add constraint PK_NRDBENTRYVER primary key (NRDB_ENTRY_ID,MODIFICATION_DATE);
alter table DoTStestVer.OPTICALMAPALIGNMENTSPANVER add constraint PK_OPTICALMAPALIGNMENTSPANVER primary key (OPTICAL_MAP_ALIGNMENT_SPAN_ID,MODIFICATION_DATE);
alter table DoTStestVer.OPTICALMAPALIGNMENTVER add constraint PK_OPTICALMAPALIGNMENTVER primary key (OPTICAL_MAP_ALIGNMENT_ID,MODIFICATION_DATE);
alter table DoTStestVer.OPTICALMAPFRAGMENTVER add constraint PK_OPTICALMAPFRAGMENTVER primary key (OPTICAL_MAP_FRAGMENT_ID,MODIFICATION_DATE);
alter table DoTStestVer.OPTICALMAPVER add constraint PK_OPTICALMAPVER primary key (OPTICAL_MAP_ID,MODIFICATION_DATE);
alter table DoTStestVer.ORGANELLEVER add constraint PK_ORGANELLEVER primary key (ORGANELLE_ID,MODIFICATION_DATE);
alter table DoTStestVer.PATHWAYINTERACTIONVER add constraint PK_PATHWAYINTERACTIONVER primary key (PATHWAY_INTERACTION_ID,MODIFICATION_DATE);
alter table DoTStestVer.PATHWAYVER add constraint PK_PATHWAYVER primary key (PATHWAY_ID,MODIFICATION_DATE);
alter table DoTStestVer.PFAMENTRYVER add constraint PK_PFAMENTRYVER primary key (PFAM_ENTRY_ID,MODIFICATION_DATE);
alter table DoTStestVer.PROJECTLINKVER add constraint PK_PROJECTLINKVER primary key (PROJECT_LINK_ID,MODIFICATION_DATE);
alter table DoTStestVer.PROTEINCATEGORYVER add constraint PK_PROTEINCATEGORYVER primary key (PROTEIN_CATEGORY_ID,MODIFICATION_DATE);
alter table DoTStestVer.PROTEININSTANCEVER add constraint PK_PROTEININSTANCEVER primary key (PROTEIN_INSTANCE_ID,MODIFICATION_DATE);
alter table DoTStestVer.PROTEINPROPERTYTYPEVER add constraint PK_PROTEINPROPERTYTYPEVER primary key (PROTEIN_PROPERTY_TYPE_ID,MODIFICATION_DATE);
alter table DoTStestVer.PROTEINPROTEINCATEGORYVER add constraint PK_PROTEINPROTEINCATEGORYVER primary key (PROTEIN_PROTEIN_CATEGORY_ID,MODIFICATION_DATE);
alter table DoTStestVer.PROTEINSYNONYMVER add constraint PK_PROTEINSYNONYMVER primary key (PROTEIN_SYNONYM_ID,MODIFICATION_DATE);
alter table DoTStestVer.PROTEINVER add constraint PK_PROTEINVER primary key (PROTEIN_ID,MODIFICATION_DATE);
alter table DoTStestVer.REPEATTYPEVER add constraint PK_REPEATTYPEVER primary key (REPEAT_TYPE_ID,MODIFICATION_DATE);
alter table DoTStestVer.RHMAPMARKERVER add constraint PK_RHMAPMARKERVER primary key (RH_MAP_MARKER_ID,MODIFICATION_DATE);
alter table DoTStestVer.RHMAPVER add constraint PK_RHMAPVER primary key (RH_MAP_ID,MODIFICATION_DATE);
alter table DoTStestVer.RHMARKERVER add constraint PK_RHMARKERVER primary key (RH_MARKER_ID,MODIFICATION_DATE);
alter table DoTStestVer.RNAANATOMYLOEVER add constraint PK_RNAANATOMYLOEVER primary key (RNA_ANATOMY_LOE_ID,MODIFICATION_DATE);
alter table DoTStestVer.RNAANATOMYVER add constraint PK_RNAANATOMYVER primary key (RNA_ANATOMY_ID,MODIFICATION_DATE);
alter table DoTStestVer.RNACATEGORYVER add constraint PK_RNACATEGORYVER primary key (RNA_CATEGORY_ID,MODIFICATION_DATE);
alter table DoTStestVer.RNAFEATUREEXONVER add constraint PK_RNAFEATUREEXONVER primary key (RNA_FEATURE_EXON_ID,MODIFICATION_DATE);
alter table DoTStestVer.RNAICONSTRUCTVER add constraint PK_RNAICONSTRUCTVER primary key (RNAI_CONSTRUCT_ID,MODIFICATION_DATE);
alter table DoTStestVer.RNAINSTANCECATEGORYVER add constraint PK_RNAINSTANCECATEGORYVER primary key (RNA_INSTANCE_CATEGORY_ID,MODIFICATION_DATE);
alter table DoTStestVer.RNAINSTANCEVER add constraint PK_RNAINSTANCEVER primary key (RNA_INSTANCE_ID,MODIFICATION_DATE);
alter table DoTStestVer.RNARNACATEGORYVER add constraint PK_RNARNACATEGORYVER primary key (RNA_RNA_CATEGORY_ID,MODIFICATION_DATE);
alter table DoTStestVer.RNAVER add constraint PK_RNAVER primary key (RNA_ID,MODIFICATION_DATE);
alter table DoTStestVer.ROWSETMEMBERVER add constraint PK_ROWSETMEMBERVER primary key (ROW_SET_MEMBER_ID,MODIFICATION_DATE);
alter table DoTStestVer.ROWSETVER add constraint PK_ROWSETVER primary key (ROW_SET_ID,MODIFICATION_DATE);
alter table DoTStestVer.SECONDARYACCSVER add constraint PK_SECONDARYACCSVER primary key (SECONDARY_ACCS_ID,MODIFICATION_DATE);
alter table DoTStestVer.SEQGROUPEXPERIMENTIMPVER add constraint PK_SEQGROUPEXPERIMENTIMPVER primary key (SEQ_GROUP_EXPERIMENT_ID,MODIFICATION_DATE);
alter table DoTStestVer.SEQUENCEFAMILYEXPERIMENTVER add constraint PK_SEQUENCEFAMILYEXPERIMENTVER primary key (SEQUENCE_FAMILY_EXPERIMENT_ID,MODIFICATION_DATE);
alter table DoTStestVer.SEQUENCEFAMILYVER add constraint PK_SEQUENCEFAMILYVER primary key (SEQUENCE_FAMILY_ID,MODIFICATION_DATE);
alter table DoTStestVer.SEQUENCEGROUPFAMILYVER add constraint PK_SEQUENCEGROUPFAMILYVER primary key (SEQUENCE_GROUP_FAMILY_ID,MODIFICATION_DATE);
alter table DoTStestVer.SEQUENCEGROUPIMPVER add constraint PK_SEQUENCEGROUPIMPVER primary key (SEQUENCE_GROUP_ID,MODIFICATION_DATE);
alter table DoTStestVer.SEQUENCEPIECEVER add constraint PK_SEQUENCEPIECEVER primary key (SEQUENCE_PIECE_ID,MODIFICATION_DATE);
alter table DoTStestVer.SEQUENCESEQUENCEGROUPVER add constraint PK_SEQUENCESEQUENCEGROUPVER primary key (SEQUENCE_SEQUENCE_GROUP_ID,MODIFICATION_DATE);
alter table DoTStestVer.SEQUENCETYPEVER add constraint PK_SEQUENCETYPEVER primary key (SEQUENCE_TYPE_ID,MODIFICATION_DATE);
alter table DoTStestVer.SIMILARITYSPANVER add constraint PK_SIMILARITYSPANVER primary key (SIMILARITY_SPAN_ID,MODIFICATION_DATE);
alter table DoTStestVer.SIMILARITYVER add constraint PK_SIMILARITYVER primary key (SIMILARITY_ID,MODIFICATION_DATE);
alter table DoTStestVer.TRANSLATEDAAFEATSEGVER add constraint PK_TRANSLATEDAAFEATSEGVER primary key (TRANSLATED_AA_FEAT_SEG_ID,MODIFICATION_DATE);


/* 137 primary key constraint(s) */

SPOOL OFF
SET ECHO OFF
DISCONNECT
EXIT
