
/*                                                                                            */
/* dots-constraints.sql                                                                       */
/*                                                                                            */
/* This file was generated automatically by dumpSchema.pl on Wed Feb 12 12:26:08 EST 2003     */
/*                                                                                            */

SET ECHO ON
SPOOL dots-constraints.log

/* NON-PRIMARY KEY CONSTRAINTS */

/* AACOMMENT */
alter table DoTStest.AACOMMENT add constraint AACOMMENT_FK04 foreign key (AA_SEQUENCE_ID) references DoTStest.AASEQUENCEIMP (AA_SEQUENCE_ID);
alter table DoTStest.AACOMMENT add constraint AACOMMENT_FK05 foreign key (COMMENT_NAME_ID) references DoTStest.COMMENTNAME (COMMENT_NAME_ID);

/* AAENTRY */
alter table DoTStest.AAENTRY add constraint AAENTRY_FK04 foreign key (AA_SEQUENCE_ID) references DoTStest.AASEQUENCEIMP (AA_SEQUENCE_ID);

/* AAFAMILYEXPERIMENT */
alter table DoTStest.AAFAMILYEXPERIMENT add constraint AAFAMILYEXPERIMENT_FK01 foreign key (AA_ORTHOLOG_EXPERIMENT_ID) references DoTStest.AASEQGROUPEXPERIMENTIMP (AA_SEQ_GROUP_EXPERIMENT_ID);
alter table DoTStest.AAFAMILYEXPERIMENT add constraint AAFAMILYEXPERIMENT_FK02 foreign key (AA_PARALOG_EXPERIMENT_ID) references DoTStest.AASEQGROUPEXPERIMENTIMP (AA_SEQ_GROUP_EXPERIMENT_ID);

/* AAFEATUREIMP */
alter table DoTStest.AAFEATUREIMP add constraint AAFEATUREIMP_FK01 foreign key (AA_SEQUENCE_ID) references DoTStest.AASEQUENCEIMP (AA_SEQUENCE_ID);
alter table DoTStest.AAFEATUREIMP add constraint AAFEATUREIMP_FK02 foreign key (FEATURE_NAME_ID) references DoTStest.FEATURENAME (FEATURE_NAME_ID);
alter table DoTStest.AAFEATUREIMP add constraint AAFEATUREIMP_FK03 foreign key (PARENT_ID) references DoTStest.AAFEATUREIMP (AA_FEATURE_ID);
alter table DoTStest.AAFEATUREIMP add constraint AAFEATUREIMP_FK04 foreign key (NA_FEATURE_ID) references DoTStest.NAFEATUREIMP (NA_FEATURE_ID);
alter table DoTStest.AAFEATUREIMP add constraint AAFEATUREIMP_FK05 foreign key (SEQUENCE_ONTOLOGY_ID) references SRestest.SEQUENCEONTOLOGY (SEQUENCE_ONTOLOGY_ID);
alter table DoTStest.AAFEATUREIMP add constraint AAFEATUREIMP_FK06 foreign key (PFAM_ENTRY_ID) references DoTStest.PFAMENTRY (PFAM_ENTRY_ID);
alter table DoTStest.AAFEATUREIMP add constraint AAFEATUREIMP_FK07 foreign key (MOTIF_AA_SEQUENCE_ID) references DoTStest.AASEQUENCEIMP (AA_SEQUENCE_ID);
alter table DoTStest.AAFEATUREIMP add constraint AAFEATUREIMP_FK08 foreign key (REPEAT_TYPE_ID) references DoTStest.REPEATTYPE (REPEAT_TYPE_ID);
alter table DoTStest.AAFEATUREIMP add constraint AAFEATUREIMP_FK09 foreign key (EXTERNAL_DATABASE_RELEASE_ID) references SRestest.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_RELEASE_ID);
alter table DoTStest.AAFEATUREIMP add constraint AAFEATUREIMP_FK10 foreign key (PREDICTION_ALGORITHM_ID) references Coretest.ALGORITHM (ALGORITHM_ID);
alter table DoTStest.AAFEATUREIMP add constraint AAFEATUREIMP_FK11 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);

/* AAGENE */
alter table DoTStest.AAGENE add constraint AAGENE_FK04 foreign key (AA_SEQUENCE_ID) references DoTStest.AASEQUENCEIMP (AA_SEQUENCE_ID);

/* AAGENESYNONYM */
alter table DoTStest.AAGENESYNONYM add constraint AAGENESYNONYM_FK04 foreign key (AA_GENE_ID) references DoTStest.AAGENE (AA_GENE_ID);

/* AALOCATION */
alter table DoTStest.AALOCATION add constraint AALOCATION_FK04 foreign key (AA_FEATURE_ID) references DoTStest.AAFEATUREIMP (AA_FEATURE_ID);

/* AAMOTIFGOTERMRULE */
alter table DoTStest.AAMOTIFGOTERMRULE add constraint AAMOTIFGOTERMRULE_FK01 foreign key (AA_MOTIF_GO_TERM_RULE_SET_ID) references DoTStest.AAMOTIFGOTERMRULESET (AA_MOTIF_GO_TERM_RULE_SET_ID);
alter table DoTStest.AAMOTIFGOTERMRULE add constraint AAMOTIFGOTERMRULE_FK02 foreign key (GO_TERM_ID) references SRestest.GOTERM (GO_TERM_ID);
alter table DoTStest.AAMOTIFGOTERMRULE add constraint AAMOTIFGOTERMRULE_FK03 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);
alter table DoTStest.AAMOTIFGOTERMRULE add constraint AAMOTIFGOTERMRULE_FK04 foreign key (REVIEWER_ID) references Coretest.USERINFO (USER_ID);

/* AAMOTIFGOTERMRULESET */
alter table DoTStest.AAMOTIFGOTERMRULESET add constraint AAMOTIFGOTERMRULESET_FK01 foreign key (AA_SEQUENCE_ID_1) references DoTStest.AASEQUENCEIMP (AA_SEQUENCE_ID);
alter table DoTStest.AAMOTIFGOTERMRULESET add constraint AAMOTIFGOTERMRULESET_FK02 foreign key (AA_SEQUENCE_ID_2) references DoTStest.AASEQUENCEIMP (AA_SEQUENCE_ID);
alter table DoTStest.AAMOTIFGOTERMRULESET add constraint AAMOTIFGOTERMRULESET_FK03 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);
alter table DoTStest.AAMOTIFGOTERMRULESET add constraint AAMOTIFGOTERMRULESET_FK04 foreign key (REVIEWER_ID) references Coretest.USERINFO (USER_ID);

/* AASEQGROUPEXPERIMENTIMP */

/* AASEQUENCEDBREF */
alter table DoTStest.AASEQUENCEDBREF add constraint AASEQUENCEDBREF_FK04 foreign key (DB_REF_ID) references SRestest.DBREF (DB_REF_ID);
alter table DoTStest.AASEQUENCEDBREF add constraint AASEQUENCEDBREF_FK05 foreign key (AA_SEQUENCE_ID) references DoTStest.AASEQUENCEIMP (AA_SEQUENCE_ID);

/* AASEQUENCEFAMILY */
alter table DoTStest.AASEQUENCEFAMILY add constraint AASEQUENCEFAMILY_FK01 foreign key (AA_FAMILY_EXPERIMENT_ID) references DoTStest.AAFAMILYEXPERIMENT (AA_FAMILY_EXPERIMENT_ID);

/* AASEQUENCEGROUPFAMILY */
alter table DoTStest.AASEQUENCEGROUPFAMILY add constraint AASEQUENCEGROUPFAMILY_FK01 foreign key (AA_SEQUENCE_FAMILY_ID) references DoTStest.AASEQUENCEFAMILY (AA_SEQUENCE_FAMILY_ID);
alter table DoTStest.AASEQUENCEGROUPFAMILY add constraint AASEQUENCEGROUPFAMILY_FK02 foreign key (AA_SEQUENCE_GROUP_ID) references DoTStest.AASEQUENCEGROUPIMP (AA_SEQUENCE_GROUP_ID);

/* AASEQUENCEGROUPIMP */
alter table DoTStest.AASEQUENCEGROUPIMP add constraint AASEQUENCEGROUPIMP_FK01 foreign key (AA_SEQ_GROUP_EXPERIMENT_ID) references DoTStest.AASEQGROUPEXPERIMENTIMP (AA_SEQ_GROUP_EXPERIMENT_ID);

/* AASEQUENCEIMP */
alter table DoTStest.AASEQUENCEIMP add constraint AASEQUENCEIMP_FK04 foreign key (EXTERNAL_DATABASE_RELEASE_ID) references SRestest.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_RELEASE_ID);
alter table DoTStest.AASEQUENCEIMP add constraint AASEQUENCEIMP_FK05 foreign key (SOURCE_AA_SEQUENCE_ID) references DoTStest.AASEQUENCEIMP (AA_SEQUENCE_ID);

/* AASEQUENCEKEYWORD */
alter table DoTStest.AASEQUENCEKEYWORD add constraint AASEQUENCEKEYWORD_FK04 foreign key (KEYWORD_ID) references DoTStest.KEYWORD (KEYWORD_ID);
alter table DoTStest.AASEQUENCEKEYWORD add constraint AASEQUENCEKEYWORD_FK05 foreign key (AA_SEQUENCE_ID) references DoTStest.AASEQUENCEIMP (AA_SEQUENCE_ID);

/* AASEQUENCEORGANELLE */
alter table DoTStest.AASEQUENCEORGANELLE add constraint AASEQUENCEORGANELLE_FK04 foreign key (ORGANELLE_ID) references DoTStest.ORGANELLE (ORGANELLE_ID);
alter table DoTStest.AASEQUENCEORGANELLE add constraint AASEQUENCEORGANELLE_FK05 foreign key (AA_SEQUENCE_ID) references DoTStest.AASEQUENCEIMP (AA_SEQUENCE_ID);

/* AASEQUENCEREF */
alter table DoTStest.AASEQUENCEREF add constraint AASEQUENCEREF_FK01 foreign key (REFERENCE_ID) references SRestest.REFERENCE (REFERENCE_ID);
alter table DoTStest.AASEQUENCEREF add constraint AASEQUENCEREF_FK02 foreign key (AA_SEQUENCE_ID) references DoTStest.AASEQUENCEIMP (AA_SEQUENCE_ID);

/* AASEQUENCESEQUENCEGROUP */
alter table DoTStest.AASEQUENCESEQUENCEGROUP add constraint AASEQUENCESEQUENCEGROUP_FK01 foreign key (AA_SEQUENCE_ID) references DoTStest.AASEQUENCEIMP (AA_SEQUENCE_ID);
alter table DoTStest.AASEQUENCESEQUENCEGROUP add constraint AASEQUENCESEQUENCEGROUP_FK02 foreign key (AA_SEQUENCE_GROUP_ID) references DoTStest.AASEQUENCEGROUPIMP (AA_SEQUENCE_GROUP_ID);

/* AASEQUENCETAXON */
alter table DoTStest.AASEQUENCETAXON add constraint AASEQUENCETAXON_FK03 foreign key (TAXON_ID) references SRestest.TAXON (TAXON_ID);
alter table DoTStest.AASEQUENCETAXON add constraint AASEQUENCETAXON_FK05 foreign key (AA_SEQUENCE_ID) references DoTStest.AASEQUENCEIMP (AA_SEQUENCE_ID);

/* ALLELE */
alter table DoTStest.ALLELE add constraint ALLELE_FK01 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);
alter table DoTStest.ALLELE add constraint ALLELE_FK02 foreign key (GENE_ID) references DoTStest.GENE (GENE_ID);
alter table DoTStest.ALLELE add constraint ALLELE_FK03 foreign key (MUTAGEN_ID) references SRestest.MUTAGEN (MUTAGEN_ID);

/* ALLELECOMPLEMENTATION */
alter table DoTStest.ALLELECOMPLEMENTATION add constraint ALLELECOMPLEMENTATION_FK01 foreign key (COMPLEMENTATION_ID) references DoTStest.COMPLEMENTATION (COMPLEMENTATION_ID);
alter table DoTStest.ALLELECOMPLEMENTATION add constraint ALLELECOMPLEMENTATION_FK02 foreign key (ALLELE_ID) references DoTStest.ALLELE (ALLELE_ID);
alter table DoTStest.ALLELECOMPLEMENTATION add constraint ALLELECOMPLEMENTATION_FK03 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);

/* ALLELEINSTANCE */
alter table DoTStest.ALLELEINSTANCE add constraint ALLELEINSTANCE_FK01 foreign key (NA_FEATURE_ID) references DoTStest.NAFEATUREIMP (NA_FEATURE_ID);
alter table DoTStest.ALLELEINSTANCE add constraint ALLELEINSTANCE_FK02 foreign key (ALLELE_ID) references DoTStest.ALLELE (ALLELE_ID);
alter table DoTStest.ALLELEINSTANCE add constraint ALLELEINSTANCE_FK03 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);

/* ALLELEPHENOTYPE */
alter table DoTStest.ALLELEPHENOTYPE add constraint ALLELEPHENOTYPE_FK01 foreign key (PHENOTYPE_ID) references SRestest.PHENOTYPE (PHENOTYPE_ID);
alter table DoTStest.ALLELEPHENOTYPE add constraint ALLELEPHENOTYPE_FK02 foreign key (ALLELE_ID) references DoTStest.ALLELE (ALLELE_ID);
alter table DoTStest.ALLELEPHENOTYPE add constraint ALLELEPHENOTYPE_FK03 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);

/* ALLELEPHENOTYPECLASS */
alter table DoTStest.ALLELEPHENOTYPECLASS add constraint ALLELEPHENOTYPECLASS_FK01 foreign key (PHENOTYPE_CLASS_ID) references SRestest.PHENOTYPECLASS (PHENOTYPE_CLASS_ID);
alter table DoTStest.ALLELEPHENOTYPECLASS add constraint ALLELEPHENOTYPECLASS_FK02 foreign key (ALLELE_ID) references DoTStest.ALLELE (ALLELE_ID);
alter table DoTStest.ALLELEPHENOTYPECLASS add constraint ALLELEPHENOTYPECLASS_FK03 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);

/* ANATOMYLIBRARY */
alter table DoTStest.ANATOMYLIBRARY add constraint ANATOMYLIBRARY_FK04 foreign key (ANATOMY_ID) references SRestest.ANATOMY (ANATOMY_ID);

/* ANATOMYLOE */

/* ASSEMBLYANATOMYPERCENT */
alter table DoTStest.ASSEMBLYANATOMYPERCENT add constraint ASSEMBLYANATOMYPERCENT_FK01 foreign key (NA_SEQUENCE_ID) references DoTStest.NASEQUENCEIMP (NA_SEQUENCE_ID);
alter table DoTStest.ASSEMBLYANATOMYPERCENT add constraint ASSEMBLYANATOMYPERCENT_FK02 foreign key (TAXON_ID) references SRestest.TAXON (TAXON_ID);
alter table DoTStest.ASSEMBLYANATOMYPERCENT add constraint ASSEMBLYANATOMYPERCENT_FK03 foreign key (ANATOMY_ID) references SRestest.ANATOMY (ANATOMY_ID);

/* ASSEMBLYSEQUENCE */
alter table DoTStest.ASSEMBLYSEQUENCE add constraint ASSEMBLYSEQUENCE_FK04 foreign key (NA_SEQUENCE_ID) references DoTStest.NASEQUENCEIMP (NA_SEQUENCE_ID);
alter table DoTStest.ASSEMBLYSEQUENCE add constraint ASSEMBLYSEQUENCE_FK05 foreign key (ASSEMBLY_NA_SEQUENCE_ID) references DoTStest.NASEQUENCEIMP (NA_SEQUENCE_ID);

/* ASSEMBLYSEQUENCESNP */
alter table DoTStest.ASSEMBLYSEQUENCESNP add constraint ASSEMBLYSEQUENCESNP_FK01 foreign key (ASSEMBLY_SEQUENCE_ID) references DoTStest.ASSEMBLYSEQUENCE (ASSEMBLY_SEQUENCE_ID);
alter table DoTStest.ASSEMBLYSEQUENCESNP add constraint ASSEMBLYSEQUENCESNP_FK02 foreign key (ASSEMBLY_SNP_ID) references DoTStest.ASSEMBLYSNP (ASSEMBLY_SNP_ID);

/* ASSEMBLYSNP */
alter table DoTStest.ASSEMBLYSNP add constraint ASSEMBLYSNP_FK01 foreign key (NA_SEQUENCE_ID) references DoTStest.NASEQUENCEIMP (NA_SEQUENCE_ID);

/* ATTRIBUTION */
alter table DoTStest.ATTRIBUTION add constraint ATTRIBUTION_FK01 foreign key (TABLE_ID) references Coretest.TABLEINFO (TABLE_ID);
alter table DoTStest.ATTRIBUTION add constraint ATTRIBUTION_FK02 foreign key (CONTACT_ID) references SRestest.CONTACT (CONTACT_ID);

/* BESTSIMILARITYPAIR */
alter table DoTStest.BESTSIMILARITYPAIR add constraint BESTSIMILARITYPAIR_FK05 foreign key (SOURCE_TABLE_ID) references Coretest.TABLEINFO (TABLE_ID);
alter table DoTStest.BESTSIMILARITYPAIR add constraint BESTSIMILARITYPAIR_FK06 foreign key (PAIRED_SOURCE_TABLE_ID) references Coretest.TABLEINFO (TABLE_ID);
alter table DoTStest.BESTSIMILARITYPAIR add constraint BESTSIMILARITYPAIR_FK07 foreign key (ORTHOLOG_EXPERIMENT_ID) references DoTStest.SEQGROUPEXPERIMENTIMP (SEQ_GROUP_EXPERIMENT_ID);

/* BLATALIGNMENT */
alter table DoTStest.BLATALIGNMENT add constraint BLATALIGNMENT_FK01 foreign key (QUERY_NA_SEQUENCE_ID) references DoTStest.NASEQUENCEIMP (NA_SEQUENCE_ID);
alter table DoTStest.BLATALIGNMENT add constraint BLATALIGNMENT_FK02 foreign key (TARGET_NA_SEQUENCE_ID) references DoTStest.NASEQUENCEIMP (NA_SEQUENCE_ID);
alter table DoTStest.BLATALIGNMENT add constraint BLATALIGNMENT_FK03 foreign key (QUERY_TABLE_ID) references Coretest.TABLEINFO (TABLE_ID);
alter table DoTStest.BLATALIGNMENT add constraint BLATALIGNMENT_FK04 foreign key (QUERY_TAXON_ID) references SRestest.TAXON (TAXON_ID);
alter table DoTStest.BLATALIGNMENT add constraint BLATALIGNMENT_FK05 foreign key (QUERY_EXTERNAL_DB_RELEASE_ID) references SRestest.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_RELEASE_ID);
alter table DoTStest.BLATALIGNMENT add constraint BLATALIGNMENT_FK06 foreign key (TARGET_TABLE_ID) references Coretest.TABLEINFO (TABLE_ID);
alter table DoTStest.BLATALIGNMENT add constraint BLATALIGNMENT_FK07 foreign key (TARGET_TAXON_ID) references SRestest.TAXON (TAXON_ID);
alter table DoTStest.BLATALIGNMENT add constraint BLATALIGNMENT_FK08 foreign key (TARGET_EXTERNAL_DB_RELEASE_ID) references SRestest.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_RELEASE_ID);
alter table DoTStest.BLATALIGNMENT add constraint BLATALIGNMENT_FK09 foreign key (BLAT_ALIGNMENT_QUALITY_ID) references DoTStest.BLATALIGNMENTQUALITY (BLAT_ALIGNMENT_QUALITY_ID);

/* BLATALIGNMENTQUALITY */

/* CLONE */
alter table DoTStest.CLONE add constraint CLONE_FK03 foreign key (LIBRARY_ID) references DoTStest.LIBRARY (LIBRARY_ID);

/* CLONEINSET */
alter table DoTStest.CLONEINSET add constraint CLONEINSET_FK01 foreign key (CLONE_ID) references DoTStest.CLONE (CLONE_ID);
alter table DoTStest.CLONEINSET add constraint CLONEINSET_FK05 foreign key (CLONE_SET_ID) references DoTStest.CLONESET (CLONE_SET_ID);

/* CLONESET */
alter table DoTStest.CLONESET add constraint CLONESET_FK03 foreign key (CONTACT_ID) references SRestest.CONTACT (CONTACT_ID);

/* COMMENTNAME */

/* COMMENTS */
alter table DoTStest.COMMENTS add constraint COMMENTS_FK01 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);

/* COMPLEMENTATION */
alter table DoTStest.COMPLEMENTATION add constraint COMPLEMENTATION_FK01 foreign key (EXTERNAL_DATABASE_RELEASE_ID) references SRestest.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_RELEASE_ID);
alter table DoTStest.COMPLEMENTATION add constraint COMPLEMENTATION_FK02 foreign key (TAXON_ID) references SRestest.TAXON (TAXON_ID);
alter table DoTStest.COMPLEMENTATION add constraint COMPLEMENTATION_FK03 foreign key (TABLE_ID) references Coretest.TABLEINFO (TABLE_ID);
alter table DoTStest.COMPLEMENTATION add constraint COMPLEMENTATION_FK04 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);

/* COMPLEX */
alter table DoTStest.COMPLEX add constraint COMPLEX_FK01 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);
alter table DoTStest.COMPLEX add constraint COMPLEX_FK02 foreign key (COMPLEX_TYPE_ID) references DoTStest.COMPLEXTYPE (COMPLEX_TYPE_ID);
alter table DoTStest.COMPLEX add constraint COMPLEX_FK03 foreign key (EXTERNAL_DATABASE_RELEASE_ID) references SRestest.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_RELEASE_ID);

/* COMPLEXANATOMY */
alter table DoTStest.COMPLEXANATOMY add constraint COMPLEXANATOMY_FK01 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);
alter table DoTStest.COMPLEXANATOMY add constraint COMPLEXANATOMY_FK02 foreign key (ANATOMY_ID) references SRestest.ANATOMY (ANATOMY_ID);
alter table DoTStest.COMPLEXANATOMY add constraint COMPLEXANATOMY_FK03 foreign key (COMPLEX_ID) references DoTStest.COMPLEX (COMPLEX_ID);

/* COMPLEXCOMPONENT */
alter table DoTStest.COMPLEXCOMPONENT add constraint COMPLEXCOMPONENT_FK01 foreign key (TABLE_ID) references Coretest.TABLEINFO (TABLE_ID);
alter table DoTStest.COMPLEXCOMPONENT add constraint COMPLEXCOMPONENT_FK02 foreign key (COMPLEX_ID) references DoTStest.COMPLEX (COMPLEX_ID);

/* COMPLEXTYPE */

/* CONSISTENTALIGNMENT */
alter table DoTStest.CONSISTENTALIGNMENT add constraint CONSISTENTALIGNMENT_FK04 foreign key (SIMILARITY_ID) references DoTStest.SIMILARITY (SIMILARITY_ID);
alter table DoTStest.CONSISTENTALIGNMENT add constraint CONSISTENTALIGNMENT_FK05 foreign key (GENOMIC_NA_SEQUENCE_ID) references DoTStest.NASEQUENCEIMP (NA_SEQUENCE_ID);
alter table DoTStest.CONSISTENTALIGNMENT add constraint CONSISTENTALIGNMENT_FK06 foreign key (TRANSCRIPT_NA_SEQUENCE_ID) references DoTStest.NASEQUENCEIMP (NA_SEQUENCE_ID);

/* DBREFNAFEATURE */
alter table DoTStest.DBREFNAFEATURE add constraint DBREFNAFEATURE_FK04 foreign key (DB_REF_ID) references SRestest.DBREF (DB_REF_ID);
alter table DoTStest.DBREFNAFEATURE add constraint DBREFNAFEATURE_FK05 foreign key (NA_FEATURE_ID) references DoTStest.NAFEATUREIMP (NA_FEATURE_ID);

/* DBREFNASEQUENCE */
alter table DoTStest.DBREFNASEQUENCE add constraint DBREFNASEQUENCE_FK04 foreign key (DB_REF_ID) references SRestest.DBREF (DB_REF_ID);
alter table DoTStest.DBREFNASEQUENCE add constraint DBREFNASEQUENCE_FK05 foreign key (NA_SEQUENCE_ID) references DoTStest.NASEQUENCEIMP (NA_SEQUENCE_ID);

/* DBREFPFAMENTRY */
alter table DoTStest.DBREFPFAMENTRY add constraint DBREFPFAMENTRY_FK01 foreign key (DB_REF_ID) references SRestest.DBREF (DB_REF_ID);
alter table DoTStest.DBREFPFAMENTRY add constraint DBREFPFAMENTRY_FK05 foreign key (PFAM_ENTRY_ID) references DoTStest.PFAMENTRY (PFAM_ENTRY_ID);

/* EFFECTORACTIONTYPE */
alter table DoTStest.EFFECTORACTIONTYPE add constraint EFFECTORACTIONTYPE_FK01 foreign key (EXTERNAL_DATABASE_RELEASE_ID) references SRestest.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_RELEASE_ID);

/* ENDSEQUENCEPAIRMAP */
alter table DoTStest.ENDSEQUENCEPAIRMAP add constraint ENDSEQUENCEPAIRMAP_FK01 foreign key (EXTERNAL_DATABASE_RELEASE_ID) references SRestest.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_RELEASE_ID);
alter table DoTStest.ENDSEQUENCEPAIRMAP add constraint ENDSEQUENCEPAIRMAP_FK02 foreign key (TAXON_ID) references SRestest.TAXON (TAXON_ID);
alter table DoTStest.ENDSEQUENCEPAIRMAP add constraint ENDSEQUENCEPAIRMAP_FK03 foreign key (NA_SEQUENCE_ID_1) references DoTStest.NASEQUENCEIMP (NA_SEQUENCE_ID);
alter table DoTStest.ENDSEQUENCEPAIRMAP add constraint ENDSEQUENCEPAIRMAP_FK04 foreign key (NA_SEQUENCE_ID_2) references DoTStest.NASEQUENCEIMP (NA_SEQUENCE_ID);

/* EPCR */
alter table DoTStest.EPCR add constraint EPCR_FK01 foreign key (MAP_TABLE_ID) references Coretest.TABLEINFO (TABLE_ID);
alter table DoTStest.EPCR add constraint EPCR_FK02 foreign key (NA_SEQUENCE_ID) references DoTStest.NASEQUENCEIMP (NA_SEQUENCE_ID);
alter table DoTStest.EPCR add constraint EPCR_FK03 foreign key (SIMILARITY_ID_1) references DoTStest.SIMILARITY (SIMILARITY_ID);
alter table DoTStest.EPCR add constraint EPCR_FK04 foreign key (SIMILARITY_ID_2) references DoTStest.SIMILARITY (SIMILARITY_ID);

/* EST */
alter table DoTStest.EST add constraint EST_FK01 foreign key (CLONE_ID) references DoTStest.CLONE (CLONE_ID);
alter table DoTStest.EST add constraint EST_FK04 foreign key (CONTACT_ID) references SRestest.CONTACT (CONTACT_ID);
alter table DoTStest.EST add constraint EST_FK06 foreign key (NA_SEQUENCE_ID) references DoTStest.NASEQUENCEIMP (NA_SEQUENCE_ID);
alter table DoTStest.EST add constraint EST_FK08 foreign key (LIBRARY_ID) references DoTStest.LIBRARY (LIBRARY_ID);

/* EVIDENCE */
alter table DoTStest.EVIDENCE add constraint EVIDENCE_FK04 foreign key (FACT_TABLE_ID) references Coretest.TABLEINFO (TABLE_ID);
alter table DoTStest.EVIDENCE add constraint EVIDENCE_FK05 foreign key (TARGET_TABLE_ID) references Coretest.TABLEINFO (TABLE_ID);

/* EXONLOCATION */
alter table DoTStest.EXONLOCATION add constraint EXONLOCATION_FK04 foreign key (NA_SEQUENCE_ID) references DoTStest.NASEQUENCEIMP (NA_SEQUENCE_ID);

/* FAMILY */
alter table DoTStest.FAMILY add constraint FAMILY_FK04 foreign key (PARENT_FAMILY_ID) references DoTStest.FAMILY (FAMILY_ID);

/* FAMILYGENE */
alter table DoTStest.FAMILYGENE add constraint FAMILYGENE_FK03 foreign key (GENE_ID) references DoTStest.GENE (GENE_ID);
alter table DoTStest.FAMILYGENE add constraint FAMILYGENE_FK05 foreign key (FAMILY_ID) references DoTStest.FAMILY (FAMILY_ID);

/* FAMILYPROTEIN */
alter table DoTStest.FAMILYPROTEIN add constraint FAMILYPROTEIN_FK04 foreign key (FAMILY_ID) references DoTStest.FAMILY (FAMILY_ID);
alter table DoTStest.FAMILYPROTEIN add constraint FAMILYPROTEIN_FK05 foreign key (PROTEIN_ID) references DoTStest.PROTEIN (PROTEIN_ID);

/* FEATURENAME */

/* FINGERPRINTCLONE */
alter table DoTStest.FINGERPRINTCLONE add constraint FINGERPRINTCLONE_FK01 foreign key (EXTERNAL_DATABASE_RELEASE_ID) references SRestest.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_RELEASE_ID);

/* FINGERPRINTCLONECONTIG */
alter table DoTStest.FINGERPRINTCLONECONTIG add constraint FINGERPRINTCLONECONTIG_FK01 foreign key (FINGERPRINT_CLONE_ID) references DoTStest.FINGERPRINTCLONE (FINGERPRINT_CLONE_ID);
alter table DoTStest.FINGERPRINTCLONECONTIG add constraint FINGERPRINTCLONECONTIG_FK02 foreign key (FINGERPRINT_CONTIG_ID) references DoTStest.FINGERPRINTCONTIG (FINGERPRINT_CONTIG_ID);

/* FINGERPRINTCLONEMARKER */
alter table DoTStest.FINGERPRINTCLONEMARKER add constraint FINGERPRINTCLONEMARKER_FK01 foreign key (FINGERPRINT_MAP_ID) references DoTStest.FINGERPRINTMAP (FINGERPRINT_MAP_ID);
alter table DoTStest.FINGERPRINTCLONEMARKER add constraint FINGERPRINTCLONEMARKER_FK02 foreign key (FINGERPRINT_CLONE_ID) references DoTStest.FINGERPRINTCLONE (FINGERPRINT_CLONE_ID);
alter table DoTStest.FINGERPRINTCLONEMARKER add constraint FINGERPRINTCLONEMARKER_FK03 foreign key (EXTERNAL_DATABASE_RELEASE_ID) references SRestest.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_RELEASE_ID);

/* FINGERPRINTCONTIG */
alter table DoTStest.FINGERPRINTCONTIG add constraint FINGERPRINTCONTIG_FK01 foreign key (FINGERPRINT_MAP_ID) references DoTStest.FINGERPRINTMAP (FINGERPRINT_MAP_ID);

/* FINGERPRINTMAP */
alter table DoTStest.FINGERPRINTMAP add constraint FINGERPRINTMAP_FK01 foreign key (EXTERNAL_DATABASE_RELEASE_ID) references SRestest.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_RELEASE_ID);

/* GENE */
alter table DoTStest.GENE add constraint GENE_FK04 foreign key (GENE_CATEGORY_ID) references DoTStest.GENECATEGORY (GENE_CATEGORY_ID);
alter table DoTStest.GENE add constraint GENE_FK05 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);

/* GENEALIAS */
alter table DoTStest.GENEALIAS add constraint GENEALIAS_FK05 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);
alter table DoTStest.GENEALIAS add constraint GENEALIAS_FK06 foreign key (GENE_ID) references DoTStest.GENE (GENE_ID);

/* GENECATEGORY */

/* GENECHROMOSOMALLOCATION */
alter table DoTStest.GENECHROMOSOMALLOCATION add constraint GENECHROMOSOMALLOCATION_FK01 foreign key (GENE_ID) references DoTStest.GENE (GENE_ID);

/* GENEFAMILY */

/* GENEFAMILYRELATION */
alter table DoTStest.GENEFAMILYRELATION add constraint GENEFAMILYRELATION_FK02 foreign key (GENE_ID) references DoTStest.GENE (GENE_ID);
alter table DoTStest.GENEFAMILYRELATION add constraint GENEFAMILYRELATION_FK05 foreign key (GENE_FAMILY_ID) references DoTStest.GENEFAMILY (GENE_FAMILY_ID);

/* GENEFEATURESAGETAGLINK */
alter table DoTStest.GENEFEATURESAGETAGLINK add constraint GENEFEATURESAGETAGLINK_FK01 foreign key (GENOMIC_NA_SEQUENCE_ID) references DoTStest.NASEQUENCEIMP (NA_SEQUENCE_ID);
alter table DoTStest.GENEFEATURESAGETAGLINK add constraint GENEFEATURESAGETAGLINK_FK02 foreign key (GENE_NA_FEATURE_ID) references DoTStest.NAFEATUREIMP (NA_FEATURE_ID);
alter table DoTStest.GENEFEATURESAGETAGLINK add constraint GENEFEATURESAGETAGLINK_FK03 foreign key (TAG_NA_FEATURE_ID) references DoTStest.NAFEATUREIMP (NA_FEATURE_ID);

/* GENEFEATURESEQOVERLAP */
alter table DoTStest.GENEFEATURESEQOVERLAP add constraint GENEFEATURESEQOVERLAP_FK01 foreign key (GENE_NA_FEATURE_ID) references DoTStest.NAFEATUREIMP (NA_FEATURE_ID);
alter table DoTStest.GENEFEATURESEQOVERLAP add constraint GENEFEATURESEQOVERLAP_FK02 foreign key (GENOMIC_NA_SEQUENCE_ID) references DoTStest.NASEQUENCEIMP (NA_SEQUENCE_ID);
alter table DoTStest.GENEFEATURESEQOVERLAP add constraint GENEFEATURESEQOVERLAP_FK03 foreign key (SEQ_NA_SEQUENCE_ID) references DoTStest.NASEQUENCEIMP (NA_SEQUENCE_ID);
alter table DoTStest.GENEFEATURESEQOVERLAP add constraint GENEFEATURESEQOVERLAP_FK04 foreign key (END_SEQUENCE_PAIR_MAP_ID) references DoTStest.ENDSEQUENCEPAIRMAP (END_SEQUENCE_PAIR_MAP_ID);
alter table DoTStest.GENEFEATURESEQOVERLAP add constraint GENEFEATURESEQOVERLAP_FK05 foreign key (EPCR_ID) references DoTStest.EPCR (EPCR_ID);
alter table DoTStest.GENEFEATURESEQOVERLAP add constraint GENEFEATURESEQOVERLAP_FK06 foreign key (SIMILARITY_ID) references DoTStest.SIMILARITY (SIMILARITY_ID);
alter table DoTStest.GENEFEATURESEQOVERLAP add constraint GENEFEATURESEQOVERLAP_FK07 foreign key (BLAT_ALIGNMENT_ID) references DoTStest.BLATALIGNMENT (BLAT_ALIGNMENT_ID);

/* GENEINSTANCE */
alter table DoTStest.GENEINSTANCE add constraint GENEINSTANCE_FK05 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);
alter table DoTStest.GENEINSTANCE add constraint GENEINSTANCE_FK06 foreign key (GENE_ID) references DoTStest.GENE (GENE_ID);
alter table DoTStest.GENEINSTANCE add constraint GENEINSTANCE_FK07 foreign key (NA_FEATURE_ID) references DoTStest.NAFEATUREIMP (NA_FEATURE_ID);
alter table DoTStest.GENEINSTANCE add constraint GENEINSTANCE_FK08 foreign key (GENE_INSTANCE_CATEGORY_ID) references DoTStest.GENEINSTANCECATEGORY (GENE_INSTANCE_CATEGORY_ID);

/* GENEINSTANCECATEGORY */

/* GENESUPERFAMILY */

/* GENESUPERFAMILYRELATION */
alter table DoTStest.GENESUPERFAMILYRELATION add constraint GENESUPERFAMILYRELATION_FK04 foreign key (GENE_FAMILY_ID) references DoTStest.GENEFAMILY (GENE_FAMILY_ID);
alter table DoTStest.GENESUPERFAMILYRELATION add constraint GENESUPERFAMILYRELATION_FK06 foreign key (GENE_SUPER_FAMILY_ID) references DoTStest.GENESUPERFAMILY (GENE_SUPER_FAMILY_ID);

/* GENESYNONYM */
alter table DoTStest.GENESYNONYM add constraint GENESYNONYM_FK03 foreign key (GENE_ID) references DoTStest.GENE (GENE_ID);
alter table DoTStest.GENESYNONYM add constraint GENESYNONYM_FK04 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);

/* GENETRAPASSEMBLY */
alter table DoTStest.GENETRAPASSEMBLY add constraint GENETRAPASSEMBLY_FK01 foreign key (TAG_NA_SEQUENCE_ID) references DoTStest.NASEQUENCEIMP (NA_SEQUENCE_ID);
alter table DoTStest.GENETRAPASSEMBLY add constraint GENETRAPASSEMBLY_FK02 foreign key (ASSEMBLY_NA_SEQUENCE_ID) references DoTStest.NASEQUENCEIMP (NA_SEQUENCE_ID);

/* GOASSOCIATION */
alter table DoTStest.GOASSOCIATION add constraint GOASSOCIATION_FK03 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);
alter table DoTStest.GOASSOCIATION add unique (TABLE_ID,ROW_ID,GO_TERM_ID);
alter table DoTStest.GOASSOCIATION add constraint GOSSOCIATION_FK01 foreign key (TABLE_ID) references Coretest.TABLEINFO (TABLE_ID);
alter table DoTStest.GOASSOCIATION add constraint GOSSOCIATION_FK02 foreign key (GO_TERM_ID) references SRestest.GOTERM (GO_TERM_ID);

/* GOASSOCIATIONINSTANCE */
alter table DoTStest.GOASSOCIATIONINSTANCE add constraint GOASSOCIATIONINSTANCE_FK01 foreign key (GO_ASSOCIATION_ID) references DoTStest.GOASSOCIATION (GO_ASSOCIATION_ID);
alter table DoTStest.GOASSOCIATIONINSTANCE add constraint GOASSOCIATIONINSTANCE_FK02 foreign key (GO_ASSOC_INST_LOE_ID) references DoTStest.GOASSOCIATIONINSTANCELOE (GO_ASSOC_INST_LOE_ID);
alter table DoTStest.GOASSOCIATIONINSTANCE add constraint GOASSOCIATIONINSTANCE_FK03 foreign key (EXTERNAL_DATABASE_RELEASE_ID) references SRestest.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_RELEASE_ID);
alter table DoTStest.GOASSOCIATIONINSTANCE add constraint GOASSOCIATIONINSTANCE_FK04 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);

/* GOASSOCIATIONINSTANCELOE */

/* GOASSOCINSTEVIDCODE */
alter table DoTStest.GOASSOCINSTEVIDCODE add constraint GOASSOCINSTEVIDCODE_FK01 foreign key (GO_EVIDENCE_CODE_ID) references SRestest.GOEVIDENCECODE (GO_EVIDENCE_CODE_ID);
alter table DoTStest.GOASSOCINSTEVIDCODE add constraint GOASSOCINSTEVIDCODE_FK02 foreign key (GO_ASSOCIATION_INSTANCE_ID) references DoTStest.GOASSOCIATIONINSTANCE (GO_ASSOCIATION_INSTANCE_ID);
alter table DoTStest.GOASSOCINSTEVIDCODE add constraint GOASSOCINSTEVIDCODE_FK03 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);

/* INDEXWORD */

/* INDEXWORDLINK */
alter table DoTStest.INDEXWORDLINK add constraint INDEXWORDLINK_FK04 foreign key (TARGET_TABLE_ID) references Coretest.TABLEINFO (TABLE_ID);
alter table DoTStest.INDEXWORDLINK add constraint INDEXWORDLINK_FK05 foreign key (INDEX_WORD_ID) references DoTStest.INDEXWORD (INDEX_WORD_ID);

/* INDEXWORDSIMLINK */
alter table DoTStest.INDEXWORDSIMLINK add constraint INDEXWORDSIMLINK_FK04 foreign key (TARGET_TABLE_ID) references Coretest.TABLEINFO (TABLE_ID);
alter table DoTStest.INDEXWORDSIMLINK add constraint INDEXWORDSIMLINK_FK05 foreign key (INDEX_WORD_ID) references DoTStest.INDEXWORD (INDEX_WORD_ID);
alter table DoTStest.INDEXWORDSIMLINK add constraint INDEXWORDSIMLINK_FK06 foreign key (SIMILARITY_TABLE_ID) references Coretest.TABLEINFO (TABLE_ID);
alter table DoTStest.INDEXWORDSIMLINK add constraint INDEXWORDSIMLINK_FK07 foreign key (BEST_SIMILARITY_ID) references DoTStest.SIMILARITY (SIMILARITY_ID);

/* INTERACTION */
alter table DoTStest.INTERACTION add constraint INTERACTION_FK01 foreign key (INTERACTION_TYPE_ID) references DoTStest.INTERACTIONTYPE (INTERACTION_TYPE_ID);
alter table DoTStest.INTERACTION add constraint INTERACTION_FK02 foreign key (EFFECTOR_ACTION_TYPE_ID) references DoTStest.EFFECTORACTIONTYPE (EFFECTOR_ACTION_TYPE_ID);
alter table DoTStest.INTERACTION add constraint INTERACTION_FK03 foreign key (EFFECTOR_ROW_SET_ID) references DoTStest.ROWSET (ROW_SET_ID);
alter table DoTStest.INTERACTION add constraint INTERACTION_FK04 foreign key (TARGET_ROW_SET_ID) references DoTStest.ROWSET (ROW_SET_ID);
alter table DoTStest.INTERACTION add constraint INTERACTION_FK05 foreign key (EXTERNAL_DATABASE_RELEASE_ID) references SRestest.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_RELEASE_ID);
alter table DoTStest.INTERACTION add constraint INTERACTION_FK06 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);

/* INTERACTIONINTERACTIONLOE */
alter table DoTStest.INTERACTIONINTERACTIONLOE add constraint INTERACTIONINTERACTIONLOE_FK01 foreign key (INTERACTION_ID) references DoTStest.INTERACTION (INTERACTION_ID);
alter table DoTStest.INTERACTIONINTERACTIONLOE add constraint INTERACTIONINTERACTIONLOE_FK02 foreign key (INTERACTION_LOE_ID) references DoTStest.INTERACTIONLOE (INTERACTION_LOE_ID);

/* INTERACTIONLOE */

/* INTERACTIONTYPE */
alter table DoTStest.INTERACTIONTYPE add constraint INTERACTIONTYPE_FK01 foreign key (EXTERNAL_DATABASE_RELEASE_ID) references SRestest.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_RELEASE_ID);

/* ISEXPRESSED */
alter table DoTStest.ISEXPRESSED add constraint ISEXPRESSED_FK05 foreign key (ANATOMY_ID) references SRestest.ANATOMY (ANATOMY_ID);
alter table DoTStest.ISEXPRESSED add constraint ISEXPRESSED_FK06 foreign key (TABLE_ID) references Coretest.TABLEINFO (TABLE_ID);

/* KEYWORD */
alter table DoTStest.KEYWORD add constraint KEYWORD_FK foreign key (PREFERRED_KEYWORD_ID) references DoTStest.KEYWORD (KEYWORD_ID);

/* LIBRARY */
alter table DoTStest.LIBRARY add constraint LIBRARY_FK01 foreign key (TAXON_ID) references SRestest.TAXON (TAXON_ID);
alter table DoTStest.LIBRARY add constraint LIBRARY_FK03 foreign key (ANATOMY_ID) references SRestest.ANATOMY (ANATOMY_ID);

/* MERGESPLIT */
alter table DoTStest.MERGESPLIT add constraint MERGESPLIT_FK04 foreign key (TABLE_ID) references Coretest.TABLEINFO (TABLE_ID);

/* MOTIF */
alter table DoTStest.MOTIF add constraint MOTIF_FK04 foreign key (EXTERNAL_DATABASE_RELEASE_ID) references SRestest.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_RELEASE_ID);

/* NACOMMENT */
alter table DoTStest.NACOMMENT add constraint NACOMMENT_FK01 foreign key (NA_SEQUENCE_ID) references DoTStest.NASEQUENCEIMP (NA_SEQUENCE_ID);

/* NAENTRY */
alter table DoTStest.NAENTRY add constraint NAENTRY_FK04 foreign key (NA_SEQUENCE_ID) references DoTStest.NASEQUENCEIMP (NA_SEQUENCE_ID);

/* NAFEATRELATIONSHIPTYPE */

/* NAFEATURECOMMENT */
alter table DoTStest.NAFEATURECOMMENT add constraint NAFEATURECOMMENT_FK01 foreign key (NA_FEATURE_ID) references DoTStest.NAFEATUREIMP (NA_FEATURE_ID);

/* NAFEATUREIMP */
alter table DoTStest.NAFEATUREIMP add constraint NAFEATUREIMP_FK03 foreign key (SEQUENCE_ONTOLOGY_ID) references SRestest.SEQUENCEONTOLOGY (SEQUENCE_ONTOLOGY_ID);
alter table DoTStest.NAFEATUREIMP add constraint NAFEATUREIMP_FK04 foreign key (PARENT_ID) references DoTStest.NAFEATUREIMP (NA_FEATURE_ID);
alter table DoTStest.NAFEATUREIMP add constraint NAFEATUREIMP_FK05 foreign key (PREDICTION_ALGORITHM_ID) references Coretest.ALGORITHM (ALGORITHM_ID);
alter table DoTStest.NAFEATUREIMP add constraint NAFEATUREIMP_FK06 foreign key (NA_SEQUENCE_ID) references DoTStest.NASEQUENCEIMP (NA_SEQUENCE_ID);
alter table DoTStest.NAFEATUREIMP add constraint NAFEATUREIMP_FK07 foreign key (EXTERNAL_DATABASE_RELEASE_ID) references SRestest.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_RELEASE_ID);
alter table DoTStest.NAFEATUREIMP add constraint NAFEATUREIMP_FK08 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);

/* NAFEATURENAGENE */
alter table DoTStest.NAFEATURENAGENE add constraint NAFEATURENAGENE_FK04 foreign key (NA_GENE_ID) references DoTStest.NAGENE (NA_GENE_ID);
alter table DoTStest.NAFEATURENAGENE add constraint NAFEATURENAGENE_FK05 foreign key (NA_FEATURE_ID) references DoTStest.NAFEATUREIMP (NA_FEATURE_ID);

/* NAFEATURENAPROTEIN */
alter table DoTStest.NAFEATURENAPROTEIN add constraint NAFEATURENAPROTEIN_FK04 foreign key (NA_PROTEIN_ID) references DoTStest.NAPROTEIN (NA_PROTEIN_ID);
alter table DoTStest.NAFEATURENAPROTEIN add constraint NAFEATURENAPROTEIN_FK05 foreign key (NA_FEATURE_ID) references DoTStest.NAFEATUREIMP (NA_FEATURE_ID);

/* NAFEATURENAPT */
alter table DoTStest.NAFEATURENAPT add constraint NAFEATURENAPT_FK05 foreign key (NA_FEATURE_ID) references DoTStest.NAFEATUREIMP (NA_FEATURE_ID);
alter table DoTStest.NAFEATURENAPT add constraint NAFEATURENAPT_FK06 foreign key (NA_PRIMARY_TRANSCRIPT_ID) references DoTStest.NAPRIMARYTRANSCRIPT (NA_PRIMARY_TRANSCRIPT_ID);

/* NAFEATURERELATIONSHIP */
alter table DoTStest.NAFEATURERELATIONSHIP add constraint NAFEATURERELATIONSHIP_FK05 foreign key (NA_FEAT_RELATIONSHIP_TYPE_ID) references DoTStest.NAFEATRELATIONSHIPTYPE (NA_FEAT_RELATIONSHIP_TYPE_ID);
alter table DoTStest.NAFEATURERELATIONSHIP add constraint NAFEATURERELATIONSHIP_FK06 foreign key (PARENT_NA_FEATURE_ID) references DoTStest.NAFEATUREIMP (NA_FEATURE_ID);
alter table DoTStest.NAFEATURERELATIONSHIP add constraint NAFEATURERELATIONSHIP_FK07 foreign key (CHILD_NA_FEATURE_ID) references DoTStest.NAFEATUREIMP (NA_FEATURE_ID);

/* NAGENE */

/* NALOCATION */
alter table DoTStest.NALOCATION add constraint NALOCATION_FK04 foreign key (NA_FEATURE_ID) references DoTStest.NAFEATUREIMP (NA_FEATURE_ID);

/* NAPRIMARYTRANSCRIPT */
alter table DoTStest.NAPRIMARYTRANSCRIPT add constraint NAPRIMARYTRANSCRIPT_FK04 foreign key (NA_GENE_ID) references DoTStest.NAGENE (NA_GENE_ID);

/* NAPROTEIN */
alter table DoTStest.NAPROTEIN add constraint NAPROTEIN_FK04 foreign key (NA_PRIMARY_TRANSCRIPT_ID) references DoTStest.NAPRIMARYTRANSCRIPT (NA_PRIMARY_TRANSCRIPT_ID);

/* NASEQCYTOLOCATION */
alter table DoTStest.NASEQCYTOLOCATION add constraint NASEQCYTOLOCATION foreign key (NA_SEQUENCE_ID) references DoTStest.NASEQUENCEIMP (NA_SEQUENCE_ID);

/* NASEQUENCEIMP */
alter table DoTStest.NASEQUENCEIMP add constraint NASEQUENCEIMP_FK01 foreign key (SEQUENCE_TYPE_ID) references DoTStest.SEQUENCETYPE (SEQUENCE_TYPE_ID);
alter table DoTStest.NASEQUENCEIMP add constraint NASEQUENCEIMP_FK02 foreign key (TAXON_ID) references SRestest.TAXON (TAXON_ID);
alter table DoTStest.NASEQUENCEIMP add constraint NASEQUENCEIMP_FK03 foreign key (EXTERNAL_DATABASE_RELEASE_ID) references SRestest.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_RELEASE_ID);
alter table DoTStest.NASEQUENCEIMP add constraint NASEQUENCEIMP_FK05 foreign key (SEQUENCE_PIECE_ID) references DoTStest.SEQUENCEPIECE (SEQUENCE_PIECE_ID);
alter table DoTStest.NASEQUENCEIMP add constraint NASEQUENCEIMP_FK06 foreign key (SEQUENCING_CENTER_CONTACT_ID) references SRestest.CONTACT (CONTACT_ID);

/* NASEQUENCEKEYWORD */
alter table DoTStest.NASEQUENCEKEYWORD add constraint NASEQUENCEKEYWORD_FK04 foreign key (KEYWORD_ID) references DoTStest.KEYWORD (KEYWORD_ID);
alter table DoTStest.NASEQUENCEKEYWORD add constraint NASEQUENCEKEYWORD_FK05 foreign key (NA_SEQUENCE_ID) references DoTStest.NASEQUENCEIMP (NA_SEQUENCE_ID);

/* NASEQUENCEORGANELLE */
alter table DoTStest.NASEQUENCEORGANELLE add constraint NASEQUENCEORGANELLE_FK04 foreign key (ORGANELLE_ID) references DoTStest.ORGANELLE (ORGANELLE_ID);
alter table DoTStest.NASEQUENCEORGANELLE add constraint NASEQUENCEORGANELLE_FK05 foreign key (NA_SEQUENCE_ID) references DoTStest.NASEQUENCEIMP (NA_SEQUENCE_ID);

/* NASEQUENCEREF */
alter table DoTStest.NASEQUENCEREF add constraint NASEQUENCEREF_FK01 foreign key (REFERENCE_ID) references SRestest.REFERENCE (REFERENCE_ID);
alter table DoTStest.NASEQUENCEREF add constraint NASEQUENCEREF_FK05 foreign key (NA_SEQUENCE_ID) references DoTStest.NASEQUENCEIMP (NA_SEQUENCE_ID);

/* NRDBENTRY */
alter table DoTStest.NRDBENTRY add constraint NRDBENTRY_FK01 foreign key (AA_SEQUENCE_ID) references DoTStest.AASEQUENCEIMP (AA_SEQUENCE_ID);
alter table DoTStest.NRDBENTRY add constraint NRDBENTRY_FK02 foreign key (EXTERNAL_DATABASE_RELEASE_ID) references SRestest.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_RELEASE_ID);
alter table DoTStest.NRDBENTRY add constraint NRDBENTRY_FK03 foreign key (TAXON_ID) references SRestest.TAXON (TAXON_ID);

/* OPTICALMAP */
alter table DoTStest.OPTICALMAP add constraint OPTICALMAP_FK01 foreign key (EXTERNAL_DATABASE_RELEASE_ID) references SRestest.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_RELEASE_ID);
alter table DoTStest.OPTICALMAP add constraint OPTICALMAP_FK02 foreign key (TAXON_ID) references SRestest.TAXON (TAXON_ID);

/* OPTICALMAPALIGNMENT */
alter table DoTStest.OPTICALMAPALIGNMENT add constraint OPTICALMAPALIGNMENT_FK01 foreign key (OPTICAL_MAP_ID) references DoTStest.OPTICALMAP (OPTICAL_MAP_ID);
alter table DoTStest.OPTICALMAPALIGNMENT add constraint OPTICALMAPALIGNMENT_FK02 foreign key (NA_SEQUENCE_ID) references DoTStest.NASEQUENCEIMP (NA_SEQUENCE_ID);
alter table DoTStest.OPTICALMAPALIGNMENT add constraint OPTICALMAPALIGNMENT_FK03 foreign key (ALGORITHM_ID) references Coretest.ALGORITHM (ALGORITHM_ID);

/* OPTICALMAPALIGNMENTSPAN */
alter table DoTStest.OPTICALMAPALIGNMENTSPAN add constraint OPTICALMAPALIGNMENTSPAN_FK01 foreign key (OPTICAL_MAP_ALIGNMENT_ID) references DoTStest.OPTICALMAPALIGNMENT (OPTICAL_MAP_ALIGNMENT_ID);
alter table DoTStest.OPTICALMAPALIGNMENTSPAN add constraint OPTICALMAPALIGNMENTSPAN_FK02 foreign key (OPTICAL_MAP_FRAGMENT_ID) references DoTStest.OPTICALMAPFRAGMENT (OPTICAL_MAP_FRAGMENT_ID);
alter table DoTStest.OPTICALMAPALIGNMENTSPAN add constraint OPTICALMAPALIGNMENTSPAN_FK03 foreign key (NA_FEATURE_ID) references DoTStest.NAFEATUREIMP (NA_FEATURE_ID);

/* OPTICALMAPFRAGMENT */
alter table DoTStest.OPTICALMAPFRAGMENT add constraint OPTICALMAPFRAGMENT_FK01 foreign key (OPTICAL_MAP_ID) references DoTStest.OPTICALMAP (OPTICAL_MAP_ID);

/* ORGANELLE */

/* PATHWAY */
alter table DoTStest.PATHWAY add constraint PATHWAY_FK04 foreign key (EXTERNAL_DATABASE_RELEASE_ID) references SRestest.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_RELEASE_ID);

/* PATHWAYINTERACTION */
alter table DoTStest.PATHWAYINTERACTION add constraint PATHWAYINTERACTION_FK04 foreign key (PATHWAY_ID) references DoTStest.PATHWAY (PATHWAY_ID);
alter table DoTStest.PATHWAYINTERACTION add constraint PATHWAYINTERACTION_FK06 foreign key (INTERACTION_ID) references DoTStest.INTERACTION (INTERACTION_ID);

/* PFAMENTRY */

/* PLASMOMAP */
alter table DoTStest.PLASMOMAP add constraint PLASMOMAP_FK01 foreign key (EXTERNAL_DATABASE_RELEASE_ID) references SRestest.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_RELEASE_ID);
alter table DoTStest.PLASMOMAP add constraint PLASMOMAP_FK02 foreign key (TAXON_ID) references SRestest.TAXON (TAXON_ID);

/* PROJECTLINK */
alter table DoTStest.PROJECTLINK add constraint PROJECTLINK_FK04 foreign key (TABLE_ID) references Coretest.TABLEINFO (TABLE_ID);
alter table DoTStest.PROJECTLINK add constraint PROJECTLINK_FK05 foreign key (PROJECT_ID) references Coretest.PROJECTINFO (PROJECT_ID);

/* PROTEIN */
alter table DoTStest.PROTEIN add constraint PROTEIN_FK01 foreign key (RNA_ID) references DoTStest.RNA (RNA_ID);
alter table DoTStest.PROTEIN add constraint PROTEIN_FK06 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);

/* PROTEINCATEGORY */

/* PROTEININSTANCE */
alter table DoTStest.PROTEININSTANCE add constraint PROTEININSTANCE_FK01 foreign key (PROTEIN_INSTANCE_CATEGORY_ID) references DoTStest.PROTEININSTANCECATEGORY (PROTEIN_INSTANCE_CATEGORY_ID);
alter table DoTStest.PROTEININSTANCE add constraint PROTEININSTANCE_FK02 foreign key (PROTEIN_ID) references DoTStest.PROTEIN (PROTEIN_ID);
alter table DoTStest.PROTEININSTANCE add constraint PROTEININSTANCE_FK03 foreign key (AA_FEATURE_ID) references DoTStest.AAFEATUREIMP (AA_FEATURE_ID);
alter table DoTStest.PROTEININSTANCE add constraint PROTEININSTANCE_FK04 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);

/* PROTEININSTANCECATEGORY */

/* PROTEINPROPERTY */
alter table DoTStest.PROTEINPROPERTY add constraint PROTEINPROPERTY_FK01 foreign key (AA_SEQUENCE_ID) references DoTStest.AASEQUENCEIMP (AA_SEQUENCE_ID);
alter table DoTStest.PROTEINPROPERTY add constraint PROTEINPROPERTY_FK02 foreign key (PROTEIN_PROPERTY_TYPE_ID) references DoTStest.PROTEINPROPERTYTYPE (PROTEIN_PROPERTY_TYPE_ID);
alter table DoTStest.PROTEINPROPERTY add constraint PROTEINPROPERTY_FK03 foreign key (PREDICTION_ALGORITHM_ID) references Coretest.ALGORITHM (ALGORITHM_ID);
alter table DoTStest.PROTEINPROPERTY add constraint PROTEINPROPERTY_FK04 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);
alter table DoTStest.PROTEINPROPERTY add constraint PROTEINPROPERTY_FK05 foreign key (EXTERNAL_DATABASE_RELEASE_ID) references SRestest.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_RELEASE_ID);

/* PROTEINPROPERTYTYPE */

/* PROTEINPROTEINCATEGORY */
alter table DoTStest.PROTEINPROTEINCATEGORY add constraint PROTEINPROTEINCATEGORY_FK01 foreign key (PROTEIN_ID) references DoTStest.PROTEIN (PROTEIN_ID);
alter table DoTStest.PROTEINPROTEINCATEGORY add constraint PROTEINPROTEINCATEGORY_FK02 foreign key (PROTEIN_CATEGORY_ID) references DoTStest.PROTEINCATEGORY (PROTEIN_CATEGORY_ID);

/* PROTEINSYNONYM */
alter table DoTStest.PROTEINSYNONYM add constraint PROTEINSYNONYM_FK04 foreign key (PROTEIN_ID) references DoTStest.PROTEIN (PROTEIN_ID);
alter table DoTStest.PROTEINSYNONYM add constraint PROTEINSYNONYM_FK05 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);

/* REPEATTYPE */
alter table DoTStest.REPEATTYPE add constraint REPEATTYPE_FK04 foreign key (PARENT_ID) references DoTStest.REPEATTYPE (REPEAT_TYPE_ID);
alter table DoTStest.REPEATTYPE add constraint REPEATTYPE_FK05 foreign key (EXTERNAL_DATABASE_RELEASE_ID) references SRestest.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_RELEASE_ID);
alter table DoTStest.REPEATTYPE add constraint REPEATTYPE_FK06 foreign key (EXEMPLAR_NA_SEQUENCE_ID) references DoTStest.NASEQUENCEIMP (NA_SEQUENCE_ID);

/* RHMAP */
alter table DoTStest.RHMAP add constraint RHMAP_FK foreign key (TAXON_ID) references SRestest.TAXON (TAXON_ID);
alter table DoTStest.RHMAP add constraint RHMAP_FK05 foreign key (EXTERNAL_DATABASE_RELEASE_ID) references SRestest.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_RELEASE_ID);

/* RHMAPMARKER */
alter table DoTStest.RHMAPMARKER add constraint RHMAPMARKER_FK04 foreign key (RH_MARKER_ID) references DoTStest.RHMARKER (RH_MARKER_ID);
alter table DoTStest.RHMAPMARKER add constraint RHMAPMARKER_FK05 foreign key (RH_MAP_ID) references DoTStest.RHMAP (RH_MAP_ID);

/* RHMARKER */
alter table DoTStest.RHMARKER add constraint RHMARKER_FK04 foreign key (TAXON_ID) references SRestest.TAXON (TAXON_ID);
alter table DoTStest.RHMARKER add constraint RHMARKER_FK05 foreign key (EXTERNAL_DATABASE_RELEASE_ID) references SRestest.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_RELEASE_ID);

/* RNA */
alter table DoTStest.RNA add constraint RNA_FK04 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);
alter table DoTStest.RNA add constraint RNA_FK05 foreign key (GENE_ID) references DoTStest.GENE (GENE_ID);

/* RNAANATOMY */
alter table DoTStest.RNAANATOMY add constraint RNAANATOMY_FK04 foreign key (ANATOMY_ID) references SRestest.ANATOMY (ANATOMY_ID);
alter table DoTStest.RNAANATOMY add constraint RNAANATOMY_FK05 foreign key (RNA_ID) references DoTStest.RNA (RNA_ID);

/* RNAANATOMYLOE */
alter table DoTStest.RNAANATOMYLOE add constraint RNAANATOMYLOE_FK04 foreign key (ANATOMY_LOE_ID) references DoTStest.ANATOMYLOE (ANATOMY_LOE_ID);
alter table DoTStest.RNAANATOMYLOE add constraint RNAANATOMYLOE_FK05 foreign key (RNA_ANATOMY_ID) references DoTStest.RNAANATOMY (RNA_ANATOMY_ID);

/* RNACATEGORY */

/* RNAFEATUREEXON */
alter table DoTStest.RNAFEATUREEXON add constraint RNAFEATUREEXON_FK01 foreign key (RNA_FEATURE_ID) references DoTStest.NAFEATUREIMP (NA_FEATURE_ID);
alter table DoTStest.RNAFEATUREEXON add constraint RNAFEATUREEXON_FK02 foreign key (EXON_FEATURE_ID) references DoTStest.NAFEATUREIMP (NA_FEATURE_ID);

/* RNAICONSTRUCT */
alter table DoTStest.RNAICONSTRUCT add constraint RNAICONSTRUCT_FK01 foreign key (RNA_ID) references DoTStest.RNA (RNA_ID);
alter table DoTStest.RNAICONSTRUCT add constraint RNAICONSTRUCT_FK02 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);

/* RNAINSTANCE */
alter table DoTStest.RNAINSTANCE add constraint RNAINSTANCES_FK02 foreign key (NA_FEATURE_ID) references DoTStest.NAFEATUREIMP (NA_FEATURE_ID);
alter table DoTStest.RNAINSTANCE add constraint RNAINSTANCE_FK01 foreign key (RNA_ID) references DoTStest.RNA (RNA_ID);
alter table DoTStest.RNAINSTANCE add constraint RNAINSTANCE_FK03 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);
alter table DoTStest.RNAINSTANCE add constraint RNAINSTANCE_FK04 foreign key (RNA_INSTANCE_CATEGORY_ID) references DoTStest.RNAINSTANCECATEGORY (RNA_INSTANCE_CATEGORY_ID);

/* RNAINSTANCECATEGORY */

/* RNAIPHENOTYPE */
alter table DoTStest.RNAIPHENOTYPE add constraint RNAIPHENOTYPE_FK01 foreign key (RNAI_CONSTRUCT_ID) references DoTStest.RNAICONSTRUCT (RNAI_CONSTRUCT_ID);
alter table DoTStest.RNAIPHENOTYPE add constraint RNAIPHENOTYPE_FK02 foreign key (PHENOTYPE_ID) references SRestest.PHENOTYPE (PHENOTYPE_ID);
alter table DoTStest.RNAIPHENOTYPE add constraint RNAIPHENOTYPE_FK03 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);

/* RNARNACATEGORY */
alter table DoTStest.RNARNACATEGORY add constraint RNARNACATEGORY_FK05 foreign key (RNA_CATEGORY_ID) references DoTStest.RNACATEGORY (RNA_CATEGORY_ID);
alter table DoTStest.RNARNACATEGORY add constraint RNARNACATEGORY_FK06 foreign key (RNA_ID) references DoTStest.RNA (RNA_ID);

/* ROWSET */

/* ROWSETMEMBER */
alter table DoTStest.ROWSETMEMBER add constraint ROWSETMEMBER_FK01 foreign key (ROW_SET_ID) references DoTStest.ROWSET (ROW_SET_ID);
alter table DoTStest.ROWSETMEMBER add constraint ROWSETMEMBER_FK02 foreign key (TABLE_ID) references Coretest.TABLEINFO (TABLE_ID);

/* SECONDARYACCS */
alter table DoTStest.SECONDARYACCS add constraint SECONDARYACCS_FK04 foreign key (AA_ENTRY_ID) references DoTStest.AAENTRY (AA_ENTRY_ID);
alter table DoTStest.SECONDARYACCS add constraint SECONDARYACCS_FK05 foreign key (NA_ENTRY_ID) references DoTStest.NAENTRY (NA_ENTRY_ID);
alter table DoTStest.SECONDARYACCS add constraint SECONDARYACCS_FK06 foreign key (EXTERNAL_DATABASE_RELEASE_ID) references SRestest.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_RELEASE_ID);

/* SEQGROUPEXPERIMENTIMP */
alter table DoTStest.SEQGROUPEXPERIMENTIMP add constraint SEQGROUPEXPERIMENTIMP_FK05 foreign key (ALGORITHM_ID) references Coretest.ALGORITHM (ALGORITHM_ID);

/* SEQUENCEFAMILY */
alter table DoTStest.SEQUENCEFAMILY add constraint SEQUENCEFAMILY_FK05 foreign key (SEQUENCE_FAMILY_EXPERIMENT_ID) references DoTStest.SEQUENCEFAMILYEXPERIMENT (SEQUENCE_FAMILY_EXPERIMENT_ID);

/* SEQUENCEFAMILYEXPERIMENT */
alter table DoTStest.SEQUENCEFAMILYEXPERIMENT add constraint SEQUENCEFAMILYEXPERIMENT_FK05 foreign key (ORTHOLOG_EXPERIMENT_ID) references DoTStest.SEQGROUPEXPERIMENTIMP (SEQ_GROUP_EXPERIMENT_ID);
alter table DoTStest.SEQUENCEFAMILYEXPERIMENT add constraint SEQUENCEFAMILYEXPERIMENT_FK06 foreign key (IN_PARALOG_EXPERIMENT_ID) references DoTStest.SEQGROUPEXPERIMENTIMP (SEQ_GROUP_EXPERIMENT_ID);
alter table DoTStest.SEQUENCEFAMILYEXPERIMENT add constraint SEQUENCEFAMILYEXPERIMENT_FK07 foreign key (OUT_PARALOG_EXPERIMENT_ID) references DoTStest.SEQGROUPEXPERIMENTIMP (SEQ_GROUP_EXPERIMENT_ID);

/* SEQUENCEGROUPFAMILY */
alter table DoTStest.SEQUENCEGROUPFAMILY add constraint SEQUENCEGROUPFAMILY_FK05 foreign key (SEQUENCE_FAMILY_ID) references DoTStest.SEQUENCEFAMILY (SEQUENCE_FAMILY_ID);
alter table DoTStest.SEQUENCEGROUPFAMILY add constraint SEQUENCEGROUPFAMILY_FK06 foreign key (SEQUENCE_GROUP_ID) references DoTStest.SEQUENCEGROUPIMP (SEQUENCE_GROUP_ID);

/* SEQUENCEGROUPIMP */
alter table DoTStest.SEQUENCEGROUPIMP add constraint SEQUENCEGROUPIMP_FK05 foreign key (SEQUENCE_GROUP_EXPERIMENT_ID) references DoTStest.SEQGROUPEXPERIMENTIMP (SEQ_GROUP_EXPERIMENT_ID);

/* SEQUENCEPIECE */
alter table DoTStest.SEQUENCEPIECE add constraint SEQUENCEPIECE_FK04 foreign key (PIECE_NA_SEQUENCE_ID) references DoTStest.NASEQUENCEIMP (NA_SEQUENCE_ID);
alter table DoTStest.SEQUENCEPIECE add constraint SEQUENCEPIECE_FK06 foreign key (VIRTUAL_NA_SEQUENCE_ID) references DoTStest.NASEQUENCEIMP (NA_SEQUENCE_ID);

/* SEQUENCESEQUENCEGROUP */
alter table DoTStest.SEQUENCESEQUENCEGROUP add constraint SEQUENCESEQUENCEGROUP_FK05 foreign key (SOURCE_TABLE_ID) references Coretest.TABLEINFO (TABLE_ID);
alter table DoTStest.SEQUENCESEQUENCEGROUP add constraint SEQUENCESEQUENCEGROUP_FK06 foreign key (SEQUENCE_GROUP_ID) references DoTStest.SEQUENCEGROUPIMP (SEQUENCE_GROUP_ID);

/* SEQUENCETYPE */
alter table DoTStest.SEQUENCETYPE add constraint SEQUENCETYPE_FK foreign key (PARENT_SEQUENCE_TYPE_ID) references DoTStest.SEQUENCETYPE (SEQUENCE_TYPE_ID);

/* SIMILARITY */
alter table DoTStest.SIMILARITY add constraint SIMILARITY_FK01 foreign key (ALGORITHM_ID) references Coretest.ALGORITHM (ALGORITHM_ID);
alter table DoTStest.SIMILARITY add constraint SIMILARITY_FK04 foreign key (QUERY_TABLE_ID) references Coretest.TABLEINFO (TABLE_ID);
alter table DoTStest.SIMILARITY add constraint SIMILARITY_FK05 foreign key (SUBJECT_TABLE_ID) references Coretest.TABLEINFO (TABLE_ID);

/* SIMILARITYSPAN */
alter table DoTStest.SIMILARITYSPAN add constraint SIMILARITYSPAN_FK03 foreign key (SIMILARITY_ID) references DoTStest.SIMILARITY (SIMILARITY_ID);

/* TRANSLATEDAAFEATSEG */
alter table DoTStest.TRANSLATEDAAFEATSEG add constraint TRANSLATEDAAFEATSEG_FK01 foreign key (AA_FEATURE_ID) references DoTStest.AAFEATUREIMP (AA_FEATURE_ID);



/* 316 non-primary key constraint(s) */

SPOOL OFF
SET ECHO OFF
DISCONNECT
EXIT
