
/*                                                                                            */
/* dots-sequences.sql                                                                         */
/*                                                                                            */
/* This file was generated automatically by dumpSchema.pl on Tue Dec  9 16:10:24 EST 2003     */
/*                                                                                            */

SET ECHO ON
SPOOL dots-sequences.log

CREATE SEQUENCE @oracle_dots@.AACOMMENT_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.AAENTRY_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.AAFAMILYEXPERIMENT_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.AAFEATUREIMP_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.AAGENESYNONYM_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.AAGENE_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.AALOCATION_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.AAMOTIFGOTERMRULESET_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.AAMOTIFGOTERMRULE_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.AASEQGROUPEXPERIMENTIMP_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.AASEQUENCEDBREF_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.AASEQUENCEENZYMECLASS_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.AASEQUENCEFAMILY_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.AASEQUENCEGROUPFAMILY_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.AASEQUENCEGROUPIMP_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.AASEQUENCEIMP_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.AASEQUENCEKEYWORD_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.AASEQUENCEORGANELLE_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.AASEQUENCEREF_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.AASEQUENCESEQUENCEGROUP_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.AASEQUENCETAXON_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.ALLELECOMPLEMENTATION_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.ALLELEINSTANCE_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.ALLELEPHENOTYPECLASS_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.ALLELEPHENOTYPE_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.ALLELE_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.ANATOMYLIBRARY_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.ANATOMYLOE_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.ASSEMBLYANATOMYPERCENT_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.ASSEMBLYSEQUENCESNP_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.ASSEMBLYSEQUENCE_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.ASSEMBLYSNP_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.ATTRIBUTION_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.BESTSIMILARITYPAIR_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.BLATALIGNMENTQUALITY_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.BLATALIGNMENT_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.CLONEINSET_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.CLONESET_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.CLONE_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.COMMENTNAME_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.COMMENTS_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.COMPLEMENTATION_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.COMPLEXANATOMY_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.COMPLEXCOMPONENT_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.COMPLEXTYPE_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.COMPLEX_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.CONSISTENTALIGNMENT_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.DBREFNAFEATURE_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.DBREFNASEQUENCE_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.DBREFPFAMENTRY_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.EFFECTORACTIONTYPE_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.ENDSEQUENCEPAIRMAP_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.EPCR_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.EST_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.EVIDENCE_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.EXONLOCATION_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.FAMILYGENE_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.FAMILYPROTEIN_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.FAMILY_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.FEATURENAME_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.FINGERPRINTCLONECONTIG_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.FINGERPRINTCLONEMARKER_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.FINGERPRINTCLONE_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.FINGERPRINTCONTIG_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.FINGERPRINTMAP_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.GENEALIAS_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.GENECATEGORY_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.GENECHROMOSOMALLOCATION_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.GENEFAMILYRELATION_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.GENEFAMILY_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.GENEFEATURESAGETAGLINK_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.GENEFEATURESEQOVERLAP_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.GENEINSTANCECATEGORY_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.GENEINSTANCE_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.GENESUPERFAMILYRELATION_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.GENESUPERFAMILY_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.GENESYNONYM_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.GENETRAPASSEMBLY_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.GENE_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.GOASSOCIATIONINSTANCELOE_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.GOASSOCIATIONINSTANCE_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.GOASSOCIATION_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.GOASSOCINSTEVIDCODE_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.INDEXWORDLINK_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.INDEXWORDSIMLINK_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.INDEXWORD_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.INTERACTIONINTERACTIONLOE_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.INTERACTIONLOE_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.INTERACTIONTYPE_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.INTERACTION_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.ISEXPRESSED_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.KEYWORD_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.LIBRARY_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.MERGESPLIT_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.MOTIF_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.NACOMMENT_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.NAENTRY_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.NAFEATRELATIONSHIPTYPE_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.NAFEATURECOMMENT_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.NAFEATUREIMP_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.NAFEATURENAGENE_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.NAFEATURENAPROTEIN_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.NAFEATURENAPT_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.NAFEATURERELATIONSHIP_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.NAGENE_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.NALOCATION_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.NAPRIMARYTRANSCRIPT_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.NAPROTEIN_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.NASEQCYTOLOCATION_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.NASEQUENCEIMP_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.NASEQUENCEKEYWORD_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.NASEQUENCEORGANELLE_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.NASEQUENCEREF_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.NRDBENTRY_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.OPTICALMAPALIGNMENTSPAN_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.OPTICALMAPALIGNMENT_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.OPTICALMAPFRAGMENT_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.OPTICALMAP_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.ORGANELLE_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.PATHWAYINTERACTION_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.PATHWAY_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.PFAMENTRY_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.PLASMOMAP_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.PROJECTLINK_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.PROTEINCATEGORY_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.PROTEININSTANCECATEGORY_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.PROTEININSTANCE_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.PROTEINPROPERTYTYPE_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.PROTEINPROPERTY_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.PROTEINPROTEINCATEGORY_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.PROTEINSYNONYM_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.PROTEIN_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.REPEATTYPE_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.RHMAPMARKER_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.RHMAP_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.RHMARKER_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.RNAANATOMYLOE_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.RNAANATOMY_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.RNACATEGORY_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.RNAFEATUREEXON_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.RNAICONSTRUCT_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.RNAINSTANCECATEGORY_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.RNAINSTANCE_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.RNAIPHENOTYPE_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.RNARNACATEGORY_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.RNA_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.ROWSETMEMBER_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.ROWSET_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.SECONDARYACCS_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.SEQGROUPEXPERIMENTIMP_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.SEQUENCEFAMILYEXPERIMENT_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.SEQUENCEFAMILY_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.SEQUENCEGROUPFAMILY_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.SEQUENCEGROUPIMP_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.SEQUENCEPIECE_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.SEQUENCESEQUENCEGROUP_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.SEQUENCETYPE_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.SIMILARITYSPAN_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.SIMILARITY_SQ START WITH 1;
CREATE SEQUENCE @oracle_dots@.TRANSLATEDAAFEATSEG_SQ START WITH 1;

/* 160 sequences(s) */

SPOOL OFF
SET ECHO OFF
DISCONNECT
EXIT
