
/*                                                                                            */
/* dots-sequences.sql                                                                         */
/*                                                                                            */
/* This file was generated automatically by dumpSchema.pl on Wed Feb 12 12:23:37 EST 2003     */
/*                                                                                            */

SET ECHO ON
SPOOL dots-sequences.log

CREATE SEQUENCE DoTStest.AACOMMENT_SQ START WITH 1;
CREATE SEQUENCE DoTStest.AAENTRY_SQ START WITH 1;
CREATE SEQUENCE DoTStest.AAFAMILYEXPERIMENT_SQ START WITH 1;
CREATE SEQUENCE DoTStest.AAFEATUREIMP_SQ START WITH 1;
CREATE SEQUENCE DoTStest.AAGENESYNONYM_SQ START WITH 1;
CREATE SEQUENCE DoTStest.AAGENE_SQ START WITH 1;
CREATE SEQUENCE DoTStest.AALOCATION_SQ START WITH 1;
CREATE SEQUENCE DoTStest.AAMOTIFGOTERMRULESET_SQ START WITH 1;
CREATE SEQUENCE DoTStest.AAMOTIFGOTERMRULE_SQ START WITH 1;
CREATE SEQUENCE DoTStest.AASEQGROUPEXPERIMENTIMP_SQ START WITH 1;
CREATE SEQUENCE DoTStest.AASEQUENCEDBREF_SQ START WITH 1;
CREATE SEQUENCE DoTStest.AASEQUENCEFAMILY_SQ START WITH 1;
CREATE SEQUENCE DoTStest.AASEQUENCEGROUPFAMILY_SQ START WITH 1;
CREATE SEQUENCE DoTStest.AASEQUENCEGROUPIMP_SQ START WITH 1;
CREATE SEQUENCE DoTStest.AASEQUENCEIMP_SQ START WITH 1;
CREATE SEQUENCE DoTStest.AASEQUENCEKEYWORD_SQ START WITH 1;
CREATE SEQUENCE DoTStest.AASEQUENCEORGANELLE_SQ START WITH 1;
CREATE SEQUENCE DoTStest.AASEQUENCEREF_SQ START WITH 1;
CREATE SEQUENCE DoTStest.AASEQUENCESEQUENCEGROUP_SQ START WITH 1;
CREATE SEQUENCE DoTStest.AASEQUENCETAXON_SQ START WITH 1;
CREATE SEQUENCE DoTStest.ALLELECOMPLEMENTATION_SQ START WITH 1;
CREATE SEQUENCE DoTStest.ALLELEINSTANCE_SQ START WITH 1;
CREATE SEQUENCE DoTStest.ALLELEPHENOTYPECLASS_SQ START WITH 1;
CREATE SEQUENCE DoTStest.ALLELEPHENOTYPE_SQ START WITH 1;
CREATE SEQUENCE DoTStest.ALLELE_SQ START WITH 1;
CREATE SEQUENCE DoTStest.ANATOMYLIBRARY_SQ START WITH 1;
CREATE SEQUENCE DoTStest.ANATOMYLOE_SQ START WITH 1;
CREATE SEQUENCE DoTStest.ASSEMBLYANATOMYPERCENT_SQ START WITH 1;
CREATE SEQUENCE DoTStest.ASSEMBLYSEQUENCESNP_SQ START WITH 1;
CREATE SEQUENCE DoTStest.ASSEMBLYSEQUENCE_SQ START WITH 1;
CREATE SEQUENCE DoTStest.ASSEMBLYSNP_SQ START WITH 1;
CREATE SEQUENCE DoTStest.ATTRIBUTION_SQ START WITH 1;
CREATE SEQUENCE DoTStest.BESTSIMILARITYPAIR_SQ START WITH 1;
CREATE SEQUENCE DoTStest.BLATALIGNMENTQUALITY_SQ START WITH 1;
CREATE SEQUENCE DoTStest.BLATALIGNMENT_SQ START WITH 1;
CREATE SEQUENCE DoTStest.CLONEINSET_SQ START WITH 1;
CREATE SEQUENCE DoTStest.CLONESET_SQ START WITH 1;
CREATE SEQUENCE DoTStest.CLONE_SQ START WITH 1;
CREATE SEQUENCE DoTStest.COMMENTNAME_SQ START WITH 1;
CREATE SEQUENCE DoTStest.COMMENTS_SQ START WITH 1;
CREATE SEQUENCE DoTStest.COMPLEMENTATION_SQ START WITH 1;
CREATE SEQUENCE DoTStest.COMPLEXANATOMY_SQ START WITH 1;
CREATE SEQUENCE DoTStest.COMPLEXCOMPONENT_SQ START WITH 1;
CREATE SEQUENCE DoTStest.COMPLEXTYPE_SQ START WITH 1;
CREATE SEQUENCE DoTStest.COMPLEX_SQ START WITH 1;
CREATE SEQUENCE DoTStest.CONSISTENTALIGNMENT_SQ START WITH 1;
CREATE SEQUENCE DoTStest.DBREFNAFEATURE_SQ START WITH 1;
CREATE SEQUENCE DoTStest.DBREFNASEQUENCE_SQ START WITH 1;
CREATE SEQUENCE DoTStest.DBREFPFAMENTRY_SQ START WITH 1;
CREATE SEQUENCE DoTStest.EFFECTORACTIONTYPE_SQ START WITH 1;
CREATE SEQUENCE DoTStest.ENDSEQUENCEPAIRMAP_SQ START WITH 1;
CREATE SEQUENCE DoTStest.EPCR_SQ START WITH 1;
CREATE SEQUENCE DoTStest.EST_SQ START WITH 1;
CREATE SEQUENCE DoTStest.EVIDENCE_SQ START WITH 1;
CREATE SEQUENCE DoTStest.EXONLOCATION_SQ START WITH 1;
CREATE SEQUENCE DoTStest.FAMILYGENE_SQ START WITH 1;
CREATE SEQUENCE DoTStest.FAMILYPROTEIN_SQ START WITH 1;
CREATE SEQUENCE DoTStest.FAMILY_SQ START WITH 1;
CREATE SEQUENCE DoTStest.FEATURENAME_SQ START WITH 1;
CREATE SEQUENCE DoTStest.FINGERPRINTCLONECONTIG_SQ START WITH 1;
CREATE SEQUENCE DoTStest.FINGERPRINTCLONEMARKER_SQ START WITH 1;
CREATE SEQUENCE DoTStest.FINGERPRINTCLONE_SQ START WITH 1;
CREATE SEQUENCE DoTStest.FINGERPRINTCONTIG_SQ START WITH 1;
CREATE SEQUENCE DoTStest.FINGERPRINTMAP_SQ START WITH 1;
CREATE SEQUENCE DoTStest.GENEALIAS_SQ START WITH 1;
CREATE SEQUENCE DoTStest.GENECATEGORY_SQ START WITH 1;
CREATE SEQUENCE DoTStest.GENECHROMOSOMALLOCATION_SQ START WITH 1;
CREATE SEQUENCE DoTStest.GENEFAMILYRELATION_SQ START WITH 1;
CREATE SEQUENCE DoTStest.GENEFAMILY_SQ START WITH 1;
CREATE SEQUENCE DoTStest.GENEFEATURESAGETAGLINK_SQ START WITH 1;
CREATE SEQUENCE DoTStest.GENEFEATURESEQOVERLAP_SQ START WITH 1;
CREATE SEQUENCE DoTStest.GENEINSTANCECATEGORY_SQ START WITH 1;
CREATE SEQUENCE DoTStest.GENEINSTANCE_SQ START WITH 1;
CREATE SEQUENCE DoTStest.GENESUPERFAMILYRELATION_SQ START WITH 1;
CREATE SEQUENCE DoTStest.GENESUPERFAMILY_SQ START WITH 1;
CREATE SEQUENCE DoTStest.GENESYNONYM_SQ START WITH 1;
CREATE SEQUENCE DoTStest.GENETRAPASSEMBLY_SQ START WITH 1;
CREATE SEQUENCE DoTStest.GENE_SQ START WITH 1;
CREATE SEQUENCE DoTStest.GOASSOCIATIONINSTANCELOE_SQ START WITH 1;
CREATE SEQUENCE DoTStest.GOASSOCIATIONINSTANCE_SQ START WITH 1;
CREATE SEQUENCE DoTStest.GOASSOCIATION_SQ START WITH 1;
CREATE SEQUENCE DoTStest.GOASSOCINSTEVIDCODE_SQ START WITH 1;
CREATE SEQUENCE DoTStest.INDEXWORDLINK_SQ START WITH 1;
CREATE SEQUENCE DoTStest.INDEXWORDSIMLINK_SQ START WITH 1;
CREATE SEQUENCE DoTStest.INDEXWORD_SQ START WITH 1;
CREATE SEQUENCE DoTStest.INTERACTIONINTERACTIONLOE_SQ START WITH 1;
CREATE SEQUENCE DoTStest.INTERACTIONLOE_SQ START WITH 1;
CREATE SEQUENCE DoTStest.INTERACTIONTYPE_SQ START WITH 1;
CREATE SEQUENCE DoTStest.INTERACTION_SQ START WITH 1;
CREATE SEQUENCE DoTStest.ISEXPRESSED_SQ START WITH 1;
CREATE SEQUENCE DoTStest.KEYWORD_SQ START WITH 1;
CREATE SEQUENCE DoTStest.LIBRARY_SQ START WITH 1;
CREATE SEQUENCE DoTStest.MERGESPLIT_SQ START WITH 1;
CREATE SEQUENCE DoTStest.MOTIF_SQ START WITH 1;
CREATE SEQUENCE DoTStest.NACOMMENT_SQ START WITH 1;
CREATE SEQUENCE DoTStest.NAENTRY_SQ START WITH 1;
CREATE SEQUENCE DoTStest.NAFEATRELATIONSHIPTYPE_SQ START WITH 1;
CREATE SEQUENCE DoTStest.NAFEATURECOMMENT_SQ START WITH 1;
CREATE SEQUENCE DoTStest.NAFEATUREIMP_SQ START WITH 1;
CREATE SEQUENCE DoTStest.NAFEATURENAGENE_SQ START WITH 1;
CREATE SEQUENCE DoTStest.NAFEATURENAPROTEIN_SQ START WITH 1;
CREATE SEQUENCE DoTStest.NAFEATURENAPT_SQ START WITH 1;
CREATE SEQUENCE DoTStest.NAFEATURERELATIONSHIP_SQ START WITH 1;
CREATE SEQUENCE DoTStest.NAGENE_SQ START WITH 1;
CREATE SEQUENCE DoTStest.NALOCATION_SQ START WITH 1;
CREATE SEQUENCE DoTStest.NAPRIMARYTRANSCRIPT_SQ START WITH 1;
CREATE SEQUENCE DoTStest.NAPROTEIN_SQ START WITH 1;
CREATE SEQUENCE DoTStest.NASEQCYTOLOCATION_SQ START WITH 1;
CREATE SEQUENCE DoTStest.NASEQUENCEIMP_SQ START WITH 1;
CREATE SEQUENCE DoTStest.NASEQUENCEKEYWORD_SQ START WITH 1;
CREATE SEQUENCE DoTStest.NASEQUENCEORGANELLE_SQ START WITH 1;
CREATE SEQUENCE DoTStest.NASEQUENCEREF_SQ START WITH 1;
CREATE SEQUENCE DoTStest.NRDBENTRY_SQ START WITH 1;
CREATE SEQUENCE DoTStest.OPTICALMAPALIGNMENTSPAN_SQ START WITH 1;
CREATE SEQUENCE DoTStest.OPTICALMAPALIGNMENT_SQ START WITH 1;
CREATE SEQUENCE DoTStest.OPTICALMAPFRAGMENT_SQ START WITH 1;
CREATE SEQUENCE DoTStest.OPTICALMAP_SQ START WITH 1;
CREATE SEQUENCE DoTStest.ORGANELLE_SQ START WITH 1;
CREATE SEQUENCE DoTStest.PATHWAYINTERACTION_SQ START WITH 1;
CREATE SEQUENCE DoTStest.PATHWAY_SQ START WITH 1;
CREATE SEQUENCE DoTStest.PFAMENTRY_SQ START WITH 1;
CREATE SEQUENCE DoTStest.PLASMOMAP_SQ START WITH 1;
CREATE SEQUENCE DoTStest.PROJECTLINK_SQ START WITH 1;
CREATE SEQUENCE DoTStest.PROTEINCATEGORY_SQ START WITH 1;
CREATE SEQUENCE DoTStest.PROTEININSTANCECATEGORY_SQ START WITH 1;
CREATE SEQUENCE DoTStest.PROTEININSTANCE_SQ START WITH 1;
CREATE SEQUENCE DoTStest.PROTEINPROPERTYTYPE_SQ START WITH 1;
CREATE SEQUENCE DoTStest.PROTEINPROPERTY_SQ START WITH 1;
CREATE SEQUENCE DoTStest.PROTEINPROTEINCATEGORY_SQ START WITH 1;
CREATE SEQUENCE DoTStest.PROTEINSYNONYM_SQ START WITH 1;
CREATE SEQUENCE DoTStest.PROTEIN_SQ START WITH 1;
CREATE SEQUENCE DoTStest.REPEATTYPE_SQ START WITH 1;
CREATE SEQUENCE DoTStest.RHMAPMARKER_SQ START WITH 1;
CREATE SEQUENCE DoTStest.RHMAP_SQ START WITH 1;
CREATE SEQUENCE DoTStest.RHMARKER_SQ START WITH 1;
CREATE SEQUENCE DoTStest.RNAANATOMYLOE_SQ START WITH 1;
CREATE SEQUENCE DoTStest.RNAANATOMY_SQ START WITH 1;
CREATE SEQUENCE DoTStest.RNACATEGORY_SQ START WITH 1;
CREATE SEQUENCE DoTStest.RNAFEATUREEXON_SQ START WITH 1;
CREATE SEQUENCE DoTStest.RNAICONSTRUCT_SQ START WITH 1;
CREATE SEQUENCE DoTStest.RNAINSTANCECATEGORY_SQ START WITH 1;
CREATE SEQUENCE DoTStest.RNAINSTANCE_SQ START WITH 1;
CREATE SEQUENCE DoTStest.RNAIPHENOTYPE_SQ START WITH 1;
CREATE SEQUENCE DoTStest.RNARNACATEGORY_SQ START WITH 1;
CREATE SEQUENCE DoTStest.RNA_SQ START WITH 1;
CREATE SEQUENCE DoTStest.ROWSETMEMBER_SQ START WITH 1;
CREATE SEQUENCE DoTStest.ROWSET_SQ START WITH 1;
CREATE SEQUENCE DoTStest.SECONDARYACCS_SQ START WITH 1;
CREATE SEQUENCE DoTStest.SEQGROUPEXPERIMENTIMP_SQ START WITH 1;
CREATE SEQUENCE DoTStest.SEQUENCEFAMILYEXPERIMENT_SQ START WITH 1;
CREATE SEQUENCE DoTStest.SEQUENCEFAMILY_SQ START WITH 1;
CREATE SEQUENCE DoTStest.SEQUENCEGROUPFAMILY_SQ START WITH 1;
CREATE SEQUENCE DoTStest.SEQUENCEGROUPIMP_SQ START WITH 1;
CREATE SEQUENCE DoTStest.SEQUENCEPIECE_SQ START WITH 1;
CREATE SEQUENCE DoTStest.SEQUENCESEQUENCEGROUP_SQ START WITH 1;
CREATE SEQUENCE DoTStest.SEQUENCETYPE_SQ START WITH 1;
CREATE SEQUENCE DoTStest.SIMILARITYSPAN_SQ START WITH 1;
CREATE SEQUENCE DoTStest.SIMILARITY_SQ START WITH 1;
CREATE SEQUENCE DoTStest.TRANSLATEDAAFEATSEG_SQ START WITH 1;

/* 159 sequences(s) */

SPOOL OFF
SET ECHO OFF
DISCONNECT
EXIT
