
/*                                                                                            */
/* rad3-indexes.sql                                                                           */
/*                                                                                            */
/* This file was generated automatically by dumpSchema.pl on Wed Feb 12 12:30:10 EST 2003     */
/*                                                                                            */

SET ECHO ON
SPOOL rad3-indexes.log

/* ACQUISITION */
create unique index RAD3test.ACQUISITION_AK01 on RAD3test.ACQUISITION (NAME)  TABLESPACE INDX2;
create index RAD3test.ACQUISITION_IND01 on RAD3test.ACQUISITION (ASSAY_ID)  TABLESPACE INDX2;
create index RAD3test.ACQUISITION_IND02 on RAD3test.ACQUISITION (CHANNEL_ID)  TABLESPACE INDX2;
create index RAD3test.ACQUISITION_IND03 on RAD3test.ACQUISITION (PROTOCOL_ID)  TABLESPACE INDX2;

/* ACQUISITIONPARAM */
create unique index RAD3test.ACQPARAM_AK01 on RAD3test.ACQUISITIONPARAM (ACQUISITION_ID,NAME)  TABLESPACE INDX2;

/* ANALYSIS */


/* ANALYSISIMPLEMENTATION */
create index RAD3test.ANALYSISIMPLEMENTATION_IND01 on RAD3test.ANALYSISIMPLEMENTATION (ANALYSIS_ID)  TABLESPACE INDX2;

/* ANALYSISIMPLEMENTATIONPARAM */
create index RAD3test.ANALYSISIMPPARAM_IND01 on RAD3test.ANALYSISIMPLEMENTATIONPARAM (ANALYSIS_IMPLEMENTATION_ID)  TABLESPACE INDX2;

/* ANALYSISINPUT */
create index RAD3test.ANALYSISINPUT_IND01 on RAD3test.ANALYSISINPUT (ANALYSIS_INVOCATION_ID)  TABLESPACE INDX2;
create index RAD3test.ANALYSISINPUT_IND02 on RAD3test.ANALYSISINPUT (TABLE_ID)  TABLESPACE INDX2;

/* ANALYSISINVOCATION */
create index RAD3test.ANALYSISINVOCATION_IND01 on RAD3test.ANALYSISINVOCATION (ANALYSIS_IMPLEMENTATION_ID)  TABLESPACE INDX2;

/* ANALYSISINVOCATIONPARAM */
create index RAD3test.ANALYSISINVOCATIONPARAM_IND01 on RAD3test.ANALYSISINVOCATIONPARAM (ANALYSIS_INVOCATION_ID)  TABLESPACE INDX2;

/* ANALYSISOUTPUT */
create index RAD3test.ANALYSISOUTPUT_IND01 on RAD3test.ANALYSISOUTPUT (ANALYSIS_INVOCATION_ID)  TABLESPACE INDX2;

/* ARRAY */
create unique index RAD3test.ARRAY_AK01 on RAD3test.ARRAY (NAME,VERSION)  TABLESPACE INDX2;
create index RAD3test.ARRAY_IND02 on RAD3test.ARRAY (EXTERNAL_DATABASE_RELEASE_ID)  TABLESPACE INDX2;
create index RAD3test.ARRAY_IND03 on RAD3test.ARRAY (PLATFORM_TYPE_ID)  TABLESPACE INDX2;
create index RAD3test.ARRAY_IND04 on RAD3test.ARRAY (SUBSTRATE_TYPE_ID)  TABLESPACE INDX2;
create index RAD3test.ARRAY_IND05 on RAD3test.ARRAY (PROTOCOL_ID)  TABLESPACE INDX2;
create index RAD3test.ARRAY_IND06 on RAD3test.ARRAY (MANUFACTURER_ID)  TABLESPACE INDX2;

/* ARRAYANNOTATION */
create index RAD3test.ARRAYANNOTATION_IND01 on RAD3test.ARRAYANNOTATION (ARRAY_ID)  TABLESPACE INDX2;

/* ASSAY */
create index RAD3test.ASSAY_IND01 on RAD3test.ASSAY (ARRAY_ID)  TABLESPACE INDX2;
create index RAD3test.ASSAY_IND02 on RAD3test.ASSAY (OPERATOR_ID)  TABLESPACE INDX2;
create index RAD3test.ASSAY_IND03 on RAD3test.ASSAY (PROTOCOL_ID)  TABLESPACE INDX2;
create index RAD3test.ASSAY_IND04 on RAD3test.ASSAY (EXTERNAL_DATABASE_RELEASE_ID)  TABLESPACE INDX2;
create unique index RAD3test.ASSAY_AK01 on RAD3test.ASSAY (NAME)  TABLESPACE INDX2;

/* ASSAYBIOMATERIAL */
create index RAD3test.ASSAYBIOMATERIAL_IND02 on RAD3test.ASSAYBIOMATERIAL (ASSAY_ID)  TABLESPACE INDX2;
create index RAD3test.ASSAYBIOMATERIAL_IND01 on RAD3test.ASSAYBIOMATERIAL (BIO_MATERIAL_ID)  TABLESPACE INDX2;

/* ASSAYLABELEDEXTRACT */
create index RAD3test.ASSAYLABELEDEXTRACT_IND01 on RAD3test.ASSAYLABELEDEXTRACT (ASSAY_ID)  TABLESPACE INDX2;
create index RAD3test.ASSAYLABELEDEXTRACT_IND02 on RAD3test.ASSAYLABELEDEXTRACT (CHANNEL_ID)  TABLESPACE INDX2;
create index RAD3test.ASSAYLABELEDEXTRACT_IND03 on RAD3test.ASSAYLABELEDEXTRACT (LABELED_EXTRACT_ID)  TABLESPACE INDX2;

/* ASSAYPARAM */
create index RAD3test.ASSAYPARAM_IND01 on RAD3test.ASSAYPARAM (ASSAY_ID)  TABLESPACE INDX2;
create index RAD3test.ASSAYPARAM_IND02 on RAD3test.ASSAYPARAM (PROTOCOL_PARAM_ID)  TABLESPACE INDX2;

/* BIOMATERIALCHARACTERISTIC */
create index RAD3test.BIOMATCHARACTERISTIC_IND01 on RAD3test.BIOMATERIALCHARACTERISTIC (BIO_MATERIAL_ID)  TABLESPACE INDX2;
create index RAD3test.BIOMATCHARACTERISTIC_IND02 on RAD3test.BIOMATERIALCHARACTERISTIC (ONTOLOGY_ENTRY_ID)  TABLESPACE INDX2;

/* BIOMATERIALIMP */
create index RAD3test.BIOMATERIALIMP_IND01 on RAD3test.BIOMATERIALIMP (LABEL_METHOD_ID)  TABLESPACE INDX2;
create index RAD3test.BIOMATERIALIMP_IND02 on RAD3test.BIOMATERIALIMP (TAXON_ID)  TABLESPACE INDX2;
create index RAD3test.BIOMATERIALIMP_IND03 on RAD3test.BIOMATERIALIMP (BIO_MATERIAL_TYPE_ID)  TABLESPACE INDX2;
create index RAD3test.BIOMATERIALIMP_IND04 on RAD3test.BIOMATERIALIMP (BIO_SOURCE_PROVIDER_ID)  TABLESPACE INDX2;
create index RAD3test.BIOMATERIALIMP_IND05 on RAD3test.BIOMATERIALIMP (EXTERNAL_DATABASE_RELEASE_ID)  TABLESPACE INDX2;

/* BIOMATERIALMEASUREMENT */
create index RAD3test.BIOMATERIALMEASUREMENT_IND04 on RAD3test.BIOMATERIALMEASUREMENT (BIO_MATERIAL_ID)  TABLESPACE INDX2;
create index RAD3test.BIOMATERIALMEASUREMENT_IND05 on RAD3test.BIOMATERIALMEASUREMENT (UNIT_TYPE_ID)  TABLESPACE INDX2;
create index RAD3test.BIOMATERIALMEASUREMENT_IND03 on RAD3test.BIOMATERIALMEASUREMENT (TREATMENT_ID)  TABLESPACE INDX2;

/* CHANNEL */
create unique index RAD3test.CHANNEL_AK01 on RAD3test.CHANNEL (NAME)  TABLESPACE INDX2;

/* COMPOSITEELEMENTANNOTATION */
create index RAD3test.COMPELEMENTANNOT_IND01 on RAD3test.COMPOSITEELEMENTANNOTATION (COMPOSITE_ELEMENT_ID)  TABLESPACE INDX2;

/* COMPOSITEELEMENTGUS */
create index RAD3test.COMPOSITEELEMENTGUS_IND01 on RAD3test.COMPOSITEELEMENTGUS (COMPOSITE_ELEMENT_ID,TABLE_ID,ROW_ID)  TABLESPACE INDX2;
create index RAD3test.COMPOSITEELEMENTGUS_IND02 on RAD3test.COMPOSITEELEMENTGUS (TABLE_ID,ROW_ID,COMPOSITE_ELEMENT_ID)  TABLESPACE INDX2;

/* COMPOSITEELEMENTIMP */
create index RAD3test.RAD3_SPOTFAMILY_IND01 on RAD3test.COMPOSITEELEMENTIMP (SMALLSTRING1,SMALLSTRING2,COMPOSITE_ELEMENT_ID)  TABLESPACE INDX2;
create index RAD3test.RAD3_SPOTFAMILY_IND02 on RAD3test.COMPOSITEELEMENTIMP (ARRAY_ID,SOURCE_ID,EXTERNAL_DATABASE_RELEASE_ID)  TABLESPACE INDX2;
create index RAD3test.SAGETAG_IND02 on RAD3test.COMPOSITEELEMENTIMP (PARENT_ID)  TABLESPACE INDX2;
create index RAD3test.SAGETAG_IND03 on RAD3test.COMPOSITEELEMENTIMP (EXTERNAL_DATABASE_RELEASE_ID)  TABLESPACE INDX2;
create index RAD3test.SAGETAG_IND01 on RAD3test.COMPOSITEELEMENTIMP (ARRAY_ID,TINYSTRING1)  TABLESPACE INDX2;

/* COMPOSITEELEMENTRESULTIMP */
create index RAD3test.COMPELEMENTRESULTIMP_IND01 on RAD3test.COMPOSITEELEMENTRESULTIMP (COMPOSITE_ELEMENT_ID,SUBCLASS_VIEW)  TABLESPACE INDX2;
create index RAD3test.COMPELEMENTRESULTIMP_IND02 on RAD3test.COMPOSITEELEMENTRESULTIMP (QUANTIFICATION_ID,COMPOSITE_ELEMENT_ID,SUBCLASS_VIEW)  TABLESPACE INDX2;

/* CONTROL */
create index RAD3test.CONTROL_IND01 on RAD3test.CONTROL (TABLE_ID)  TABLESPACE INDX2;
create index RAD3test.CONTROL_IND02 on RAD3test.CONTROL (ASSAY_ID)  TABLESPACE INDX2;
create index RAD3test.CONTROL_IND03 on RAD3test.CONTROL (CONTROL_TYPE_ID)  TABLESPACE INDX2;

/* ELEMENTANNOTATION */
create index RAD3test.ELEMENTANNOTATION_IND01 on RAD3test.ELEMENTANNOTATION (ELEMENT_ID)  TABLESPACE INDX2;

/* ELEMENTIMP */
create index RAD3test.RAD3_SPOT_IND02 on RAD3test.ELEMENTIMP (COMPOSITE_ELEMENT_ID)  TABLESPACE INDX2;
create index RAD3test.SHORTOLIGO_IND02 on RAD3test.ELEMENTIMP (ELEMENT_TYPE_ID)  TABLESPACE INDX2;
create index RAD3test.SHORTOLIGO_IND03 on RAD3test.ELEMENTIMP (EXTERNAL_DATABASE_RELEASE_ID)  TABLESPACE INDX2;
create index RAD3test.SPOT_IND01 on RAD3test.ELEMENTIMP (ARRAY_ID,CHAR1,CHAR2,CHAR3,CHAR4,CHAR5,CHAR6)  TABLESPACE INDX2;
create index RAD3test.SAGETAMAPPING_IND01 on RAD3test.ELEMENTIMP (ARRAY_ID,EXTERNAL_DATABASE_RELEASE_ID,SOURCE_ID)  TABLESPACE INDX2;
create index RAD3test.ARRAY_IND01 on RAD3test.ELEMENTIMP (ARRAY_ID)  TABLESPACE INDX2;
create index RAD3test.SHORTOLIGO_IND01 on RAD3test.ELEMENTIMP (ARRAY_ID,TINYSTRING1,TINYSTRING2)  TABLESPACE INDX2;

/* ELEMENTRESULTIMP */
create index RAD3test.ELEMENTRESULTIMP_IND01 on RAD3test.ELEMENTRESULTIMP (ELEMENT_ID,SUBCLASS_VIEW)  TABLESPACE INDX2;
create index RAD3test.ELEMENTRESULTIMP_IND02 on RAD3test.ELEMENTRESULTIMP (QUANTIFICATION_ID,ELEMENT_ID,SUBCLASS_VIEW)  TABLESPACE INDX2;
create index RAD3test.ELEMENTRESULTIMP_IND03 on RAD3test.ELEMENTRESULTIMP (COMPOSITE_ELEMENT_RESULT_ID)  TABLESPACE INDX2;

/* LABELMETHOD */
create index RAD3test.LABELMETHOD_IND01 on RAD3test.LABELMETHOD (PROTOCOL_ID)  TABLESPACE INDX2;
create index RAD3test.LABELMETHOD_IND02 on RAD3test.LABELMETHOD (CHANNEL_ID)  TABLESPACE INDX2;

/* MAGEDOCUMENTATION */
create index RAD3test.MAGEDOCUMENTATION_IND01 on RAD3test.MAGEDOCUMENTATION (TABLE_ID)  TABLESPACE INDX2;
create index RAD3test.MAGEDOCUMENTATION_IND02 on RAD3test.MAGEDOCUMENTATION (MAGE_ML_ID)  TABLESPACE INDX2;

/* MAGE_ML */


/* ONTOLOGYENTRY */
create index RAD3test.ONTOLOGYENTRY_IND01 on RAD3test.ONTOLOGYENTRY (PARENT_ID)  TABLESPACE INDX2;
create index RAD3test.ONTOLOGYENTRY_IND02 on RAD3test.ONTOLOGYENTRY (TABLE_ID)  TABLESPACE INDX2;
create index RAD3test.ONTOLOGYENTRY_IND03 on RAD3test.ONTOLOGYENTRY (EXTERNAL_DATABASE_RELEASE_ID)  TABLESPACE INDX2;
create unique index RAD3test.ONTOLOGYENTRY_AK01 on RAD3test.ONTOLOGYENTRY (CATEGORY,VALUE)  TABLESPACE INDX2;

/* PROCESSIMPLEMENTATION */
create index RAD3test.PROCESSIMPLEMENTATION_IND_01 on RAD3test.PROCESSIMPLEMENTATION (PROCESS_TYPE_ID)  TABLESPACE INDX2;

/* PROCESSIMPLEMENTATIONPARAM */
create index RAD3test.PROCESSIMPPARAM_IND01 on RAD3test.PROCESSIMPLEMENTATIONPARAM (PROCESS_IMPLEMENTATION_ID)  TABLESPACE INDX2;

/* PROCESSINVOCATION */
create index RAD3test.PROCESSINVOCATION_IND01 on RAD3test.PROCESSINVOCATION (PROCESS_IMPLEMENTATION_ID)  TABLESPACE INDX2;

/* PROCESSINVOCATIONPARAM */
create index RAD3test.PROCESSINVOCATIONPARAM_IND01 on RAD3test.PROCESSINVOCATIONPARAM (PROCESS_INVOCATION_ID)  TABLESPACE INDX2;

/* PROCESSINVQUANTIFICATION */
create index RAD3test.PROCESSINVQUANTIFICATION_IND01 on RAD3test.PROCESSINVQUANTIFICATION (PROCESS_INVOCATION_ID)  TABLESPACE INDX2;
create index RAD3test.PROCESSINVQUANTIFICATION_IND02 on RAD3test.PROCESSINVQUANTIFICATION (QUANTIFICATION_ID)  TABLESPACE INDX2;

/* PROCESSIO */
create index RAD3test.PROCESSIO_IND_01 on RAD3test.PROCESSIO (OUTPUT_RESULT_ID)  TABLESPACE INDX2;
create index RAD3test.PROCESSIO_IND_02 on RAD3test.PROCESSIO (PROCESS_INVOCATION_ID)  TABLESPACE INDX2;
create index RAD3test.PROCESSIO_IND_03 on RAD3test.PROCESSIO (INPUT_RESULT_ID,TABLE_ID,OUTPUT_RESULT_ID)  TABLESPACE INDX2;
create index RAD3test.PROCESSIO_IND01 on RAD3test.PROCESSIO (TABLE_ID)  TABLESPACE INDX2;

/* PROCESSIOELEMENT */
create index RAD3test.PROCESSIOELEMENT_IND01 on RAD3test.PROCESSIOELEMENT (PROCESS_IO_ID)  TABLESPACE INDX2;

/* PROCESSRESULT */
create index RAD3test.PROCESSRESULT_IND01 on RAD3test.PROCESSRESULT (PROCESS_RESULT_ID,VALUE)  TABLESPACE INDX2;
create index RAD3test.PROCESSRESULT_IND02 on RAD3test.PROCESSRESULT (UNIT_TYPE_ID)  TABLESPACE INDX2;

/* PROJECTLINK */
create index RAD3test.PROJECTLINK_IND03 on RAD3test.PROJECTLINK (ID)  TABLESPACE INDX2;
create index RAD3test.PROJECTLINK_IND02 on RAD3test.PROJECTLINK (TABLE_ID)  TABLESPACE INDX2;
create index RAD3test.PROJECTLINK_IND01 on RAD3test.PROJECTLINK (PROJECT_ID)  TABLESPACE INDX2;

/* PROTOCOL */
create index RAD3test.PROTOCOL_IND01 on RAD3test.PROTOCOL (BIBLIOGRAPHIC_REFERENCE_ID)  TABLESPACE INDX2;
create index RAD3test.PROTOCOL_IND02 on RAD3test.PROTOCOL (EXTERNAL_DATABASE_RELEASE_ID)  TABLESPACE INDX2;
create index RAD3test.PROTOCOL_IND03 on RAD3test.PROTOCOL (PROTOCOL_TYPE_ID)  TABLESPACE INDX2;
create unique index RAD3test.PROTOCOL_AK01 on RAD3test.PROTOCOL (NAME)  TABLESPACE INDX2;

/* PROTOCOLPARAM */
create index RAD3test.PROTOCOLPARAM_IND01 on RAD3test.PROTOCOLPARAM (DATA_TYPE_ID)  TABLESPACE INDX2;
create index RAD3test.PROTOCOLPARAM_IND02 on RAD3test.PROTOCOLPARAM (UNIT_TYPE_ID)  TABLESPACE INDX2;
create index RAD3test.PROTOCOLPARAM_IND03 on RAD3test.PROTOCOLPARAM (PROTOCOL_ID)  TABLESPACE INDX2;

/* QUANTIFICATION */
create unique index RAD3test.QUANTIFICATION_AK01 on RAD3test.QUANTIFICATION (NAME)  TABLESPACE INDX2;
create index RAD3test.QUANTIFICATION_IND01 on RAD3test.QUANTIFICATION (ACQUISITION_ID)  TABLESPACE INDX2;
create index RAD3test.QUANTIFICATION_IND02 on RAD3test.QUANTIFICATION (OPERATOR_ID)  TABLESPACE INDX2;
create index RAD3test.QUANTIFICATION_IND03 on RAD3test.QUANTIFICATION (PROTOCOL_ID)  TABLESPACE INDX2;
create index RAD3test.QUANTIFICATION_IND04 on RAD3test.QUANTIFICATION (RESULT_TABLE_ID)  TABLESPACE INDX2;

/* QUANTIFICATIONPARAM */
create unique index RAD3test.QUANTPARAM_AK01 on RAD3test.QUANTIFICATIONPARAM (QUANTIFICATION_ID,NAME)  TABLESPACE INDX2;

/* RELATEDACQUISITION */
create index RAD3test.RELATEDACQUISITION_IND01 on RAD3test.RELATEDACQUISITION (ACQUISITION_ID)  TABLESPACE INDX2;
create index RAD3test.RELATEDACQUISITION_IND02 on RAD3test.RELATEDACQUISITION (ASSOCIATED_ACQUISITION_ID)  TABLESPACE INDX2;

/* RELATEDQUANTIFICATION */
create index RAD3test.RELATEDQUANTIFICATION_IND01 on RAD3test.RELATEDQUANTIFICATION (QUANTIFICATION_ID)  TABLESPACE INDX2;
create index RAD3test.RELATEDQUANTIFICATION_IND02 on RAD3test.RELATEDQUANTIFICATION (ASSOCIATED_QUANTIFICATION_ID)  TABLESPACE INDX2;

/* STUDY */
create unique index RAD3test.STUDY_AK01 on RAD3test.STUDY (NAME)  TABLESPACE INDX2;
create index RAD3test.STUDY_IND01 on RAD3test.STUDY (BIBLIOGRAPHIC_REFERENCE_ID)  TABLESPACE INDX2;
create index RAD3test.STUDY_IND02 on RAD3test.STUDY (CONTACT_ID)  TABLESPACE INDX2;
create index RAD3test.STUDY_IND03 on RAD3test.STUDY (EXTERNAL_DATABASE_RELEASE_ID)  TABLESPACE INDX2;

/* STUDYASSAY */
create index RAD3test.STUDYASSAY_IND01 on RAD3test.STUDYASSAY (ASSAY_ID)  TABLESPACE INDX2;
create index RAD3test.STUDYASSAY_IND02 on RAD3test.STUDYASSAY (STUDY_ID)  TABLESPACE INDX2;

/* STUDYDESIGN */
create index RAD3test.STUDYDESIGN_IND01 on RAD3test.STUDYDESIGN (STUDY_ID)  TABLESPACE INDX2;

/* STUDYDESIGNASSAY */
create index RAD3test.STUDYDESIGNASSAY_IND01 on RAD3test.STUDYDESIGNASSAY (ASSAY_ID)  TABLESPACE INDX2;
create index RAD3test.STUDYDESIGNASSAY_IND02 on RAD3test.STUDYDESIGNASSAY (STUDY_DESIGN_ID)  TABLESPACE INDX2;

/* STUDYDESIGNDESCRIPTION */
create index RAD3test.STUDYDESIGNDESCRIPTION_IND01 on RAD3test.STUDYDESIGNDESCRIPTION (STUDY_DESIGN_ID)  TABLESPACE INDX2;

/* STUDYDESIGNTYPE */
create index RAD3test.STUDYDESIGNTYPE_IND01 on RAD3test.STUDYDESIGNTYPE (ONTOLOGY_ENTRY_ID)  TABLESPACE INDX2;
create index RAD3test.STUDYDESIGNTYPE_IND02 on RAD3test.STUDYDESIGNTYPE (STUDY_DESIGN_ID)  TABLESPACE INDX2;

/* STUDYFACTOR */
create unique index RAD3test.STUDYFACTOR_AK01 on RAD3test.STUDYFACTOR (STUDY_DESIGN_ID,NAME)  TABLESPACE INDX2;
create index RAD3test.STUDYFACTOR_IND01 on RAD3test.STUDYFACTOR (STUDY_FACTOR_TYPE_ID)  TABLESPACE INDX2;

/* STUDYFACTORVALUE */
create index RAD3test.STUDYFACTORVALUE_IND01 on RAD3test.STUDYFACTORVALUE (ASSAY_ID)  TABLESPACE INDX2;
create index RAD3test.STUDYFACTORVALUE_IND02 on RAD3test.STUDYFACTORVALUE (STUDY_FACTOR_ID)  TABLESPACE INDX2;

/* TREATMENT */
create index RAD3test.TREATMENT_IND01 on RAD3test.TREATMENT (BIO_MATERIAL_ID)  TABLESPACE INDX2;
create index RAD3test.TREATMENT_IND02 on RAD3test.TREATMENT (TREATMENT_TYPE_ID)  TABLESPACE INDX2;
create index RAD3test.TREATMENT_IND03 on RAD3test.TREATMENT (PROTOCOL_ID)  TABLESPACE INDX2;

/* TREATMENTPARAM */
create index RAD3test.TREATMENTPARAM_IND01 on RAD3test.TREATMENTPARAM (PROTOCOL_PARAM_ID)  TABLESPACE INDX2;
create index RAD3test.TREATMENTPARAM_IND02 on RAD3test.TREATMENTPARAM (TREATMENT_ID)  TABLESPACE INDX2;



/* 128 index(es) */

SPOOL OFF
SET ECHO OFF
DISCONNECT
EXIT
