
/*                                                                                            */
/* rad3-sequences.sql                                                                         */
/*                                                                                            */
/* This file was generated automatically by dumpSchema.pl on Wed Feb 12 12:29:24 EST 2003     */
/*                                                                                            */

SET ECHO ON
SPOOL rad3-sequences.log

CREATE SEQUENCE RAD3test.ACQUISITIONPARAM_SQ START WITH 1;
CREATE SEQUENCE RAD3test.ACQUISITION_SQ START WITH 1;
CREATE SEQUENCE RAD3test.ANALYSISIMPLEMENTATIONPARAM_SQ START WITH 1;
CREATE SEQUENCE RAD3test.ANALYSISIMPLEMENTATION_SQ START WITH 1;
CREATE SEQUENCE RAD3test.ANALYSISINPUT_SQ START WITH 1;
CREATE SEQUENCE RAD3test.ANALYSISINVOCATIONPARAM_SQ START WITH 1;
CREATE SEQUENCE RAD3test.ANALYSISINVOCATION_SQ START WITH 1;
CREATE SEQUENCE RAD3test.ANALYSISOUTPUT_SQ START WITH 1;
CREATE SEQUENCE RAD3test.ANALYSIS_SQ START WITH 1;
CREATE SEQUENCE RAD3test.ARRAYANNOTATION_SQ START WITH 1;
CREATE SEQUENCE RAD3test.ARRAY_SQ START WITH 1;
CREATE SEQUENCE RAD3test.ASSAYBIOMATERIAL_SQ START WITH 1;
CREATE SEQUENCE RAD3test.ASSAYLABELEDEXTRACT_SQ START WITH 1;
CREATE SEQUENCE RAD3test.ASSAYPARAM_SQ START WITH 1;
CREATE SEQUENCE RAD3test.ASSAY_SQ START WITH 1;
CREATE SEQUENCE RAD3test.BIOMATERIALCHARACTERISTIC_SQ START WITH 1;
CREATE SEQUENCE RAD3test.BIOMATERIALIMP_SQ START WITH 1;
CREATE SEQUENCE RAD3test.BIOMATERIALMEASUREMENT_SQ START WITH 1;
CREATE SEQUENCE RAD3test.CHANNEL_SQ START WITH 1;
CREATE SEQUENCE RAD3test.COMPOSITEELEMENTANNOTATION_SQ START WITH 1;
CREATE SEQUENCE RAD3test.COMPOSITEELEMENTGUS_SQ START WITH 1;
CREATE SEQUENCE RAD3test.COMPOSITEELEMENTIMP_SQ START WITH 1;
CREATE SEQUENCE RAD3test.COMPOSITEELEMENTRESULTIMP_SQ START WITH 1;
CREATE SEQUENCE RAD3test.CONTROL_SQ START WITH 1;
CREATE SEQUENCE RAD3test.ELEMENTANNOTATION_SQ START WITH 1;
CREATE SEQUENCE RAD3test.ELEMENTIMP_SQ START WITH 1;
CREATE SEQUENCE RAD3test.ELEMENTRESULTIMP_SQ START WITH 1;
CREATE SEQUENCE RAD3test.FORMHELP_SQ START WITH 1;
CREATE SEQUENCE RAD3test.LABELMETHOD_SQ START WITH 1;
CREATE SEQUENCE RAD3test.MAGEDOCUMENTATION_SQ START WITH 1;
CREATE SEQUENCE RAD3test.ONTOLOGYENTRY_SQ START WITH 1;
CREATE SEQUENCE RAD3test.PROCESSIMPLEMENTATIONPARAM_SQ START WITH 1;
CREATE SEQUENCE RAD3test.PROCESSIMPLEMENTATION_SQ START WITH 1;
CREATE SEQUENCE RAD3test.PROCESSINVOCATIONPARAM_SQ START WITH 1;
CREATE SEQUENCE RAD3test.PROCESSINVOCATION_SQ START WITH 1;
CREATE SEQUENCE RAD3test.PROCESSIOELEMENT_SQ START WITH 1;
CREATE SEQUENCE RAD3test.PROCESSIO_SQ START WITH 1;
CREATE SEQUENCE RAD3test.PROCESSRESULT_SQ START WITH 1;
CREATE SEQUENCE RAD3test.PROJECTLINK_SQ START WITH 1;
CREATE SEQUENCE RAD3test.PROTOCOLPARAM_SQ START WITH 1;
CREATE SEQUENCE RAD3test.PROTOCOL_SQ START WITH 1;
CREATE SEQUENCE RAD3test.QUANTIFICATIONPARAM_SQ START WITH 1;
CREATE SEQUENCE RAD3test.QUANTIFICATION_SQ START WITH 1;
CREATE SEQUENCE RAD3test.RELATEDACQUISITION_SQ START WITH 1;
CREATE SEQUENCE RAD3test.RELATEDQUANTIFICATION_SQ START WITH 1;
CREATE SEQUENCE RAD3test.STUDYASSAY_SQ START WITH 1;
CREATE SEQUENCE RAD3test.STUDYDESIGNASSAY_SQ START WITH 1;
CREATE SEQUENCE RAD3test.STUDYDESIGNDESCRIPTION_SQ START WITH 1;
CREATE SEQUENCE RAD3test.STUDYDESIGNTYPE_SQ START WITH 1;
CREATE SEQUENCE RAD3test.STUDYDESIGN_SQ START WITH 1;
CREATE SEQUENCE RAD3test.STUDYFACTORVALUE_SQ START WITH 1;
CREATE SEQUENCE RAD3test.STUDYFACTOR_SQ START WITH 1;
CREATE SEQUENCE RAD3test.STUDY_SQ START WITH 1;
CREATE SEQUENCE RAD3test.TREATMENTPARAM_SQ START WITH 1;
CREATE SEQUENCE RAD3test.TREATMENT_SQ START WITH 1;

/* 55 sequences(s) */

SPOOL OFF
SET ECHO OFF
DISCONNECT
EXIT
