
/*                                                                                            */
/* rad3ver-constraints.sql                                                                    */
/*                                                                                            */
/* This file was generated automatically by dumpSchema.pl on Tue Dec  9 16:09:43 EST 2003     */
/*                                                                                            */

SET ECHO ON
SPOOL rad3ver-constraints.log

/* NON-PRIMARY KEY CONSTRAINTS */

/* ACQUISITIONPARAMVER */

/* ACQUISITIONVER */

/* ANALYSISINPUTVER */

/* ANALYSISPARAMVER */

/* ANALYSISQCPARAMVER */

/* ANALYSISRESULTIMPVER */

/* ANALYSISVER */

/* ARRAYANNOTATIONVER */

/* ARRAYGROUPLINKVER */

/* ARRAYGROUPVER */

/* ARRAYVER */

/* ASSAYBIOMATERIALVER */

/* ASSAYLABELEDEXTRACTVER */

/* ASSAYPARAMVER */

/* ASSAYVER */

/* BIOMATERIALCHARACTERISTICVER */

/* BIOMATERIALIMPVER */

/* BIOMATERIALMEASUREMENTVER */

/* CHANNELVER */

/* COMPOSITEELEMENTANNOTATIONVER */

/* COMPOSITEELEMENTGUSVER */

/* COMPOSITEELEMENTIMPVER */

/* COMPOSITEELEMENTRESULTIMPVER */

/* CONTROLVER */

/* ELEMENTANNOTATIONVER */

/* ELEMENTIMPVER */

/* ELEMENTRESULTIMPVER */

/* INTEGRITYSTATINPUTVER */

/* INTEGRITYSTATISTICVER */

/* LABELMETHODVER */

/* LOGICALGROUPLINKVER */

/* LOGICALGROUPVER */

/* MAGEDOCUMENTATIONVER */

/* MAGE_MLVER */

/* ONTOLOGYENTRYVER */

/* PROCESSIMPLEMENTATIONPARAMVER */

/* PROCESSIMPLEMENTATIONVER */

/* PROCESSINVOCATIONPARAMVER */

/* PROCESSINVOCATIONVER */

/* PROCESSINVQUANTIFICATIONVER */

/* PROCESSIOELEMENTVER */

/* PROCESSIOVER */

/* PROCESSRESULTVER */

/* PROJECTLINKVER */

/* PROTOCOLPARAMVER */

/* PROTOCOLQCPARAMVER */

/* PROTOCOLVER */

/* QUANTIFICATIONPARAMVER */

/* QUANTIFICATIONVER */

/* RELATEDACQUISITIONVER */

/* RELATEDQUANTIFICATIONVER */

/* STUDYASSAYVER */

/* STUDYBIOMATERIALVER */

/* STUDYDESIGNASSAYVER */

/* STUDYDESIGNDESCRIPTIONVER */

/* STUDYDESIGNTYPEVER */

/* STUDYDESIGNVER */

/* STUDYFACTORVALUEVER */

/* STUDYFACTORVER */

/* STUDYVER */

/* TREATMENTPARAMVER */

/* TREATMENTVER */



/* 0 non-primary key constraint(s) */

SPOOL OFF
SET ECHO OFF
DISCONNECT
EXIT
