
/*                                                                                            */
/* rad3-sequences.sql                                                                         */
/*                                                                                            */
/* This file was generated automatically by dumpSchema.pl on Tue Dec  9 16:08:34 EST 2003     */
/*                                                                                            */

SET ECHO ON
SPOOL rad3-sequences.log

CREATE SEQUENCE @oracle_rad@.ACQUISITIONPARAM_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.ACQUISITION_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.ANALYSISIMPLEMENTATIONPARAM_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.ANALYSISIMPLEMENTATION_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.ANALYSISINPUT_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.ANALYSISINVOCATIONPARAM_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.ANALYSISINVOCATION_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.ANALYSISOUTPUT_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.ANALYSISPARAM_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.ANALYSISQCPARAM_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.ANALYSIS_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.ARRAYANNOTATION_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.ARRAYGROUPLINK_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.ARRAYGROUP_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.ARRAY_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.ASSAYBIOMATERIAL_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.ASSAYCONTROL_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.ASSAYLABELEDEXTRACT_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.ASSAYPARAM_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.ASSAY_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.BIOMATERIALCHARACTERISTIC_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.BIOMATERIALIMP_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.BIOMATERIALMEASUREMENT_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.CHANNEL_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.COMPOSITEELEMENTANNOTATION_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.COMPOSITEELEMENTGUS_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.COMPOSITEELEMENTIMP_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.COMPOSITEELEMENTRESULTIMP_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.CONTROL_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.ELEMENTANNOTATION_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.ELEMENTIMP_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.ELEMENTRESULTIMP_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.INTEGRITYSTATINPUT_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.INTEGRITYSTATISTIC_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.LABELMETHOD_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.LOGICALGROUPLINK_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.LOGICALGROUP_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.MAGEDOCUMENTATION_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.ONTOLOGYENTRY_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.PROCESSIMPLEMENTATIONPARAM_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.PROCESSIMPLEMENTATION_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.PROCESSINVOCATIONPARAM_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.PROCESSINVOCATION_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.PROCESSIOELEMENT_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.PROCESSIO_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.PROCESSRESULT_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.PROJECTLINK_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.PROTOCOLPARAM_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.PROTOCOLQCPARAM_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.PROTOCOL_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.QUANTIFICATIONPARAM_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.QUANTIFICATION_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.RELATEDACQUISITION_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.RELATEDQUANTIFICATION_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.STUDYASSAY_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.STUDYBIOMATERIAL_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.STUDYDESIGNASSAY_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.STUDYDESIGNDESCRIPTION_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.STUDYDESIGNTYPE_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.STUDYDESIGN_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.STUDYFACTORVALUE_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.STUDYFACTOR_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.STUDY_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.TREATMENTPARAM_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad@.TREATMENT_SQ START WITH 1;

/* 65 sequences(s) */

SPOOL OFF
SET ECHO OFF
DISCONNECT
EXIT
