
/*                                                                                            */
/* rad3-sequences.sql                                                                         */
/*                                                                                            */
/* This file was generated automatically by dumpSchema.pl on Wed Feb 12 20:48:47 EST 2003     */
/*                                                                                            */

SET ECHO ON
SPOOL rad3-sequences.log

CREATE SEQUENCE @oracle_rad3@.ACQUISITIONPARAM_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.ACQUISITION_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.ANALYSISIMPLEMENTATIONPARAM_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.ANALYSISIMPLEMENTATION_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.ANALYSISINPUT_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.ANALYSISINVOCATIONPARAM_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.ANALYSISINVOCATION_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.ANALYSISOUTPUT_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.ANALYSIS_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.ARRAYANNOTATION_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.ARRAY_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.ASSAYBIOMATERIAL_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.ASSAYLABELEDEXTRACT_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.ASSAYPARAM_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.ASSAY_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.BIOMATERIALCHARACTERISTIC_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.BIOMATERIALIMP_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.BIOMATERIALMEASUREMENT_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.CHANNEL_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.COMPOSITEELEMENTANNOTATION_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.COMPOSITEELEMENTGUS_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.COMPOSITEELEMENTIMP_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.COMPOSITEELEMENTRESULTIMP_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.CONTROL_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.ELEMENTANNOTATION_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.ELEMENTIMP_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.ELEMENTRESULTIMP_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.FORMHELP_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.LABELMETHOD_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.MAGEDOCUMENTATION_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.ONTOLOGYENTRY_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.PROCESSIMPLEMENTATIONPARAM_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.PROCESSIMPLEMENTATION_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.PROCESSINVOCATIONPARAM_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.PROCESSINVOCATION_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.PROCESSIOELEMENT_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.PROCESSIO_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.PROCESSRESULT_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.PROJECTLINK_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.PROTOCOLPARAM_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.PROTOCOL_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.QUANTIFICATIONPARAM_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.QUANTIFICATION_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.RELATEDACQUISITION_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.RELATEDQUANTIFICATION_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.STUDYASSAY_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.STUDYDESIGNASSAY_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.STUDYDESIGNDESCRIPTION_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.STUDYDESIGNTYPE_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.STUDYDESIGN_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.STUDYFACTORVALUE_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.STUDYFACTOR_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.STUDY_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.TREATMENTPARAM_SQ START WITH 1;
CREATE SEQUENCE @oracle_rad3@.TREATMENT_SQ START WITH 1;

/* 55 sequences(s) */

SPOOL OFF
SET ECHO OFF
DISCONNECT
EXIT
