
/*                                                                                            */
/* sres-sequences.sql                                                                         */
/*                                                                                            */
/* This file was generated automatically by dumpSchema.pl on Wed Feb 12 12:22:55 EST 2003     */
/*                                                                                            */

SET ECHO ON
SPOOL sres-sequences.log

CREATE SEQUENCE SRestest.ABSTRACT_SQ START WITH 1;
CREATE SEQUENCE SRestest.ANATOMYLINEAGE_SQ START WITH 1;
CREATE SEQUENCE SRestest.ANATOMY_SQ START WITH 1;
CREATE SEQUENCE SRestest.AUTHOR_SQ START WITH 1;
CREATE SEQUENCE SRestest.BIBLIOGRAPHICREFERENCE_SQ START WITH 1;
CREATE SEQUENCE SRestest.BIBREFANNOTATION_SQ START WITH 1;
CREATE SEQUENCE SRestest.BIBREFAUTHOR_SQ START WITH 1;
CREATE SEQUENCE SRestest.BIBREFTYPE_SQ START WITH 1;
CREATE SEQUENCE SRestest.CONTACT_SQ START WITH 1;
CREATE SEQUENCE SRestest.DBREF_SQ START WITH 1;
CREATE SEQUENCE SRestest.DEVELOPMENTALSTAGE_SQ START WITH 1;
CREATE SEQUENCE SRestest.DISEASE_SQ START WITH 1;
CREATE SEQUENCE SRestest.ENZYMECLASSATTRIBUTE_SQ START WITH 1;
CREATE SEQUENCE SRestest.ENZYMECLASS_SQ START WITH 1;
CREATE SEQUENCE SRestest.EXTERNALDATABASEENTRY_SQ START WITH 1;
CREATE SEQUENCE SRestest.EXTERNALDATABASEKEYWORD_SQ START WITH 1;
CREATE SEQUENCE SRestest.EXTERNALDATABASELINK_SQ START WITH 1;
CREATE SEQUENCE SRestest.EXTERNALDATABASERELEASE_SQ START WITH 1;
CREATE SEQUENCE SRestest.EXTERNALDATABASE_SQ START WITH 1;
CREATE SEQUENCE SRestest.GENETICCODE_SQ START WITH 1;
CREATE SEQUENCE SRestest.GOEVIDENCECODE_SQ START WITH 1;
CREATE SEQUENCE SRestest.GORELATIONSHIPTYPE_SQ START WITH 1;
CREATE SEQUENCE SRestest.GORELATIONSHIP_SQ START WITH 1;
CREATE SEQUENCE SRestest.GOSYNONYM_SQ START WITH 1;
CREATE SEQUENCE SRestest.GOTERM_SQ START WITH 1;
CREATE SEQUENCE SRestest.LINEAGE_SQ START WITH 1;
CREATE SEQUENCE SRestest.MGEDONTOLOGYRELATIONSHIP_SQ START WITH 1;
CREATE SEQUENCE SRestest.MGEDONTOLOGYTERM_SQ START WITH 1;
CREATE SEQUENCE SRestest.MUTAGEN_SQ START WITH 1;
CREATE SEQUENCE SRestest.ONTOLOGYRELATIONSHIPTYPE_SQ START WITH 1;
CREATE SEQUENCE SRestest.PATOATTRIBUTE_SQ START WITH 1;
CREATE SEQUENCE SRestest.PHENOTYPECLASS_SQ START WITH 1;
CREATE SEQUENCE SRestest.PHENOTYPE_SQ START WITH 1;
CREATE SEQUENCE SRestest.REFERENCE_SQ START WITH 1;
CREATE SEQUENCE SRestest.REVIEWSTATUS_SQ START WITH 1;
CREATE SEQUENCE SRestest.SEQUENCEONTOLOGY_SQ START WITH 1;
CREATE SEQUENCE SRestest.SEQUENCEREFERENCE_SQ START WITH 1;
CREATE SEQUENCE SRestest.TAXONNAME_SQ START WITH 1;
CREATE SEQUENCE SRestest.TAXON_SQ START WITH 1;

/* 39 sequences(s) */

SPOOL OFF
SET ECHO OFF
DISCONNECT
EXIT
