
/*                                                                                            */
/* sres-indexes.sql                                                                           */
/*                                                                                            */
/* This file was generated automatically by dumpSchema.pl on Wed Feb 12 12:23:17 EST 2003     */
/*                                                                                            */

SET ECHO ON
SPOOL sres-indexes.log

/* ABSTRACT */
create index SRestest.ABSTRACT_IND01 on SRestest.ABSTRACT (BIBLIOGRAPHIC_REFERENCE_ID)  TABLESPACE INDX2;

/* ANATOMY */
create index SRestest.ANATOMY_IND01 on SRestest.ANATOMY (PARENT_ID)  TABLESPACE INDX2;

/* ANATOMYLINEAGE */
create index SRestest.ANATOMYLINEAGE_IND01 on SRestest.ANATOMYLINEAGE (ANATOMY_ID)  TABLESPACE INDX2;
create index SRestest.ANATOMYLINEAGE_IND02 on SRestest.ANATOMYLINEAGE (LINEAGE_ID)  TABLESPACE INDX2;

/* AUTHOR */


/* BIBLIOGRAPHICREFERENCE */
create index SRestest.BIBLIOGRAPHICREFERENCE_IND01 on SRestest.BIBLIOGRAPHICREFERENCE (BIB_REF_TYPE_ID)  TABLESPACE INDX2;
create index SRestest.BIBLIOGRAPHICREFERENCE_IND02 on SRestest.BIBLIOGRAPHICREFERENCE (CONTACT_ID)  TABLESPACE INDX2;

/* BIBREFANNOTATION */
create index SRestest.BIBREFANNOTATION_IND01 on SRestest.BIBREFANNOTATION (BIBLIOGRAPHIC_REFERENCE_ID)  TABLESPACE INDX2;

/* BIBREFAUTHOR */
create index SRestest.BIBREFAUTHOR_IND01 on SRestest.BIBREFAUTHOR (AUTHOR_ID)  TABLESPACE INDX2;
create index SRestest.BIBREFAUTHOR_IND02 on SRestest.BIBREFAUTHOR (BIBLIOGRAPHIC_REFERENCE_ID)  TABLESPACE INDX2;

/* BIBREFTYPE */
create index SRestest.BIBREFTYPE_IND01 on SRestest.BIBREFTYPE (EXTERNAL_DATABASE_RELEASE_ID)  TABLESPACE INDX2;

/* CONTACT */
create unique index SRestest.CONTACT_AK01 on SRestest.CONTACT (NAME)  TABLESPACE INDX2;
create index SRestest.CONTACT_IND01 on SRestest.CONTACT (AFFILIATION_ID)  TABLESPACE INDX2;
create index SRestest.CONTACT_IND02 on SRestest.CONTACT (EXTERNAL_DATABASE_RELEASE_ID)  TABLESPACE INDX2;

/* DBREF */
create index SRestest.DBREF_IND01 on SRestest.DBREF (EXTERNAL_DATABASE_RELEASE_ID)  TABLESPACE INDX2;

/* DEVELOPMENTALSTAGE */
create index SRestest.DEVELOPMENTALSTAGE_IND01 on SRestest.DEVELOPMENTALSTAGE (PARENT_ID)  TABLESPACE INDX2;
create index SRestest.DEVELOPMENTALSTAGE_IND02 on SRestest.DEVELOPMENTALSTAGE (TAXON_ID)  TABLESPACE INDX2;

/* DISEASE */
create index SRestest.DISEASE_IND01 on SRestest.DISEASE (PARENT_ID)  TABLESPACE INDX2;

/* ENZYMECLASS */
create index SRestest.ENZYMECLASS_IND01 on SRestest.ENZYMECLASS (PARENT_ID)  TABLESPACE INDX2;
create index SRestest.ENZYMECLASS_IND02 on SRestest.ENZYMECLASS (EXTERNAL_DATABASE_RELEASE_ID)  TABLESPACE INDX2;

/* ENZYMECLASSATTRIBUTE */
create index SRestest.ENZYMECLASSATTRIBUTE_IND01 on SRestest.ENZYMECLASSATTRIBUTE (ENZYME_CLASS_ID)  TABLESPACE INDX2;

/* EXTERNALDATABASE */


/* EXTERNALDATABASEENTRY */
create index SRestest.EXTERNALDATABASEENTRY_IND01 on SRestest.EXTERNALDATABASEENTRY (EXTERNAL_DATABASE_RELEASE_ID)  TABLESPACE INDX2;
create index SRestest.EXTERNALDATABASEENTRY_IND02 on SRestest.EXTERNALDATABASEENTRY (REVIEW_STATUS_ID)  TABLESPACE INDX2;

/* EXTERNALDATABASEKEYWORD */
create index SRestest.EXTERNALDATABASEKEYWORD_IND01 on SRestest.EXTERNALDATABASEKEYWORD (KEYWORD_ID)  TABLESPACE INDX2;
create index SRestest.EXTERNALDATABASEKEYWORD_IND02 on SRestest.EXTERNALDATABASEKEYWORD (EXTERNAL_DATABASE_RELEASE_ID)  TABLESPACE INDX2;

/* EXTERNALDATABASELINK */
create index SRestest.EXTERNALDATABASELINK_IND01 on SRestest.EXTERNALDATABASELINK (LINK_TABLE_ID)  TABLESPACE INDX2;
create index SRestest.EXTERNALDATABASELINK_IND02 on SRestest.EXTERNALDATABASELINK (EXTERNAL_DATABASE_RELEASE_ID)  TABLESPACE INDX2;

/* EXTERNALDATABASERELEASE */
create index SRestest.EXTERNALDATABASERELEASE_IND01 on SRestest.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_ID)  TABLESPACE INDX2;

/* GENETICCODE */


/* GOEVIDENCECODE */


/* GORELATIONSHIP */
create index SRestest.GORELATIONSHIP_IND03 on SRestest.GORELATIONSHIP (GO_RELATIONSHIP_TYPE_ID)  TABLESPACE INDX2;
create index SRestest.GORELATIONSHIP_IND01 on SRestest.GORELATIONSHIP (PARENT_TERM_ID,CHILD_TERM_ID)  TABLESPACE INDX2;
create index SRestest.GORELATIONSHIP_IND02 on SRestest.GORELATIONSHIP (CHILD_TERM_ID,PARENT_TERM_ID)  TABLESPACE INDX2;

/* GORELATIONSHIPTYPE */


/* GOSYNONYM */
create index SRestest.GOSYNONYM_IND01 on SRestest.GOSYNONYM (EXTERNAL_DATABASE_RELEASE_ID)  TABLESPACE INDX2;
create index SRestest.GOSYNONYM_IND02 on SRestest.GOSYNONYM (GO_TERM_ID)  TABLESPACE INDX2;

/* GOTERM */
create index SRestest.GOTERM_IND01 on SRestest.GOTERM (EXTERNAL_DATABASE_RELEASE_ID)  TABLESPACE INDX2;
create index SRestest.GOTERM_IND02 on SRestest.GOTERM (ANCESTOR_GO_TERM_ID)  TABLESPACE INDX2;

/* LINEAGE */


/* MGEDONTOLOGYRELATIONSHIP */
create index SRestest.MGEDONTOLOGYRELATIONSHIP_IND01 on SRestest.MGEDONTOLOGYRELATIONSHIP (CHILD_TERM_ID)  TABLESPACE INDX2;
create index SRestest.MGEDONTOLOGYRELATIONSHIP_IND02 on SRestest.MGEDONTOLOGYRELATIONSHIP (PARENT_TERM_ID)  TABLESPACE INDX2;
create index SRestest.MGEDONTOLOGYRELATIONSHIP_IND03 on SRestest.MGEDONTOLOGYRELATIONSHIP (ONTOLOGY_RELATIONSHIP_TYPE_ID)  TABLESPACE INDX2;

/* MGEDONTOLOGYTERM */
create index SRestest.MGEDONTOLOGYTERM_IND01 on SRestest.MGEDONTOLOGYTERM (EXTERNAL_DATABASE_RELEASE_ID)  TABLESPACE INDX2;

/* MUTAGEN */


/* ONTOLOGYRELATIONSHIPTYPE */


/* PATOATTRIBUTE */


/* PHENOTYPE */
create index SRestest.PHENOTYPE_IND01 on SRestest.PHENOTYPE (ANATOMY_ID)  TABLESPACE INDX2;
create index SRestest.PHENOTYPE_IND02 on SRestest.PHENOTYPE (CELL_TYPE_ID)  TABLESPACE INDX2;
create index SRestest.PHENOTYPE_IND03 on SRestest.PHENOTYPE (DEVELOPMENTAL_STAGE_ID)  TABLESPACE INDX2;
create index SRestest.PHENOTYPE_IND04 on SRestest.PHENOTYPE (PARENT_ID)  TABLESPACE INDX2;
create index SRestest.PHENOTYPE_IND05 on SRestest.PHENOTYPE (PATO_ATTRIBUTE_ID)  TABLESPACE INDX2;

/* PHENOTYPECLASS */


/* REFERENCE */
create index SRestest.REFERENCE_IND01 on SRestest.REFERENCE (DB_REF_ID)  TABLESPACE INDX2;

/* REVIEWSTATUS */


/* SEQUENCEONTOLOGY */


/* SEQUENCEREFERENCE */
create index SRestest.SEQUENCEREFERENCE_IND01 on SRestest.SEQUENCEREFERENCE (BIBLIOGRAPHIC_REFERENCE_ID)  TABLESPACE INDX2;

/* TAXON */
create index SRestest.TAXON_IND01 on SRestest.TAXON (NCBI_TAX_ID)  TABLESPACE INDX2;
create index SRestest.TAXON_IND02 on SRestest.TAXON (GENETIC_CODE_ID)  TABLESPACE INDX2;
create index SRestest.TAXON_IND03 on SRestest.TAXON (MITOCHONDRIAL_GENETIC_CODE_ID)  TABLESPACE INDX2;
create index SRestest.TAXON_IND04 on SRestest.TAXON (PARENT_ID)  TABLESPACE INDX2;

/* TAXONNAME */
create index SRestest.TAXONNAME_IND01 on SRestest.TAXONNAME (TAXON_ID)  TABLESPACE INDX2;
create index SRestest.TAXONNAME_IND02 on SRestest.TAXONNAME (NAME)  TABLESPACE INDX2;
create index SRestest.TAXONNAME_IND04 on SRestest.TAXONNAME (NAME_CLASS)  TABLESPACE INDX2;



/* 52 index(es) */

SPOOL OFF
SET ECHO OFF
DISCONNECT
EXIT
