
/*                                                                                            */
/* tess-constraints.sql                                                                       */
/*                                                                                            */
/* This file was generated automatically by dumpSchema.pl on Wed Feb 12 12:28:53 EST 2003     */
/*                                                                                            */

SET ECHO ON
SPOOL tess-constraints.log

/* NON-PRIMARY KEY CONSTRAINTS */

/* ACTIVITYCONDITIONS */
alter table TESStest.ACTIVITYCONDITIONS add constraint ACTIVITYCONDITIONS_FK01 foreign key (ACTIVITY_ID) references TESStest.ACTIVITYIMP (ACTIVITY_ID);
alter table TESStest.ACTIVITYCONDITIONS add constraint ACTIVITYCONDITIONS_FK02 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);
alter table TESStest.ACTIVITYCONDITIONS add constraint ACTIVITYCONDITIONS_FK03 foreign key (TAXON_ID) references SRestest.TAXON (TAXON_ID);
alter table TESStest.ACTIVITYCONDITIONS add constraint ACTIVITYCONDITIONS_FK04 foreign key (ANATOMY_ID) references SRestest.ANATOMY (ANATOMY_ID);
alter table TESStest.ACTIVITYCONDITIONS add constraint ACTIVITYCONDITIONS_FK05 foreign key (CELL_TYPE_ID) references SRestest.ANATOMY (ANATOMY_ID);
alter table TESStest.ACTIVITYCONDITIONS add constraint ACTIVITYCONDITIONS_FK06 foreign key (DEVELOPMENTAL_STAGE_ID) references SRestest.DEVELOPMENTALSTAGE (DEVELOPMENTAL_STAGE_ID);
alter table TESStest.ACTIVITYCONDITIONS add constraint ACTIVITYCONDITIONS_FK07 foreign key (DISEASE_ID) references SRestest.DISEASE (DISEASE_ID);
alter table TESStest.ACTIVITYCONDITIONS add constraint ACTIVITYCONDITIONS_FK08 foreign key (PHENOTYPE_ID) references SRestest.PHENOTYPE (PHENOTYPE_ID);

/* ACTIVITYIMP */
alter table TESStest.ACTIVITYIMP add constraint ACTIVITYIMP_FK01 foreign key (GO_TERM_ID) references SRestest.GOTERM (GO_TERM_ID);
alter table TESStest.ACTIVITYIMP add constraint ACTIVITYIMP_FK02 foreign key (MOIETY_ID) references TESStest.MOIETYIMP (MOIETY_ID);
alter table TESStest.ACTIVITYIMP add constraint ACTIVITYIMP_FK03 foreign key (EXTERNAL_DATABASE_RELEASE_ID) references SRestest.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_RELEASE_ID);
alter table TESStest.ACTIVITYIMP add constraint ACTIVITYIMP_FK04 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);

/* ACTIVITYINFERENCESOURCE */
alter table TESStest.ACTIVITYINFERENCESOURCE add constraint ACTIVITYINFERENCESOURCE_FK01 foreign key (ACTIVITY_ID) references TESStest.ACTIVITYIMP (ACTIVITY_ID);

/* ANALYSIS */
alter table TESStest.ANALYSIS add constraint ANALYSIS_FK01 foreign key (POSITIVE_TRAINING_SET_ID) references TESStest.TRAININGSET (TRAINING_SET_ID);
alter table TESStest.ANALYSIS add constraint ANALYSIS_FK02 foreign key (NEGATIVE_TRAINING_SET_ID) references TESStest.TRAININGSET (TRAINING_SET_ID);
alter table TESStest.ANALYSIS add constraint ANALYSIS_FK03 foreign key (PROTOCOL_ID) references RAD3test.PROTOCOL (PROTOCOL_ID);
alter table TESStest.ANALYSIS add constraint ANALYSIS_FK04 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);
alter table TESStest.ANALYSIS add constraint ANALYSIS_FK05 foreign key (EXTERNAL_DATABASE_RELEASE_ID) references SRestest.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_RELEASE_ID);
alter table TESStest.ANALYSIS add constraint ANALYSIS_FK06 foreign key (PARAMETER_GROUP_ID) references TESStest.PARAMETERGROUP (PARAMETER_GROUP_ID);

/* FOOTPRINT */
alter table TESStest.FOOTPRINT add constraint FOOTPRINT_FK01 foreign key (ACTIVITY_ID) references TESStest.ACTIVITYIMP (ACTIVITY_ID);
alter table TESStest.FOOTPRINT add constraint FOOTPRINT_FK02 foreign key (NA_FEATURE_ID) references DoTStest.NAFEATUREIMP (NA_FEATURE_ID);
alter table TESStest.FOOTPRINT add constraint FOOTPRINT_FK03 foreign key (EXTERNAL_DATABASE_RELEASE_ID) references SRestest.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_RELEASE_ID);

/* FOOTPRINTMETHODPROTOCOL */
alter table TESStest.FOOTPRINTMETHODPROTOCOL add constraint FOOTPRINTMETHODPROTOCOL_FK01 foreign key (FOOTPRINT_ID) references TESStest.FOOTPRINT (FOOTPRINT_ID);
alter table TESStest.FOOTPRINTMETHODPROTOCOL add constraint FOOTPRINTMETHODPROTOCOL_FK02 foreign key (PROTOCOL_ID) references RAD3test.PROTOCOL (PROTOCOL_ID);

/* MODEL */
alter table TESStest.MODEL add constraint MODEL_FK01 foreign key (ACTIVITY_ID) references TESStest.ACTIVITYIMP (ACTIVITY_ID);
alter table TESStest.MODEL add constraint MODEL_FK02 foreign key (SBCG_GRAMMAR_ID) references TESStest.SBCGGRAMMAR (SBCG_GRAMMAR_ID);

/* MODELRESULT */
alter table TESStest.MODELRESULT add constraint MODELRESULT_FK01 foreign key (SBCG_GRAMMAR_ID) references TESStest.SBCGGRAMMAR (SBCG_GRAMMAR_ID);
alter table TESStest.MODELRESULT add constraint MODELRESULT_FK02 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);

/* MOIETYIMP */
alter table TESStest.MOIETYIMP add constraint MOIETYIMP_FK01 foreign key (EXTERNAL_DATABASE_RELEASE_ID) references SRestest.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_RELEASE_ID);
alter table TESStest.MOIETYIMP add constraint MOIETYIMP_FK02 foreign key (TAXON_ID) references SRestest.TAXON (TAXON_ID);
alter table TESStest.MOIETYIMP add constraint MOIETYIMP_FK03 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);

/* MOIETYINSTANCE */
alter table TESStest.MOIETYINSTANCE add constraint MOIETYINSTANCE_FK01 foreign key (MOIETY_ID) references TESStest.MOIETYIMP (MOIETY_ID);
alter table TESStest.MOIETYINSTANCE add constraint MOIETYINSTANCE_FK02 foreign key (DOGMA_OBJECT_TABLE_ID) references Coretest.TABLEINFO (TABLE_ID);
alter table TESStest.MOIETYINSTANCE add constraint MOIETYINSTANCE_FK03 foreign key (EXTERNAL_DATABASE_RELEASE_ID) references SRestest.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_RELEASE_ID);

/* MOIETYMEMBER */
alter table TESStest.MOIETYMEMBER add constraint MOIETYMEMBER_FK01 foreign key (WHOLE_MOIETY_ID) references TESStest.MOIETYIMP (MOIETY_ID);
alter table TESStest.MOIETYMEMBER add constraint MOIETYMEMBER_FK02 foreign key (PART_MOIETY_ID) references TESStest.MOIETYIMP (MOIETY_ID);
alter table TESStest.MOIETYMEMBER add constraint MOIETYMEMBER_FK03 foreign key (EXTERNAL_DATABASE_RELEASE_ID) references SRestest.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_RELEASE_ID);
alter table TESStest.MOIETYMEMBER add constraint MOIETYMEMBER_FK04 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);

/* MOIETYSYNONYM */
alter table TESStest.MOIETYSYNONYM add constraint MOIETYSYNONYM_FK01 foreign key (MOIETY_ID) references TESStest.MOIETYIMP (MOIETY_ID);
alter table TESStest.MOIETYSYNONYM add constraint MOIETYSYNONYM_FK02 foreign key (EXTERNAL_DATABASE_RELEASE_ID) references SRestest.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_RELEASE_ID);

/* MULTINOMIALLABEL */
alter table TESStest.MULTINOMIALLABEL add constraint MULTINOMIALLABEL_FK01 foreign key (MULTINOMIAL_LABEL_SET_ID) references TESStest.MULTINOMIALLABELSET (MULTINOMIAL_LABEL_SET_ID);

/* MULTINOMIALLABELSET */

/* MULTINOMIALOBSERVATION */
alter table TESStest.MULTINOMIALOBSERVATION add constraint MULTINOMIALOBSERVATION_FK01 foreign key (MULTINOMIAL_OBS_SET_ID) references TESStest.MULTINOMIALOBSERVATIONSET (MULTINOMIAL_OBS_SET_ID);
alter table TESStest.MULTINOMIALOBSERVATION add constraint MULTINOMIALOBSERVATION_FK02 foreign key (MULTINOMIAL_LABEL_ID) references TESStest.MULTINOMIALLABEL (MULTINOMIAL_LABEL_ID);

/* MULTINOMIALOBSERVATIONSET */
alter table TESStest.MULTINOMIALOBSERVATIONSET add constraint MULTINOMIALOBSERVATIONSET_FK01 foreign key (RECOGNITION_ID) references TESStest.SBCGRECOGNITIONIMP (SBCG_RECOGNITION_ID);
alter table TESStest.MULTINOMIALOBSERVATIONSET add constraint MULTINOMIALOBSERVATIONSET_FK02 foreign key (MULTINOMIAL_LABEL_SET_ID) references TESStest.MULTINOMIALLABELSET (MULTINOMIAL_LABEL_SET_ID);

/* NOTE */
alter table TESStest.NOTE add constraint NOTE_FK01 foreign key (TABLE_ID) references Coretest.TABLEINFO (TABLE_ID);

/* PARAMETERGROUP */
alter table TESStest.PARAMETERGROUP add constraint PARAMETERGROUP_FK01 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);

/* PARAMETERSUBGROUP */
alter table TESStest.PARAMETERSUBGROUP add constraint PARAMETERSUBGROUP_FK01 foreign key (PARENT_GROUP_ID) references TESStest.PARAMETERGROUP (PARAMETER_GROUP_ID);
alter table TESStest.PARAMETERSUBGROUP add constraint PARAMETERSUBGROUP_FK02 foreign key (CHILD_GROUP_ID) references TESStest.PARAMETERGROUP (PARAMETER_GROUP_ID);

/* PARAMETERVALUE */
alter table TESStest.PARAMETERVALUE add constraint PARAMETERVALUE_FK01 foreign key (PARAMETER_GROUP_ID) references TESStest.PARAMETERGROUP (PARAMETER_GROUP_ID);
alter table TESStest.PARAMETERVALUE add constraint PARAMETERVALUE_FK02 foreign key (TYPE_ID) references Coretest.ALGORITHMPARAMKEYTYPE (ALGORITHM_PARAM_KEY_TYPE_ID);

/* PARSERITEM */
alter table TESStest.PARSERITEM add constraint PARSERITEM_FK01 foreign key (SBCG_RECOGNITION_ID) references TESStest.SBCGRECOGNITIONIMP (SBCG_RECOGNITION_ID);
alter table TESStest.PARSERITEM add constraint PARSERITEM_FK02 foreign key (NA_FEATURE_ID) references DoTStest.NAFEATUREIMP (NA_FEATURE_ID);

/* PARSERITEMEDGETYPE */

/* PARSERITEMLINK */
alter table TESStest.PARSERITEMLINK add constraint PARSERITEMLINK_FK01 foreign key (PARENT_PARSER_ITEM_ID) references TESStest.PARSERITEM (PARSER_ITEM_ID);
alter table TESStest.PARSERITEMLINK add constraint PARSERITEMLINK_FK02 foreign key (CHILD_PARSER_ITEM_ID) references TESStest.PARSERITEM (PARSER_ITEM_ID);
alter table TESStest.PARSERITEMLINK add constraint PARSERITEMLINK_FK03 foreign key (PARSER_ITEM_EDGE_TYPE_ID) references TESStest.PARSERITEMEDGETYPE (PARSER_ITEM_EDGE_TYPE_ID);

/* PREDICTIONRESULT */
alter table TESStest.PREDICTIONRESULT add constraint PREDICTIONRESULT_FK01 foreign key (SBCG_GRAMMAR_ID) references TESStest.SBCGGRAMMAR (SBCG_GRAMMAR_ID);
alter table TESStest.PREDICTIONRESULT add constraint PREDICTIONRESULT_FK02 foreign key (FOOTPRINT_ID) references TESStest.FOOTPRINT (FOOTPRINT_ID);
alter table TESStest.PREDICTIONRESULT add constraint PREDICTIONRESULT_FK03 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);

/* SBCGANNOTATIONFILTER */
alter table TESStest.SBCGANNOTATIONFILTER add constraint SBCGANNOTATIONFILTER_FK01 foreign key (SBCG_RECOG_PATH_EXPRESSION_ID) references TESStest.SBCGRECOGNITIONIMP (SBCG_RECOGNITION_ID);
alter table TESStest.SBCGANNOTATIONFILTER add constraint SBCGANNOTATIONFILTER_FK02 foreign key (SBCG_PATH_TERM_REL_TYPE_ID) references TESStest.SBCGPATHTERMRELATIONTYPE (SBCG_PATH_TERM_REL_TYPE_ID);

/* SBCGANNOTATIONFILTERTERM */
alter table TESStest.SBCGANNOTATIONFILTERTERM add constraint SBCGANNOTATIONFILTERTERM_FK01 foreign key (SBCG_ANNOTATION_FILTER_ID) references TESStest.SBCGANNOTATIONFILTER (SBCG_ANNOTATION_FILTER_ID);
alter table TESStest.SBCGANNOTATIONFILTERTERM add constraint SBCGANNOTATIONFILTERTERM_FK02 foreign key (SBCG_COMPARISON_TYPE_ID) references TESStest.SBCGCOMPARISONTYPE (SBCG_COMPARISON_TYPE_ID);

/* SBCGANNOTATIONGUIDE */
alter table TESStest.SBCGANNOTATIONGUIDE add constraint SBCGANNOTATIONGUIDE_FK01 foreign key (SBCG_GRAMMAR_ID) references TESStest.SBCGGRAMMAR (SBCG_GRAMMAR_ID);

/* SBCGCOMPARISONTYPE */

/* SBCGGRAMMAR */
alter table TESStest.SBCGGRAMMAR add constraint SBCGGRAMMAR_FK01 foreign key (EXTERNAL_DATABASE_RELEASE_ID) references SRestest.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_RELEASE_ID);
alter table TESStest.SBCGGRAMMAR add constraint SBCGGRAMMAR_FK02 foreign key (BEST_PRACTICE_TEST_COND_ID) references TESStest.PARAMETERGROUP (PARAMETER_GROUP_ID);
alter table TESStest.SBCGGRAMMAR add constraint SBCGGRAMMAR_FK03 foreign key (REVIEW_STATUS_ID) references SRestest.REVIEWSTATUS (REVIEW_STATUS_ID);

/* SBCGNONTERMINAL */
alter table TESStest.SBCGNONTERMINAL add constraint SBCGNONTERMINAL_FK01 foreign key (SBGC_GRAMMAR_ID) references TESStest.SBCGGRAMMAR (SBCG_GRAMMAR_ID);

/* SBCGPATHTERMRELATIONTYPE */

/* SBCGPRODUCTION */
alter table TESStest.SBCGPRODUCTION add constraint SBCGPRODUCTION_FK01 foreign key (SBGC_GRAMMAR_ID) references TESStest.SBCGGRAMMAR (SBCG_GRAMMAR_ID);
alter table TESStest.SBCGPRODUCTION add constraint SBCGPRODUCTION_FK02 foreign key (SBCG_NONTERMINAL_ID) references TESStest.SBCGNONTERMINAL (SBCG_NONTERMINAL_ID);
alter table TESStest.SBCGPRODUCTION add constraint SBCGPRODUCTION_FK03 foreign key (SBCG_PRODUCTION_TYPE_ID) references TESStest.SBCGPRODUCTIONTYPE (SBCG_PRODUCTION_TYPE_ID);
alter table TESStest.SBCGPRODUCTION add constraint SBCGPRODUCTION_FK04 foreign key (SBCG_ANNOTATION_GUIDE_ID) references TESStest.SBCGANNOTATIONGUIDE (SBCG_ANNOTATION_GUIDE_ID);
alter table TESStest.SBCGPRODUCTION add constraint SBCGPRODUCTION_FK05 foreign key (SBCG_PATH_BOUND_ID) references TESStest.SBCGRECOGNITIONIMP (SBCG_RECOGNITION_ID);

/* SBCGPRODUCTIONTYPE */

/* SBCGRECOGNITIONIMP */
alter table TESStest.SBCGRECOGNITIONIMP add constraint SBCGRECOGNITIONIMP_FK01 foreign key (SBCG_GRAMMAR_ID) references TESStest.SBCGGRAMMAR (SBCG_GRAMMAR_ID);
alter table TESStest.SBCGRECOGNITIONIMP add constraint SBCGRECOGNITIONIMP_FK02 foreign key (SBCG_NONTERMINAL_ID) references TESStest.SBCGNONTERMINAL (SBCG_NONTERMINAL_ID);
alter table TESStest.SBCGRECOGNITIONIMP add constraint SBCGRECOGNITIONIMP_FK03 foreign key (SBCG_STREAM_ID) references TESStest.SBCGSTREAM (SBCG_STREAM_ID);
alter table TESStest.SBCGRECOGNITIONIMP add constraint SBCGRECOGNITIONIMP_FK04 foreign key (PARENT_SBCG_RECOGNITION_ID) references TESStest.SBCGRECOGNITIONIMP (SBCG_RECOGNITION_ID);

/* SBCGRHSTERM */
alter table TESStest.SBCGRHSTERM add constraint SBCGRHSTERM_FK01 foreign key (SBCG_PRODUCTION_ID) references TESStest.SBCGPRODUCTION (SBCG_PRODUCTION_ID);
alter table TESStest.SBCGRHSTERM add constraint SBCGRHSTERM_FK02 foreign key (SBCG_RECOGNITION_ID) references TESStest.SBCGRECOGNITIONIMP (SBCG_RECOGNITION_ID);
alter table TESStest.SBCGRHSTERM add constraint SBCGRHSTERM_FK03 foreign key (SBCG_ANNOTATION_GUIDE_ID) references TESStest.SBCGANNOTATIONGUIDE (SBCG_ANNOTATION_GUIDE_ID);

/* SBCGSTREAM */
alter table TESStest.SBCGSTREAM add constraint SBCGSTREAM_FK01 foreign key (SBCG_GRAMMAR_ID) references TESStest.SBCGGRAMMAR (SBCG_GRAMMAR_ID);

/* SBCGSTREAMPARAMETER */
alter table TESStest.SBCGSTREAMPARAMETER add constraint SBCGSTREAMPARAMETER_FK01 foreign key (SBCG_STREAM_ID) references TESStest.SBCGSTREAM (SBCG_STREAM_ID);

/* TRAININGSET */
alter table TESStest.TRAININGSET add constraint TRAININGSET_FK01 foreign key (ACTIVITY_ID) references TESStest.ACTIVITYIMP (ACTIVITY_ID);

/* TRAININGSETMEMBER */
alter table TESStest.TRAININGSETMEMBER add constraint TRAININGSETMEMBER_FK01 foreign key (TRAINING_SET_ID) references TESStest.TRAININGSET (TRAINING_SET_ID);
alter table TESStest.TRAININGSETMEMBER add constraint TRAININGSETMEMBER_FK02 foreign key (FOOTPRINT_ID) references TESStest.FOOTPRINT (FOOTPRINT_ID);



/* 85 non-primary key constraint(s) */

SPOOL OFF
SET ECHO OFF
DISCONNECT
EXIT
