
/*                                                                                            */
/* tess-sequences.sql                                                                         */
/*                                                                                            */
/* This file was generated automatically by dumpSchema.pl on Wed Feb 12 03:58:53 EST 2003     */
/*                                                                                            */

SET ECHO ON
SPOOL tess-sequences.log

CREATE SEQUENCE @oracle_tess@.ACTIVITYCONDITIONS_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.ACTIVITYIMP_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.ACTIVITYINFERENCESOURCE_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.ANALYSIS_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.FOOTPRINTMETHODPROTOCOL_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.FOOTPRINT_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.MODELRESULT_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.MODEL_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.MOIETYIMP_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.MOIETYINSTANCE_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.MOIETYMEMBER_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.MOIETYSYNONYM_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.MULTINOMIALLABELSET_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.MULTINOMIALLABEL_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.MULTINOMIALOBSERVATIONSET_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.MULTINOMIALOBSERVATION_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.MULTINOMIAL_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.NOTE_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.PARAMETERGROUP_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.PARAMETERSUBGROUP_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.PARAMETERVALUE_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.PARSERITEMEDGETYPE_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.PARSERITEMLINK_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.PARSERITEM_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.PREDICTIONRESULT_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.SBCGANNOTATIONFILTERTERM_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.SBCGANNOTATIONFILTER_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.SBCGANNOTATIONGUIDE_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.SBCGCOMPARISONTYPE_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.SBCGGRAMMAR_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.SBCGNONTERMINAL_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.SBCGPATHTERMRELATIONTYPE_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.SBCGPRODUCTIONTYPE_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.SBCGPRODUCTION_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.SBCGRECOGNITIONIMP_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.SBCGRHSTERM_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.SBCGSTREAMPARAMETER_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.SBCGSTREAM_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.TRAININGSETMEMBER_SQ START WITH 1;
CREATE SEQUENCE @oracle_tess@.TRAININGSET_SQ START WITH 1;

/* 40 sequences(s) */

SPOOL OFF
SET ECHO OFF
DISCONNECT
EXIT
