
/*                                                                                            */
/* tess-sequences.sql                                                                         */
/*                                                                                            */
/* This file was generated automatically by dumpSchema.pl on Wed Feb 12 12:28:25 EST 2003     */
/*                                                                                            */

SET ECHO ON
SPOOL tess-sequences.log

CREATE SEQUENCE TESStest.ACTIVITYCONDITIONS_SQ START WITH 1;
CREATE SEQUENCE TESStest.ACTIVITYIMP_SQ START WITH 1;
CREATE SEQUENCE TESStest.ACTIVITYINFERENCESOURCE_SQ START WITH 1;
CREATE SEQUENCE TESStest.ANALYSIS_SQ START WITH 1;
CREATE SEQUENCE TESStest.FOOTPRINTMETHODPROTOCOL_SQ START WITH 1;
CREATE SEQUENCE TESStest.FOOTPRINT_SQ START WITH 1;
CREATE SEQUENCE TESStest.MODELRESULT_SQ START WITH 1;
CREATE SEQUENCE TESStest.MODEL_SQ START WITH 1;
CREATE SEQUENCE TESStest.MOIETYIMP_SQ START WITH 1;
CREATE SEQUENCE TESStest.MOIETYINSTANCE_SQ START WITH 1;
CREATE SEQUENCE TESStest.MOIETYMEMBER_SQ START WITH 1;
CREATE SEQUENCE TESStest.MOIETYSYNONYM_SQ START WITH 1;
CREATE SEQUENCE TESStest.MULTINOMIALLABELSET_SQ START WITH 1;
CREATE SEQUENCE TESStest.MULTINOMIALLABEL_SQ START WITH 1;
CREATE SEQUENCE TESStest.MULTINOMIALOBSERVATIONSET_SQ START WITH 1;
CREATE SEQUENCE TESStest.MULTINOMIALOBSERVATION_SQ START WITH 1;
CREATE SEQUENCE TESStest.MULTINOMIAL_SQ START WITH 1;
CREATE SEQUENCE TESStest.NOTE_SQ START WITH 1;
CREATE SEQUENCE TESStest.PARAMETERGROUP_SQ START WITH 1;
CREATE SEQUENCE TESStest.PARAMETERSUBGROUP_SQ START WITH 1;
CREATE SEQUENCE TESStest.PARAMETERVALUE_SQ START WITH 1;
CREATE SEQUENCE TESStest.PARSERITEMEDGETYPE_SQ START WITH 1;
CREATE SEQUENCE TESStest.PARSERITEMLINK_SQ START WITH 1;
CREATE SEQUENCE TESStest.PARSERITEM_SQ START WITH 1;
CREATE SEQUENCE TESStest.PREDICTIONRESULT_SQ START WITH 1;
CREATE SEQUENCE TESStest.SBCGANNOTATIONFILTERTERM_SQ START WITH 1;
CREATE SEQUENCE TESStest.SBCGANNOTATIONFILTER_SQ START WITH 1;
CREATE SEQUENCE TESStest.SBCGANNOTATIONGUIDE_SQ START WITH 1;
CREATE SEQUENCE TESStest.SBCGCOMPARISONTYPE_SQ START WITH 1;
CREATE SEQUENCE TESStest.SBCGGRAMMAR_SQ START WITH 1;
CREATE SEQUENCE TESStest.SBCGNONTERMINAL_SQ START WITH 1;
CREATE SEQUENCE TESStest.SBCGPATHTERMRELATIONTYPE_SQ START WITH 1;
CREATE SEQUENCE TESStest.SBCGPRODUCTIONTYPE_SQ START WITH 1;
CREATE SEQUENCE TESStest.SBCGPRODUCTION_SQ START WITH 1;
CREATE SEQUENCE TESStest.SBCGRECOGNITIONIMP_SQ START WITH 1;
CREATE SEQUENCE TESStest.SBCGRHSTERM_SQ START WITH 1;
CREATE SEQUENCE TESStest.SBCGSTREAMPARAMETER_SQ START WITH 1;
CREATE SEQUENCE TESStest.SBCGSTREAM_SQ START WITH 1;
CREATE SEQUENCE TESStest.TRAININGSETMEMBER_SQ START WITH 1;
CREATE SEQUENCE TESStest.TRAININGSET_SQ START WITH 1;

/* 40 sequences(s) */

SPOOL OFF
SET ECHO OFF
DISCONNECT
EXIT
