
/*                                                                                            */
/* tess-indexes.sql                                                                           */
/*                                                                                            */
/* This file was generated automatically by dumpSchema.pl on Wed Feb 12 12:28:53 EST 2003     */
/*                                                                                            */

SET ECHO ON
SPOOL tess-indexes.log

/* ACTIVITYCONDITIONS */
create index TESStest.ACTIVITYCONDITIONS_IND01 on TESStest.ACTIVITYCONDITIONS (ACTIVITY_ID)  TABLESPACE INDX2;
create index TESStest.ACTIVITYCONDITIONS_IND02 on TESStest.ACTIVITYCONDITIONS (REVIEW_STATUS_ID)  TABLESPACE INDX2;
create index TESStest.ACTIVITYCONDITIONS_IND03 on TESStest.ACTIVITYCONDITIONS (TAXON_ID)  TABLESPACE INDX2;
create index TESStest.ACTIVITYCONDITIONS_IND04 on TESStest.ACTIVITYCONDITIONS (ANATOMY_ID)  TABLESPACE INDX2;
create index TESStest.ACTIVITYCONDITIONS_IND05 on TESStest.ACTIVITYCONDITIONS (CELL_TYPE_ID)  TABLESPACE INDX2;
create index TESStest.ACTIVITYCONDITIONS_IND06 on TESStest.ACTIVITYCONDITIONS (DEVELOPMENTAL_STAGE_ID)  TABLESPACE INDX2;
create index TESStest.ACTIVITYCONDITIONS_IND07 on TESStest.ACTIVITYCONDITIONS (DISEASE_ID)  TABLESPACE INDX2;
create index TESStest.ACTIVITYCONDITIONS_IND08 on TESStest.ACTIVITYCONDITIONS (PHENOTYPE_ID)  TABLESPACE INDX2;

/* ACTIVITYIMP */
create index TESStest.ACTIVITYIMP_IND01 on TESStest.ACTIVITYIMP (GO_TERM_ID)  TABLESPACE INDX2;
create index TESStest.ACTIVITYIMP_IND02 on TESStest.ACTIVITYIMP (MOIETY_ID)  TABLESPACE INDX2;
create index TESStest.ACTIVITYIMP_IND03 on TESStest.ACTIVITYIMP (EXTERNAL_DATABASE_RELEASE_ID)  TABLESPACE INDX2;
create index TESStest.ACTIVITYIMP_IND04 on TESStest.ACTIVITYIMP (REVIEW_STATUS_ID)  TABLESPACE INDX2;

/* ACTIVITYINFERENCESOURCE */
create index TESStest.ACTIVITYINFERENCESOURCE_IND01 on TESStest.ACTIVITYINFERENCESOURCE (ACTIVITY_ID)  TABLESPACE INDX2;

/* ANALYSIS */
create index TESStest.ANALYSIS_IND01 on TESStest.ANALYSIS (POSITIVE_TRAINING_SET_ID)  TABLESPACE INDX2;
create index TESStest.ANALYSIS_IND02 on TESStest.ANALYSIS (NEGATIVE_TRAINING_SET_ID)  TABLESPACE INDX2;
create index TESStest.ANALYSIS_IND03 on TESStest.ANALYSIS (PROTOCOL_ID)  TABLESPACE INDX2;
create index TESStest.ANALYSIS_IND04 on TESStest.ANALYSIS (REVIEW_STATUS_ID)  TABLESPACE INDX2;
create index TESStest.ANALYSIS_IND05 on TESStest.ANALYSIS (EXTERNAL_DATABASE_RELEASE_ID)  TABLESPACE INDX2;
create index TESStest.ANALYSIS_IND06 on TESStest.ANALYSIS (PARAMETER_GROUP_ID)  TABLESPACE INDX2;

/* FOOTPRINT */
create index TESStest.FOOTPRINT_IND01 on TESStest.FOOTPRINT (ACTIVITY_ID)  TABLESPACE INDX2;
create index TESStest.FOOTPRINT_IND02 on TESStest.FOOTPRINT (NA_FEATURE_ID)  TABLESPACE INDX2;
create index TESStest.FOOTPRINT_IND03 on TESStest.FOOTPRINT (EXTERNAL_DATABASE_RELEASE_ID)  TABLESPACE INDX2;

/* FOOTPRINTMETHODPROTOCOL */
create index TESStest.FOOTPRINTMETHODPROTOCOL_IND01 on TESStest.FOOTPRINTMETHODPROTOCOL (FOOTPRINT_ID)  TABLESPACE INDX2;
create index TESStest.FOOTPRINTMETHODPROTOCOL_IND02 on TESStest.FOOTPRINTMETHODPROTOCOL (PROTOCOL_ID)  TABLESPACE INDX2;

/* MODEL */
create index TESStest.MODEL_IND01 on TESStest.MODEL (ACTIVITY_ID)  TABLESPACE INDX2;
create index TESStest.MODEL_IND02 on TESStest.MODEL (SBCG_GRAMMAR_ID)  TABLESPACE INDX2;

/* MODELRESULT */
create index TESStest.MODELRESULT_IND01 on TESStest.MODELRESULT (SBCG_GRAMMAR_ID)  TABLESPACE INDX2;
create index TESStest.MODELRESULT_IND02 on TESStest.MODELRESULT (REVIEW_STATUS_ID)  TABLESPACE INDX2;

/* MOIETYIMP */
create index TESStest.MOIETYIMP_IND01 on TESStest.MOIETYIMP (EXTERNAL_DATABASE_RELEASE_ID)  TABLESPACE INDX2;
create index TESStest.MOIETYIMP_IND02 on TESStest.MOIETYIMP (TAXON_ID)  TABLESPACE INDX2;
create index TESStest.MOIETYIMP_IND03 on TESStest.MOIETYIMP (REVIEW_STATUS_ID)  TABLESPACE INDX2;

/* MOIETYINSTANCE */
create index TESStest.MOIETYINSTANCE_IND01 on TESStest.MOIETYINSTANCE (MOIETY_ID)  TABLESPACE INDX2;
create index TESStest.MOIETYINSTANCE_IND02 on TESStest.MOIETYINSTANCE (DOGMA_OBJECT_TABLE_ID)  TABLESPACE INDX2;
create index TESStest.MOIETYINSTANCE_IND03 on TESStest.MOIETYINSTANCE (EXTERNAL_DATABASE_RELEASE_ID)  TABLESPACE INDX2;

/* MOIETYMEMBER */
create index TESStest.MOIETYMEMBER_IND01 on TESStest.MOIETYMEMBER (WHOLE_MOIETY_ID)  TABLESPACE INDX2;
create index TESStest.MOIETYMEMBER_IND02 on TESStest.MOIETYMEMBER (PART_MOIETY_ID)  TABLESPACE INDX2;
create index TESStest.MOIETYMEMBER_IND03 on TESStest.MOIETYMEMBER (EXTERNAL_DATABASE_RELEASE_ID)  TABLESPACE INDX2;
create index TESStest.MOIETYMEMBER_IND04 on TESStest.MOIETYMEMBER (REVIEW_STATUS_ID)  TABLESPACE INDX2;

/* MOIETYSYNONYM */
create index TESStest.MOIETYSYNONYM_IND01 on TESStest.MOIETYSYNONYM (MOIETY_ID)  TABLESPACE INDX2;
create index TESStest.MOIETYSYNONYM_IND02 on TESStest.MOIETYSYNONYM (EXTERNAL_DATABASE_RELEASE_ID)  TABLESPACE INDX2;

/* MULTINOMIALLABEL */
create index TESStest.MULTINOMIALLABEL_IND01 on TESStest.MULTINOMIALLABEL (MULTINOMIAL_LABEL_SET_ID)  TABLESPACE INDX2;

/* MULTINOMIALLABELSET */


/* MULTINOMIALOBSERVATION */
create index TESStest.MULTINOMIALOBSERVATION_IND01 on TESStest.MULTINOMIALOBSERVATION (MULTINOMIAL_OBS_SET_ID)  TABLESPACE INDX2;
create index TESStest.MULTINOMIALOBSERVATION_IND02 on TESStest.MULTINOMIALOBSERVATION (MULTINOMIAL_LABEL_ID)  TABLESPACE INDX2;

/* MULTINOMIALOBSERVATIONSET */
create index TESStest.MULTINOMIALOBSSET_IND01 on TESStest.MULTINOMIALOBSERVATIONSET (RECOGNITION_ID)  TABLESPACE INDX2;
create index TESStest.MULTINOMIALOBSSET_IND02 on TESStest.MULTINOMIALOBSERVATIONSET (MULTINOMIAL_LABEL_SET_ID)  TABLESPACE INDX2;

/* NOTE */
create index TESStest.NOTE_IND01 on TESStest.NOTE (TABLE_ID)  TABLESPACE INDX2;

/* PARAMETERGROUP */
create index TESStest.PARAMETERGROUP_IND01 on TESStest.PARAMETERGROUP (REVIEW_STATUS_ID)  TABLESPACE INDX2;

/* PARAMETERSUBGROUP */
create index TESStest.PARAMETERSUBGROUP_IND01 on TESStest.PARAMETERSUBGROUP (PARENT_GROUP_ID)  TABLESPACE INDX2;
create index TESStest.PARAMETERSUBGROUP_IND02 on TESStest.PARAMETERSUBGROUP (CHILD_GROUP_ID)  TABLESPACE INDX2;

/* PARAMETERVALUE */
create index TESStest.PARAMETERVALUE_IND01 on TESStest.PARAMETERVALUE (PARAMETER_GROUP_ID)  TABLESPACE INDX2;
create index TESStest.PARAMETERVALUE_IND02 on TESStest.PARAMETERVALUE (TYPE_ID)  TABLESPACE INDX2;

/* PARSERITEM */
create index TESStest.PARSERITEM_IND01 on TESStest.PARSERITEM (SBCG_RECOGNITION_ID)  TABLESPACE INDX2;
create index TESStest.PARSERITEM_IND02 on TESStest.PARSERITEM (NA_FEATURE_ID)  TABLESPACE INDX2;

/* PARSERITEMEDGETYPE */


/* PARSERITEMLINK */
create index TESStest.PARSERITEMLINK_IND01 on TESStest.PARSERITEMLINK (PARENT_PARSER_ITEM_ID)  TABLESPACE INDX2;
create index TESStest.PARSERITEMLINK_IND02 on TESStest.PARSERITEMLINK (CHILD_PARSER_ITEM_ID)  TABLESPACE INDX2;
create index TESStest.PARSERITEMLINK_IND03 on TESStest.PARSERITEMLINK (PARSER_ITEM_EDGE_TYPE_ID)  TABLESPACE INDX2;

/* PREDICTIONRESULT */
create index TESStest.PREDICTIONRESULT_IND01 on TESStest.PREDICTIONRESULT (SBCG_GRAMMAR_ID)  TABLESPACE INDX2;
create index TESStest.PREDICTIONRESULT_IND02 on TESStest.PREDICTIONRESULT (FOOTPRINT_ID)  TABLESPACE INDX2;
create index TESStest.PREDICTIONRESULT_IND03 on TESStest.PREDICTIONRESULT (REVIEW_STATUS_ID)  TABLESPACE INDX2;

/* SBCGANNOTATIONFILTER */
create index TESStest.SBCGANNOTATIONFILTER_IND01 on TESStest.SBCGANNOTATIONFILTER (SBCG_RECOG_PATH_EXPRESSION_ID)  TABLESPACE INDX2;
create index TESStest.SBCGANNOTATIONFILTER_IND02 on TESStest.SBCGANNOTATIONFILTER (SBCG_PATH_TERM_REL_TYPE_ID)  TABLESPACE INDX2;

/* SBCGANNOTATIONFILTERTERM */
create index TESStest.SBCGANNOTATIONFILTERTERM_IND01 on TESStest.SBCGANNOTATIONFILTERTERM (SBCG_ANNOTATION_FILTER_ID)  TABLESPACE INDX2;
create index TESStest.SBCGANNOTATIONFILTERTERM_IND02 on TESStest.SBCGANNOTATIONFILTERTERM (SBCG_COMPARISON_TYPE_ID)  TABLESPACE INDX2;

/* SBCGANNOTATIONGUIDE */
create index TESStest.SBCGANNOTATIONGUIDE_IND01 on TESStest.SBCGANNOTATIONGUIDE (SBCG_GRAMMAR_ID)  TABLESPACE INDX2;

/* SBCGCOMPARISONTYPE */


/* SBCGGRAMMAR */
create index TESStest.SBCGGRAMMAR_IND01 on TESStest.SBCGGRAMMAR (EXTERNAL_DATABASE_RELEASE_ID)  TABLESPACE INDX2;
create index TESStest.SBCGGRAMMAR_IND02 on TESStest.SBCGGRAMMAR (BEST_PRACTICE_TEST_COND_ID)  TABLESPACE INDX2;
create index TESStest.SBCGGRAMMAR_IND03 on TESStest.SBCGGRAMMAR (REVIEW_STATUS_ID)  TABLESPACE INDX2;

/* SBCGNONTERMINAL */
create index TESStest.SBCGNONTERMINAL_IND01 on TESStest.SBCGNONTERMINAL (SBGC_GRAMMAR_ID)  TABLESPACE INDX2;

/* SBCGPATHTERMRELATIONTYPE */


/* SBCGPRODUCTION */
create index TESStest.SBCGPRODUCTION_IND01 on TESStest.SBCGPRODUCTION (SBGC_GRAMMAR_ID)  TABLESPACE INDX2;
create index TESStest.SBCGPRODUCTION_IND02 on TESStest.SBCGPRODUCTION (SBCG_NONTERMINAL_ID)  TABLESPACE INDX2;
create index TESStest.SBCGPRODUCTION_IND03 on TESStest.SBCGPRODUCTION (SBCG_PRODUCTION_TYPE_ID)  TABLESPACE INDX2;
create index TESStest.SBCGPRODUCTION_IND04 on TESStest.SBCGPRODUCTION (SBCG_ANNOTATION_GUIDE_ID)  TABLESPACE INDX2;
create index TESStest.SBCGPRODUCTION_IND05 on TESStest.SBCGPRODUCTION (SBCG_PATH_BOUND_ID)  TABLESPACE INDX2;

/* SBCGPRODUCTIONTYPE */


/* SBCGRECOGNITIONIMP */
create index TESStest.SBCGRECOGNITIONIMP_IND01 on TESStest.SBCGRECOGNITIONIMP (SBCG_GRAMMAR_ID)  TABLESPACE INDX2;
create index TESStest.SBCGRECOGNITIONIMP_IND02 on TESStest.SBCGRECOGNITIONIMP (SBCG_NONTERMINAL_ID)  TABLESPACE INDX2;
create index TESStest.SBCGRECOGNITIONIMP_IND03 on TESStest.SBCGRECOGNITIONIMP (SBCG_STREAM_ID)  TABLESPACE INDX2;
create index TESStest.SBCGRECOGNITIONIMP_IND04 on TESStest.SBCGRECOGNITIONIMP (PARENT_SBCG_RECOGNITION_ID)  TABLESPACE INDX2;

/* SBCGRHSTERM */
create index TESStest.SBCGRHSTERM_IND01 on TESStest.SBCGRHSTERM (SBCG_PRODUCTION_ID)  TABLESPACE INDX2;
create index TESStest.SBCGRHSTERM_IND02 on TESStest.SBCGRHSTERM (SBCG_RECOGNITION_ID)  TABLESPACE INDX2;
create index TESStest.SBCGRHSTERM_IND03 on TESStest.SBCGRHSTERM (SBCG_ANNOTATION_GUIDE_ID)  TABLESPACE INDX2;

/* SBCGSTREAM */
create index TESStest.SBCGSTREAM_IND01 on TESStest.SBCGSTREAM (SBCG_GRAMMAR_ID)  TABLESPACE INDX2;

/* SBCGSTREAMPARAMETER */
create index TESStest.SBCGSTREAMPARAMETER_IND01 on TESStest.SBCGSTREAMPARAMETER (SBCG_STREAM_ID)  TABLESPACE INDX2;

/* TRAININGSET */
create index TESStest.TRAININGSET_IND01 on TESStest.TRAININGSET (ACTIVITY_ID)  TABLESPACE INDX2;

/* TRAININGSETMEMBER */
create index TESStest.TRAININGSETMEMBER_IND01 on TESStest.TRAININGSETMEMBER (TRAINING_SET_ID)  TABLESPACE INDX2;
create index TESStest.TRAININGSETMEMBER_IND02 on TESStest.TRAININGSETMEMBER (FOOTPRINT_ID)  TABLESPACE INDX2;



/* 85 index(es) */

SPOOL OFF
SET ECHO OFF
DISCONNECT
EXIT
