package edu.upenn.cbil.limpopo.model;

public enum SDRFNodeNames {
  SAMPLENAME,
  SOURCENAME,
  EXTRACTNAME,
  LABELEXTRACTNAME,
  ASSAYNAME,
  SCANNAME,
  NORMALIZATIONNAME,
  ARRAYDATAFILE,
  DERIVEDARRAYDATAFILE,
  ARRAYDATAMATRIXFILE,
  DERIVEDARRAYDATAMATRIXFILE,
  IMAGEFILE;
}
