package GUS::ObjRelP::Generator::PerlWrapperGenerator;

@ISA = qw (GUS::ObjRelP::Generator::WrapperGenerator);

use strict;

sub new{
    my ($class, $generator, $schemaName, $tableName, $tableGenerator) = @_;
    
    my $self=GUS::ObjRelP::Generator::WrapperGenerator->new($generator, $schemaName, $tableName, $tableGenerator);
    bless $self, $class;
    return $self;
}

sub generate {
  my($self, $newOnly) = @_;

  my $dir = $self->{generator}->{targetDir};

  my $file = "$dir/$self->{schemaName}/$self->{tableName}.pm";

  return if ($newOnly && -e $file);

  if (-e "$file.man") {
    system("cp $file.man $file") == 0 || die "Couldn't cp $file.man $file";
  } else {
    open(F,">$file") || die "Can't open file $file for writing";
    print F $self->_genHeader() . "1;\n\n";
    close(F);
    }
}

sub _genHeader {
  my ( $self ) = @_;

  my $rowclass = "GUS::Model::$self->{fullName}_Row";

  my $temp .= "
package GUS::Model::$self->{fullName};

# THIS CLASS HAS BEEN AUTOMATICALLY GENERATED BY THE GUS::ObjRelP::Generator 
# PACKAGE.
#
# DO NOT EDIT!!

# TO ADD FUNCTIONALITY MANUALLY, COPY THIS FILE TO $self->{tableName}.pm.man
# (or edit that file if it already exists) AND ADD THE FUNCTIONALITY THERE.
# THEN RE-GENERATE THE GUS OBJECTS.

use strict;
use $rowclass;



use vars qw \(\@ISA\);
\@ISA = qw \($rowclass\);


";
  return $temp;
}

1;
