<?php include("header.php"); ?>

<h2>Overview</h2>
  <P>
The Genomics Unified Schema (GUS) is an extensive relational database schema and associated application framework designed to store, integrate, analyze and present functional genomics data.  The GUS schema supports a wide range of data types including genomics, gene expression, transcript assemblies, proteomics and others.  It emphasizes standards-based ontologies and strong-typing.
 </P>
 <P>
The GUS Application Framework offers an object-relational layer and a Plugin API used to rapidly create robust data loading programs for diverse data sources.  The GUS distribution includes plugins for standard data sources.  The GUS Web Development Kit (WDK) is a rich environment for efficiently designing sophisticated query-based websites with little programming required.
 </P>
		  
<h2>Groups Using GUS</h2>
    <ul>
<li><strong><a href="http://www.genedb.org">GeneDB</a></strong> -- Houses the pathogen sequences and annotation generated by PSU -- Pathogen Sequencing Unit (PSU), Wellcome Trust Sanger Institute</li>
<li><strong><a href="http://www.tcruzidb.org">TcruziDB</a></strong>, <a href="http://www.cryptodb.org">CryptoDB</a> -- Storing and analyzing data for Trypanosoma cruzi, Cryptosporidium parvum and Perkinsus marinus, and a comparative genomics database for apicomplexan parasites called ApiDB</li>
<li><strong>Centromere Analysis System</strong> -- An investigation of centromere structure and function in plants.  Stores sequence data produced locally, warehouses public data for analysis and store analysis results along with the primary sequence data -- Pruess Lab, University of Chicago and Terry Clark, University of Kansas</li>
<li><strong>Phytophthora Genome Project</strong> -- Releasing the 30,000 EST sequences and 8x genome sequences of P.sojae and provide complete annotation to the user community.  It also provides an annotator's interface. -- Virginia Bioinformatics Institute (VBI) and the DOE Joint Genome Institute</li>
<li><strong>Microarray and QTL Dissection of Quantitative Resistance in Soybean Against P.sojae</strong> -- Analyzing the P.sojae infection and quantitative resistance in Soybean plants with microarray and QTL techniques. -- VBI and Ohio State</li>
<li><strong>Cross-kingdom comparative genomics of pathogens, including Phytophtora and malaria</strong> -- Currently the project is comparing the oxidative stress response in organisms from four different kingdoms, yeast (fungi), Arabidopsis (plants), Phytophthora (oomycetes) and malaria (apicomplexans) in order to learn rules for cross-kingdom comparative genomics. -- VBI</li>
<li><strong>MLB-platform, and open soruce platform for environmental genomics</strong> -- Interfacing GUS to the ERFE-SVM system for predictive classification of microarray data.  Using the GUS schema to provide the experimental microarray data descriptions and phenotype information to covariate with the visual and numerical procedures for subsample and outlier detection.  GIS visualization and analysis will also be developed, based on our open source GIS GRASS system. -- MPBA group of the ITC-irst, Trento, Italy</li>
<li><strong><a href="http://www.biowebdb.org">BiowebDB</a></strong> -- A comparative genomics and transcriptomics project aiming to complement GeneDB and TcruziDB, providing a function genomics resource for Trypansoma cruzi, Leishmania brasiliensis and Triatomine. -- Instituto Oswaldo Cruz</li>
<li><strong>Penn Bioinformatics Core Facility</strong> -- University of Pennsylvania</li>
<li><strong>John Maris</strong> -- Studying Array CGH data -- Children's Hospital of Pennsylvania</li>
<li><strong><a href="http://www.plasmodb.org">PlasmoDB.org</a></strong> --  A genomic database for the malaria-causing parasite Plasmodium falciparum -- CBIL</li>
<li><strong><a href="http://www.cbil.upenn.edu/EPConDB/">EPConDB</a></strong> -- The Endocrine Pancreas Consortium web site -- CBIL</li>
<li><strong><a href="http://www.cbil.upenn.edu/RAD">RAD</a></strong> -- A gene expression database of array-based (microarrays, high-density oligo arrays, macroarrays) and non-array-based (e.g., SAGE) experiments -- CBIL</li>
<li><strong><a href="http://www.allgenes.org/">Allgenes.org</a></strong> -- A human and mouse gene index derived from assembled ESTs and mRNAs -- CBIL</li>
    </ul>
       
<p>If we've incorrectly omitted or included your group in the above list, please contact <a href="mailto:webmaster@gusdb.org">webmaster@gusdb.org</a></p>

<h2>Collaborators</h2>
	<p>GUS is an open source project developed, maintained, and supported by:
	
	<ul>
<li><a href="http://www.cbil.upenn.edu">CBIL</a>: Steve Fischer, Michael Saffitz, Chris Stoeckert, Elisabetta Manduchi,
Junmin Liu, Trish Whetzel, Jonathan Schugg, Thomas Gan, Debbie Pinney, Jennifer Dommer</li>
<li><a href="http://www.genetics.uga.edu/faculty/bio-kissinger.html">The Kissinger Lab</a>: Mark Heiges, Ed Robinson, Jerric Gao, Haiming Wang</li>
<li><a href="https://www.vbi.vt.edu/">VBI</a>: Fidel Sals, Sucheta Tripathy</li>

	</ul>
</p>

<p>If we've incorrectly omitted or included you in the above list, please contact <a href="mailto:webmaster@gusdb.org">webmaster@gusdb.org</a></p>

<h2>Related Projects</h2>
   <ul>
     <li><a href="http://www.gmod.org/">gmod.org</a> - Generic Model Organism Database</li>
     <li><a href="http://fuge.sourceforge.net/">FuGE</a> -- Standards efforts related to functional genomics investigations</li>
   </ul>

<?php include("footer.php"); ?>